"""Root manual proof and sealed independent review adjudication."""
import importlib.util,tempfile
from pathlib import Path
s=importlib.util.spec_from_file_location('m','/Volumes/AI_DATA/development/det-review-evidence/ri122-root-execution-review-6whn_vky/metadata.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=Path(__file__).resolve().parent
Q=m.B/'ri149-singleton-hook-incidence-yfjac93v';R=m.B/'ri149-independent-canonical-review-4hzpisvg'
m.verify(R/'HANDOFF.json',dict(bytes=6704,sha256='4b5382e6cc338ae12371be5005bca119be39461b8fdfceec703f5875431e67d1'))
h=m.load(R/'HANDOFF.json');assert h['recommendation']=='ACCEPT_EXACT_SINGLETON_HOOK_CANONICAL_REDUCTION_WITH_WEIGHTED_FACE_GAP' and not h['repair_findings']
assert sorted(p.name for p in R.iterdir())==sorted(h['namespace']) and len(h['payloads'])==6
for r in h['payloads']:m.verify(r['path'],r)
assert h['subject_handoff']==m.ref(Q/'HANDOFF.json')
for r in m.load(Q/'HANDOFF.json')['payloads']:m.verify(r['path'],r)
for r in m.load(m.D/'ROOT_NATIVE_CHECK.json')['identities']:assert m.identity(r['path'])==r
v=m.load(R/'INDEPENDENT_CANONICAL_REVIEW.json')
decision=m.save('RI149_ROOT_ADJUDICATION.json',dict(schema='ri149-root-canonical-reduction-adjudication-v1',status=h['recommendation'],source_handoff=m.ref(Q/'HANDOFF.json'),independent_review=m.ref(R/'HANDOFF.json'),independent_narrative=m.ref(R/'INDEPENDENT_CANONICAL_REVIEW.md'),root_manual_review=m.ref(m.D/'ROOT_MANUAL_REVIEW.json'),root_metadata_check=m.ref(m.D/'ROOT_NATIVE_CHECK.json'),root_read='a10580 complete independent narrative and handoff; main manuscripts and literal premise spans listed in manual record',actual_checks=dict(root_seal_and_closure='1d4db3 exit0',independent_closure='a73eca exit0',independent_final_seal='f6a08d exit0'),accepted=['Complete two marked singleton-hook components, two parent roles, every proper potential and canonical-only neutral simplification','Exact history-weighted negative target objective columns with four-history factor','Zero/tie-safe residual-capacity saturation and exact two-coordinate primary elimination','Original reconstructed-full-vector canonical lexicographic order and full dual constraints including zero case','Correlated exact q substitution with unresolved fixed canonical weighted comparison'],additional_reviewer_observation_accepted=h['additional_review_observations'],additional_observation_scope='Root independently traced critical483-489 and drift910-979: Q defect0 forbids criticality, fullincrement1 and canonical active-neutral zero-drift force everyQcap equality. This is not a claim about arbitrary primary optima or strict mixed complements.',remaining_actual_premise=h['remaining_actual_premise'],actual_coefficient_ordering_decided=False,actual_rho_in_delta0_proved=False,actual_W_C2_C3_signs_decided=False,full_H30_decided=False,scientific_execution=False,preserved=h['preserved'],ret_paused=True))
print(decision)
nextdir=Path(tempfile.mkdtemp(prefix='ri151-canonical-q-equalities-',dir=m.B))
print(m.save('NATIVE_SUCCESSOR_RESERVATION.json',dict(schema='ri151-native-canonical-q-equality-assignment-v1',status='ASSIGNED_ANALYTIC_PROOF_ONLY_AFTER_RI149_ADJUDICATION',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(nextdir),predecessor=decision,question='Use the accepted stronger consequence that every canonical marked Q=(4,1) row is tight: c_xi*a_i+J_zeta(9)*alpha_c17+J_zeta(11)*alpha_c19=1. Derive the complete intrinsic marked component/incidence relations needed for the other two neutral terminals(4,1,1) and(4,2), retaining all their parent roles, mark transport and global canonical constraints. Exploit allQrow equalities to eliminate nuisance coordinates or prove a concrete identity/inequality for the actual root target contrast entering RI149 weighted q floor and RI147 joint budget. Derive exact symbolic reduced equalities or a justified canonical exchange/dual comparison; if it does not decide the comparison, identify the remaining independent actual-face degrees of freedom and why the available equalities cannot remove them. Do not repeat only the minimum/saturation formula or substitute a freely chosen feasible optimum. Any lexicographic argument must reconstruct the original full vector. A necessary bound may not be called sufficient.',permitted='Manual analytic proof and literal accepted premise/source reading; bounded administrative identity/reference checks. No scientific-body decoding, actual numerical coefficient/probability/history/max/scale/H/z evaluation, engine, subject/helper import/compile/AST/probe/run, global graph enumeration, runtime/controller/card/admission, repository/index/Git or predecessor mutation.',expected='A substantive coupled equality reduction or quantitative comparison with complete incidence and source-premise closure; seal for nonauthor review. Preserve strict restoration and distinguish boundary equality from positive actual full probabilities.',preserved=h['preserved'],measurement='Root RI150 optimized profile actual complete, independent both-mode review underway',ret_paused=True)))
