"""Independent actual reconciliation saved-evidence review. Never runs subjects.
Preparation review primitives and reconstruction reused from my sealed RI230 checker;
new actual operation comparisons independently expressed below.
Only authenticated root metadata.identity/canonical primitives are imported.
Candidate and all scientific files are opaque hash/byte reads, never JSON loads.
"""
from pathlib import Path
import hashlib,json,os,stat,shlex,importlib.util
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri226-directory-custody-recovery-yvfg_p1b';W=D/'worker_proposal';PW=B/'ri229-reconciliation-preparation-t93t1607/worker_proposal';T=B/'ri230-root-lower-combinations-review-v9mxbmtc';R=B/'ri234-independent-reconciliation-review-1t1b_0pb';E=B/'ri154-white-execution-proposed-42_uvw15';O=B/'ri226-freeze-reconciliation-operation-yvfg_p1b'
H=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=H.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('ri230_review_metadata',H);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
labels=[];seen={}
def ck(ok,label):
 labels.append(label)
 if not ok:raise ValueError(label)
def eq(a,b,label):ck(m.canonical(a)==m.canonical(b),label)
def identity(path):
 p=str(path)
 if p not in seen:seen[p]=m.identity(p)
 return seen[p]
def pin(path):return {k:identity(path)[k] for k in ('path','bytes','sha256')}
def verify(ref):eq(pin(ref['path']),{k:ref[k] for k in ('path','bytes','sha256')},'opaque pin '+ref['path'])
def load(path):
 p=Path(path);before=identity(p);data=p.read_bytes();eq(m.pin(data),m.pure(before),'whole administrative bytes '+str(p))
 def pairs(rows):
  out={}
  for key,value in rows:
   if key in out:raise ValueError('duplicate metadata key')
   out[key]=value
  return out
 return json.loads(data,object_pairs_hook=pairs,parse_constant=lambda x:(_ for _ in ()).throw(ValueError(x)))
def state(p):
 a=Path(p).lstat();return [a.st_dev,a.st_ino,a.st_mode,a.st_nlink,a.st_size,a.st_mtime_ns,a.st_ctime_ns]
def observed_rows(rows,label):
 for row in rows:eq(identity(row['path']),row,'entire actual '+label+' '+row['path'])
outputs=['HOST_GENUINE_TOOL.json','HOST_BEFORE.json','RECONCILE_BOOTSTRAP.py','SOURCES_BEFORE.json','SUPPLIER_BEFORE.json','E_BEFORE.json','RECONCILE_PREFLIGHT.json','RECONCILIATION_PROPOSAL.json','PREPARATION_CUSTODY.json']
for name in outputs:
 a=identity(D/name);ck(a['resolved_path']==str(D/name) and a['symlink_chain']==[] and a['state'][3]==1 and a['bytes']<=67108864,'regular literal single-link output '+name)
 if name!='RECONCILE_BOOTSTRAP.py':ck((D/name).read_bytes()==m.canonical(load(D/name)),'entire canonical output '+name)
for n,size,sha in [('GENUINE_PREPARATION_TOOL.json',3113,'afe45fc3982de98e7bde448fe9be75974d273da2f91eee3e6bbb1b64e27a97d1'),('RI229_PREPARATION_SOURCE_ACCEPTANCE.json',2356,'149af89b6d5a7a09c7efb56f2910d272c7f48f6df049da6c40d57268cf697646'),('ROOT_ONE_PREPARATION_DECISION.json',4234,'25fdd96a229961cfd6ed32d232687b5ad5449f25c1dfa9eb584d5aba6a5a0514')]:verify(dict(path=str(T/n),bytes=size,sha256=sha))
c=load(D/'PREPARATION_CUSTODY.json');pre=load(D/'RECONCILE_PREFLIGHT.json');proposal=load(D/'RECONCILIATION_PROPOSAL.json');sources=load(D/'SOURCES_BEFORE.json');supplier=load(D/'SUPPLIER_BEFORE.json');etree=load(D/'E_BEFORE.json');host=load(D/'HOST_BEFORE.json');copyhost=load(D/'HOST_GENUINE_TOOL.json');originalhost=load(T/'GENUINE_PREPARATION_HOST_TOOL.json');root=load(T/'ROOT_ONE_PREPARATION_DECISION.json');decision=load(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json');genuine=load(T/'GENUINE_PREPARATION_TOOL.json')
manifest=load(W/'SOURCE_PINS.json');prepmanifest=load(PW/'SOURCE_PINS.json');rh=load(W/'HANDOFF.json');ph=load(PW/'HANDOFF.json');review=load(D/'ROOT_SOURCE_REVIEW.json');deps=load(PW/'DEPENDENCIES.json');base=load(W/'INPUT_PINS.json');repair=load(W/'REPAIR_PROVENANCE.json');build=load(PW/'BUILD_METADATA.json');g=load(base['roles']['graph']['path']);history=load(base['roles']['historical_supplier']['path']);oldbefore=load(repair['roles']['original_before']['path']);oldobs=load(repair['roles']['original_observations']['path']);oldcomplete=load(repair['roles']['original_complete']['path']);oldpost=load(repair['roles']['postflight']['path']);oldsources=load(repair['roles']['original_sources']['path'])
for directory,handoff in [(W,rh),(PW,ph)]:
 eq(sorted(p.name for p in directory.iterdir()),sorted(handoff['namespace']),'complete unchanged source namespace '+str(directory))
 for row in handoff['files']:verify(row)
for row in manifest['files']+prepmanifest['files']+deps['files']:verify(row)
eq(decision['status'],'ACCEPT_RI229_PREPARATION_SOURCE_ONLY','source-only acceptance');eq(decision['source_manifest'],pin(PW/'SOURCE_PINS.json'),'accepted preparation manifest');eq(decision['recovery_source_review'],pin(D/'ROOT_SOURCE_REVIEW.json'),'accepted recovery decision');eq(decision['packet'],pin(PW/'HANDOFF.json'),'accepted complete preparation packet')
for key in ('independent_review','root_manual_review','root_metadata'):verify(decision[key])
eq(root['status'],'AUTHORIZE_ONE_ADMINISTRATIVE_PREPARATION_ONLY','actual preparation authority only');eq(root['source_review'],pin(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),'one-operation source acceptance');eq(root['source_manifest'],pin(PW/'SOURCE_PINS.json'),'one-operation manifest');eq(root['host'],pin(T/'GENUINE_PREPARATION_HOST_TOOL.json'),'genuine host pin');observed_rows([root['administrative_interpreter'],root['writer']],'root administrative startup binding');eq(root['observed_flags'],dict(isolated=1,dont_write_bytecode=1,optimize=0),'administrative flags');eq([root[k] for k in ['one_attempt','E_write','reconciliation_admitted','reconciliation_dispatched','mode_authority','scientific_execution','qualification_credit','RET_paused']],[True,False,False,False,False,False,0,True],'complete authority scope')
command=['/opt/homebrew/bin/python3','-I','-B',str(PW/'prepare_reconciliation.py'),'--preparation-manifest-bytes',str(pin(PW/'SOURCE_PINS.json')['bytes']),'--preparation-manifest-sha256',pin(PW/'SOURCE_PINS.json')['sha256'],'--preparation-review',str(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),'--preparation-review-bytes',str(root['source_review']['bytes']),'--preparation-review-sha256',root['source_review']['sha256'],'--host-transcript',str(T/'GENUINE_PREPARATION_HOST_TOOL.json'),'--host-transcript-bytes',str(root['host']['bytes']),'--host-transcript-sha256',root['host']['sha256']]
eq(root['command'],command,'entire independently reconstructed preparation argv');args=genuine['initial']['arguments'];eq({k:args[k] for k in ['cmd','workdir','login','yield_time_ms','max_output_tokens']},dict(cmd=shlex.join(command),workdir=str(D),login=False,yield_time_ms=1000,max_output_tokens=4000),'actual preparation command/cwd/flags/transport');ck(set(args)=={'cmd','workdir','login','sandbox_permissions','justification','yield_time_ms','max_output_tokens'},'complete preserved transport argument schema');eq(genuine['initial']['result']['chunk_id'],'0f12a4','actual initial receipt');eq(genuine['initial']['result']['session_id'],16198,'actual initial session');eq(genuine['initial']['result']['output'],'','initial empty output');ck(genuine['initial']['result'].get('exit_code') is None,'initial pending');eq([genuine['terminal']['chunk_id'],genuine['terminal']['exit_code']],['1db8d4',0],'actual final result');ck('session_id' not in genuine['terminal'],'genuine terminal no pending session')
eq(copyhost,originalhost,'entire host canonical copy preserves original value');ck(set(copyhost)=={'schema','arguments','result','observation'},'host record fields')
eq(copyhost['schema'],'ri229-root-genuine-host-tool-transcript-v1','genuine host schema');eq([copyhost['result']['chunk_id'],copyhost['result']['exit_code']],['ff059f',0],'actual host receipt');eq(json.loads(copyhost['result']['output']),copyhost['observation'],'whole real host stdout');obs=copyhost['observation'];eq(obs,dict(command=history['host']['argv'],environment={'PATH':'/usr/bin:/bin','LC_ALL':'C'},returncode=0,stdout=history['host']['stdout'],stderr='',uname=history['host']['uname']),'complete host observation');eq(host,dict(schema='ri209-root-host-command-record-v1',**obs,genuine_tool=pin(D/'HOST_GENUINE_TOOL.json')),'all eight host fields')
VENDOR='/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9';ENV=dict(LC_ALL='C',MKL_NUM_THREADS='1',NUMEXPR_NUM_THREADS='1',OMP_NUM_THREADS='1',OPENBLAS_NUM_THREADS='1',PATH='/usr/bin:/bin',TMPDIR=str(D/'tmp'),TZ='UTC',VECLIB_MAXIMUM_THREADS='1',__CF_USER_TEXT_ENCODING='0x1F5:0x0:0x0');LIMITS=dict(wall_seconds=180,rss_kib=524288,target_poll_seconds=.025,maximum_sample_gap_seconds=.1,ps_timeout_seconds=.05,file_bytes=67108864)
expected_refs={}
for row in base['files']+repair['files']+manifest['files']+[pin(W/'SOURCE_PINS.json'),pin(D/'ROOT_SOURCE_REVIEW.json'),pin(D/'RECONCILE_BOOTSTRAP.py')]:
 ck(row['path'] not in expected_refs or expected_refs[row['path']]==row,'unambiguous source ref');expected_refs[row['path']]=row
eq(len(expected_refs),971,'entire971 source domain');eq([v['path'] for v in sources],sorted(expected_refs),'whole sorted source domain');observed_rows(sources,'current source')
for row in sources:eq({k:row[k] for k in ('path','bytes','sha256')},expected_refs[row['path']],'entire source FilePin')
eq(len(oldsources),904,'original904 count');observed_rows(oldsources,'old source');observed_rows(list(oldbefore['bindings'].values()),'old control binding');eq(oldsources,oldbefore['source_observations'],'whole old source baseline');eq(oldobs['sources_actual'],oldsources,'whole old source tail');eq(oldobs['binding_actual'],oldbefore['bindings'],'whole old binding tail');eq(oldcomplete['status'],'REFUSED_RETAIN_ALL_PARTIALS','old refusal immutable');eq(oldcomplete['first_error'],dict(type='ValueError',message='RI209: root device inode mode links',secondary=[]),'old first error immutable');eq(sorted(p.name for p in Path(repair['roles']['original_complete']['path']).parent.iterdir()),['ATTEMPT.json','BEFORE.json','COMPLETE.json','OBSERVATIONS.json'],'whole old failed operation namespace')
for row in oldpost['operation_files']:verify(row)
eq({k:v for k,v in supplier.items() if k not in ('environment','observed_at_unix_ns')},{k:v for k,v in history.items() if k not in ('environment','observed_at_unix_ns')},'entire inherited supplier shape');eq(supplier['environment'],ENV,'whole supplier environment');ck(type(supplier['observed_at_unix_ns']) is int and supplier['observed_at_unix_ns']>2**53,'integer current recorded observation time');eq([len(supplier['vendor']),sum(v['bytes'] for v in supplier['vendor']),len(supplier['tools']),len(supplier['namespace']),len(supplier['absent'])],[1810,48024515,4,195,2],'complete supplier counts');observed_rows(supplier['vendor']+supplier['tools'],'supplier file')
for row in supplier['namespace']:
 p=Path(row['path']);v=dict(path=str(p),kind=row['kind'],state=state(p))
 if row['kind']=='directory':v['entries']=sorted(x.name for x in p.iterdir())
 else:v['target']=os.readlink(p)
 eq(v,row,'entire fresh supplier namespace '+str(p));eq(state(p),v['state'],'supplier namespace stable')
for p in supplier['absent']:ck(not os.path.lexists(p),'required supplier absence '+p)
eq(list(os.uname()),obs['uname'],'current uname matches genuine host')
# Full read-only E tree without scientific decode.
live=[];stack=[(E,0)];total=0
while stack:
 p,depth=stack.pop();a=state(p);ck(depth<=16 and len(live)<25000 and not p.is_symlink(),'bounded ordinary E entry');row=dict(relative=str(p.relative_to(E)),state=a)
 if stat.S_ISDIR(a[2]):row.update(kind='directory',entries=sorted(x.name for x in p.iterdir()));stack.extend((p/n,depth+1) for n in reversed(row['entries']))
 else:
  ck(stat.S_ISREG(a[2]) and a[4]<=67108864,'bounded E file');ident=identity(p);ck(ident['resolved_path']==str(p) and not ident['symlink_chain'] and ident['state'][3]==1,'literal single-link E file');total+=ident['bytes'];ck(total<=536870912,'aggregate E cap');row.update(kind='file',identity=ident)
 eq(state(p),a,'E entry stable');live.append(row)
for row in live:
 p=E/row['relative'];eq(state(p),row['state'],'E final whole state')
 if row['kind']=='directory':eq(sorted(x.name for x in p.iterdir()),row['entries'],'E final membership')
live.sort(key=lambda x:x['relative']);eq(live,etree,'entire fresh E equals actual prepared E');eq(etree,oldobs['E_after'],'entire prepared E equals retained postwrite baseline');eq([len(live),sum(v['kind']=='file' for v in live),sum(v['kind']=='directory' for v in live)],[58,49,9],'whole E counts');eq(identity(E/'AUTHORIZED_FREEZE.json'),oldpost['installed_partial'],'whole exact retained partial selection');candidate=base['roles']['result'];verify(candidate);ck((E/'AUTHORIZED_FREEZE.json').read_bytes()==Path(candidate['path']).read_bytes(),'whole candidate bytes opaque equality')
for name in ['tmp','runs/normal','runs/optimized']:eq(list((E/name).iterdir()),[],'empty unadmitted E path '+name)
def slim(path):return {k:identity(path)[k] for k in ('path','bytes','sha256','state')}
roles=dict(copies=[dict(relative=x['relative'],original=slim(x['source']['path']),copy=slim(x['destination'])) for x in g['copied_files']],history=[slim(x['path']) for x in g['history_originals']],target_originals=[slim(x['original']) for x in g['sources']]);eq(roles,oldbefore['source_states'],'whole48/124/30 live retained selections')
eq([len(roles[k]) for k in ['copies','history','target_originals']],[48,124,30],'complete roles')
boot=(D/'RECONCILE_BOOTSTRAP.py').read_bytes();ck(boot==(PW/'RECONCILE_BOOTSTRAP.source-only.py').read_bytes(),'whole concrete bootstrap equals accepted source');template=Path(deps['roles']['bootstrap_template']['path']).read_text();changed=template
for old,new in build['bootstrap_replacements']:eq(changed.count(old),1,'single bootstrap adaptation');changed=changed.replace(old,new)
ck(boot==changed.encode(),'entire seven-replacement bootstrap correspondence');MONITOR=deps['roles']['monitor'];verify(MONITOR)
child=[VENDOR,'-I','-B',str(W/'reconcile_freeze.py'),'--admission',str(D/'ADMIT_RECONCILE.json')];call='module.child_run('+repr(child)+', Path('+repr(str(D/'monitor'))+"), 'RECONCILE', 180, expected_environment)";eq([l for l in boot.decode().splitlines() if l.startswith('module.child_run(')],[call],'one whole child call');popen="child = subprocess.Popen(command, stdin=subprocess.DEVNULL, stdout=output, stderr=errors,\n                                     cwd=out, env=env, start_new_session=True)";ck(popen in Path(MONITOR['path']).read_text(),'actual monitor cwd');guard="need(Path.cwd()==literal(D/'monitor') and literal(OUT)==OUT and literal(W)==W,'fixed operation paths')";ck(guard in (W/'reconcile_freeze.py').read_text(),'exact recovery cwd guard');cwd=dict(outer_cwd=str(D),child_cwd=str(D/'monitor'),monitor=MONITOR,exact_popen=popen,generated_child_call=call,reconciler=manifest['files'][4],reconciler_guard=guard,source_text_only=True,subject_execution=False)
expected_pre=dict(schema='ri226-root-reconciliation-preflight-v1',status='FRESH_EXACT_READ_ONLY_RECONCILIATION_PREFLIGHT',sources=pin(D/'SOURCES_BEFORE.json'),supplier=pin(D/'SUPPLIER_BEFORE.json'),E_before=pin(D/'E_BEFORE.json'),host_tool_receipts=pin(D/'HOST_BEFORE.json'),monitor_bootstrap=pin(D/'RECONCILE_BOOTSTRAP.py'),source_manifest=pin(W/'SOURCE_PINS.json'),environment=ENV,scientific_execution=False);eq(pre,expected_pre,'all ten preflight fields')
card=dict(schema='ri226-root-read-only-reconciliation-admission-v1',status='AUTHORIZE_ONE_READ_ONLY_RECONCILIATION',source_manifest=pin(W/'SOURCE_PINS.json'),source_review=pin(D/'ROOT_SOURCE_REVIEW.json'),preflight=pin(D/'RECONCILE_PREFLIGHT.json'),output=str(O),environment=ENV,limits=LIMITS,genuine_outer_required=True)
outer=['/usr/bin/env','-i',*[k+'='+v for k,v in ENV.items()],'/usr/bin/perl','-e','$SIG{ALRM}="DEFAULT"; alarm 960; exec @ARGV; die $!;',VENDOR,'-I','-B',str(D/'RECONCILE_BOOTSTRAP.py')];dispatch=dict(outer_argv=outer,shell_command=shlex.join(outer),cwd=str(D),login=False,bootstrap=pin(D/'RECONCILE_BOOTSTRAP.py'),monitor_source=MONITOR,external_timeout_seconds=960,single_attempt=True,actual_execution_not_yet_started=True)
eq(proposal,dict(schema='ri229-unissued-reconciliation-proposal-v1',status='UNISSUED_REQUIRES_ROOT_PREFLIGHT_REVIEW',proposed_admission_fields=card,future_admission_path=str(D/'ADMIT_RECONCILE.json'),dispatch_fields_without_admission=dispatch,active_card_created=False,dispatch_created=False),'entire seven-field proposal with all9+9 nested fields')
packet=[identity(x['path']) for x in rh['files']]+[identity(W/'HANDOFF.json')];review_support=[identity(review[k]['path']) for k in ('independent_review','root_metadata_check','root_manual_review')];prep_support=[identity(PW/'SOURCE_PINS.json'),identity(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json')]+[identity(x['path']) for x in prepmanifest['files']];depstates=[identity(x['path']) for x in deps['files']]
expected_c=dict(schema='ri229-root-preparation-custody-v1',status='PREPARED_NOT_ADMITTED_OR_DISPATCHED',sealed_source_packet=packet,root_review_support=review_support,preparation_source_manifest=pin(PW/'SOURCE_PINS.json'),preparation_source_review=pin(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),preparation_support=prep_support,preparation_dependency_states=depstates,retained_failure=repair['roles']['original_complete'],retained_postflight=repair['roles']['postflight'],original_genuine_host=pin(T/'GENUINE_PREPARATION_HOST_TOOL.json'),canonical_genuine_host=pin(D/'HOST_GENUINE_TOOL.json'),monitor_template=deps['roles']['bootstrap_template'],bootstrap_replacements=build['bootstrap_replacements'],cwd_contract=cwd,source_domain=971,original_source_observation=repair['roles']['original_sources'],original_bindings=oldbefore['bindings'],root_namespace_before=['ROOT_SOURCE_REVIEW.json','worker_proposal'],root_namespace_expected_after=sorted(['ROOT_SOURCE_REVIEW.json','worker_proposal']+outputs+['tmp','monitor']),produced_before_custody={n:pin(D/n) for n in outputs[:-1]},prior_roles=810,copy_history_targets=[48,124,30],source_observations=pin(D/'SOURCES_BEFORE.json'),supplier_observation=pin(D/'SUPPLIER_BEFORE.json'),E_observation=pin(D/'E_BEFORE.json'),preflight=pin(D/'RECONCILE_PREFLIGHT.json'),unissued_proposal=pin(D/'RECONCILIATION_PROPOSAL.json'),preparation_source=pin(PW/'prepare_reconciliation.py'),tool_origin_and_startup_are_root_premises=True,scientific_execution=False,reconciliation_admitted=False,reconciliation_dispatched=False,E_read_only=True,ret_paused=True);eq(c,expected_c,'entire35-field custody including all nested fields')
summary=json.loads(genuine['terminal']['output']);eq(summary,dict(status='PREPARED_FOR_ROOT_PREFLIGHT_REVIEW_NO_ADMISSION',proposal=pin(D/'RECONCILIATION_PROPOSAL.json'),custody=pin(D/'PREPARATION_CUSTODY.json'),exact_tool_arguments=dict(cmd=dispatch['shell_command'],workdir=str(D),login=False,yield_time_ms=1000,max_output_tokens=4000)),'whole genuine terminal stdout binding')
# New actual reconciliation reconstruction. Every JSON body below is administrative.
import math
A=B/'ri234-root-reconciliation-tzop5ais'
def closed(value,keys,label):ck(type(value) is dict and set(value)==set(keys.split()),label+' complete fields')
def finite(v,label):ck(type(v) in (int,float) and math.isfinite(v),label+' finite exact numeric type')
def timing_check(v,elapsed,label):
 closed(v,'initial final elapsed',label)
 for n in ('initial','final','elapsed'):
  closed(v[n],'value error',label+' '+n);eq(v[n]['error'],None,label+' error '+n);finite(v[n]['value'],label+' '+n)
 eq(v['elapsed']['value'],v['final']['value']-v['initial']['value'],label+' difference');eq(v['elapsed']['value'],elapsed,label+' whole elapsed');ck(0<=elapsed<=180,label+' elapsed bound')
# Retained refusal remains completely intact, including all failed and successful tails.
closed(oldbefore,'E source_states source_observations bindings','historical BEFORE')
closed(oldobs,'E_after binding_actual installation_write sources_actual supplier_actual','historical OBSERVATIONS')
closed(oldcomplete,'schema status admission candidate destination first_error independent_tails produced_outputs elapsed_seconds_before_complete_write timing complete_not_self_hashed scientific_execution mode_admission_issued ret_paused','historical COMPLETE')
OLD=Path(repair['roles']['original_complete']['path']).parent
oldpins={n:pin(OLD/n) for n in ['ATTEMPT.json','BEFORE.json','OBSERVATIONS.json']};old_error=dict(message='RI209: root device inode mode links',secondary=[],type='ValueError')
eq(oldcomplete['produced_outputs'],oldpins,'all historical produced outputs');eq(oldobs['installation_write'],dict(error=None,cleanup_errors=[]),'prior write succeeded but operation refused')
eq(oldcomplete['admission'],{k:oldbefore['bindings']['admission'][k] for k in ('path','bytes','sha256')},'historical admission full pin')
eq(load(OLD/'ATTEMPT.json'),dict(schema='ri209-exclusive-install-attempt-v1',admission=oldcomplete['admission'],candidate=candidate,destination=str(E/'AUTHORIZED_FREEZE.json'),no_retry=True,scientific_execution=False),'entire historical ATTEMPT')
oldtails={k:dict(error=None,value=v) for k,v in dict(source_inputs=oldsources,root_bindings=oldbefore['bindings'],supplier=oldobs['supplier_actual'],save_observations=oldpins['OBSERVATIONS.json'],ordinary_outputs=oldpins,output_namespace=[identity(OLD/n) for n in sorted(oldpins)]).items()}
oldtails.update({n:dict(error=old_error,value=None) for n in ['E_and_frozen','final_E']});eq(oldcomplete['independent_tails'],oldtails,'all eight historical whole tail records')
eq([oldcomplete[k] for k in ['schema','status','candidate','destination','first_error','complete_not_self_hashed','scientific_execution','mode_admission_issued','ret_paused']],['ri213-installation-completion-v1','REFUSED_RETAIN_ALL_PARTIALS',candidate,str(E/'AUTHORIZED_FREEZE.json'),old_error,True,False,False,True],'all historical terminal fields');timing_check(oldcomplete['timing'],oldcomplete['elapsed_seconds_before_complete_write'],'historical timing')
eq(load(repair['roles']['supersession']['path'])['status'],'OPERATIONAL_READINESS_SUPERSEDED_AFTER_ACTUAL_POSTWRITE_REFUSAL','retained operational supersession')
eq([oldpost[k] for k in ['status','first_error','failed_tails','passed_tail_count']],['REFUSAL_AND_RETAINED_PARTIALS_CONFIRMED_NOT_INSTALLATION_ACCEPTANCE',old_error,['E_and_frozen','final_E'],6],'retained independent postflight result')
oldmap={x['relative']:x for x in oldbefore['E']};postmap={x['relative']:x for x in oldobs['E_after']}
eq([len(oldbefore['E']),len(oldmap),len(postmap)],[57,57,58],'historical complete unique tree');eq(sorted(set(postmap)-set(oldmap)),['AUTHORIZED_FREEZE.json'],'historical one addition');eq(sorted(set(oldmap)-set(postmap)),[],'historical no removals');eq(oldmap['.'],oldpost['root_before'],'whole old root');eq({k:postmap['.'][k] for k in ['state','entries']},oldpost['root_after'],'whole retained root');eq(oldmap['.']['state'][:3],postmap['.']['state'][:3],'device inode mode preserved');eq([oldmap['.']['state'][3],postmap['.']['state'][3]],[23,24],'observed historical link transition');eq(postmap['.']['entries'],sorted(oldmap['.']['entries']+['AUTHORIZED_FREEZE.json']),'historical exact root membership')
for n,v in oldmap.items():
 if n!='.':eq(postmap[n],v,'whole historical unchanged member '+n)
retained=dict(E=oldobs['E_after'],source_states=oldbefore['source_states'],original_complete=repair['roles']['original_complete'],postflight=repair['roles']['postflight'],original_status='REFUSED_RETAIN_ALL_PARTIALS')
# Independently bound actual root authority to accepted complete preparation.
verify(dict(path=str(T/'ACTUAL_PREPARATION_ACCEPTANCE.json'),bytes=8585,sha256='28d04703c3ce81c952c1ba34a2b2c4cd5021a4411c76fa0fd5871722a1a26fd8'))
accepted_prep=load(T/'ACTUAL_PREPARATION_ACCEPTANCE.json');eq(accepted_prep['outputs'],[identity(D/n) for n in outputs],'all nine accepted full output selections retained')
actual_card=load(D/'ADMIT_RECONCILE.json');actual_dispatch=load(D/'DISPATCH.json');eq(actual_card,card,'entire actual admission equals independently built nine-field card');eq(actual_dispatch,dict(dispatch,admission=pin(D/'ADMIT_RECONCILE.json')),'entire actual dispatch equals reviewed proposal plus real admission pin')
authority=load(A/'ROOT_ONE_RECONCILIATION_DECISION.json');fresh=load(A/'FRESH_PREDISPATCH_CHECK.json');issued=load(A/'ISSUED_CONTROLS.json');peer=load(A/'PREDISPATCH_PEER_CLEARANCE.json')
eq(fresh['outputs'],accepted_prep['outputs'],'fresh root observation anchored to full actual accepted preparation');eq(fresh['accepted_preparation'],pin(T/'ACTUAL_PREPARATION_ACCEPTANCE.json'),'predispatch accepted history binding');eq(fresh['status'],'PASS_FRESH_RECONCILIATION_PREDISPATCH_CUSTODY','root predispatch scope');eq(peer['disposition'],'NO_BLOCKER_TO_ONE_READ_ONLY_OPERATION','peer clearance bounded');eq(peer['reservation'],str(R),'own peer reservation')
expected_authority=dict(schema='ri234-root-one-read-only-operation-decision-v1',status='AUTHORIZE_ONE_RI226_READ_ONLY_RECONCILIATION',accepted_preparation=pin(T/'ACTUAL_PREPARATION_ACCEPTANCE.json'),source_review=pin(D/'ROOT_SOURCE_REVIEW.json'),fresh_current_custody=pin(A/'FRESH_PREDISPATCH_CHECK.json'),genuine_current_host=pin(A/'GENUINE_PREDISPATCH_HOST.json'),independent_predispatch_review=pin(A/'PREDISPATCH_PEER_CLEARANCE.json'),proposal=pin(D/'RECONCILIATION_PROPOSAL.json'),admission_fields=card,dispatch_fields_without_admission=dispatch,administrative_interpreter=identity('/opt/homebrew/bin/python3'),issuer=pin(A/'issue_controls.py'),original_failure_remains_refused=True,E_read_only=True,one_attempt_no_retry=True,original_limits_unchanged=True,scientific_execution=False,mode_admission=False,independent_postreview_required=True,RET_paused=True,premises=['Stable host and declared supplier selections during observed intervals','Apple loader/cache/kernel and prior runtime applicability remain explicit conditional premises','No descendants; sampled sole-child RSS is not continuous whole-process-group accounting','Historical preparation records are immutable; this decision uses fresh current identity and genuine host rechecks']);eq(authority,expected_authority,'whole root one-operation authority')
closed(issued,'admission decision dispatch genuine_predispatch_check observed_at_unix_ns operation_not_started','whole issuance schema');eq({k:v for k,v in issued.items() if k!='observed_at_unix_ns'},dict(admission=identity(D/'ADMIT_RECONCILE.json'),decision=pin(A/'ROOT_ONE_RECONCILIATION_DECISION.json'),dispatch=identity(D/'DISPATCH.json'),genuine_predispatch_check=dict(exit_code=0,initial_chunk='480a86',session_id=74231,terminal_chunk='c6a559'),operation_not_started=True),'all issuance fields except declared timestamp');ck(type(issued['observed_at_unix_ns']) is int and issued['observed_at_unix_ns']>2**53,'issuance integer timestamp')
outer_evidence=load(A/'GENUINE_OUTER.json');eq(outer_evidence,dict(schema='ri226-root-genuine-reconciliation-v1',dispatch=pin(D/'DISPATCH.json'),monitor=pin(D/'monitor/RECONCILE.COMPLETION.json'),post_host_tools=pin(A/'POST_HOST.json'),post_supplier=pin(A/'POST_SUPPLIER.json'),tool_transcript=pin(A/'GENUINE_RECONCILIATION_TOOL.json')),'whole six-field genuine outer envelope')
transcript=load(A/'GENUINE_RECONCILIATION_TOOL.json');closed(transcript,'initial_arguments initial_result intermediate_calls terminal_arguments terminal_result','complete genuine transcript')
eq(transcript['initial_arguments'],dict(cmd=dispatch['shell_command'],workdir=str(D),login=False,max_output_tokens=4000,yield_time_ms=1000),'actual whole command cwd flags arguments')
closed(transcript['initial_result'],'chunk_id original_token_count output session_id wall_time_seconds','initial actual result');eq({k:v for k,v in transcript['initial_result'].items() if k!='wall_time_seconds'},dict(chunk_id='5709fd',original_token_count=0,output='',session_id=77528),'actual initial receipt');finite(transcript['initial_result']['wall_time_seconds'],'initial tool elapsed')
eq(transcript['intermediate_calls'],[],'no unrecorded intermediate polls');eq(transcript['terminal_arguments'],dict(chars='',max_output_tokens=4000,session_id=77528,yield_time_ms=1000),'actual exact terminal poll linkage')
closed(transcript['terminal_result'],'chunk_id exit_code original_token_count output wall_time_seconds','terminal actual result');eq({k:v for k,v in transcript['terminal_result'].items() if k!='wall_time_seconds'},dict(chunk_id='d0b911',exit_code=0,original_token_count=0,output=''),'actual successful terminal receipt');finite(transcript['terminal_result']['wall_time_seconds'],'terminal tool elapsed')
transport=load(A/'GENUINE_RECONCILIATION_TRANSPORT.json');closed(transport,'justification sandbox_permissions','genuine transport-only fields');eq(transport['sandbox_permissions'],'require_escalated','historical transport permission');ck(type(transport['justification']) is str and len(transport['justification'])>0,'retained genuine transport explanation')
# Independently read genuine host raw stdout. No host/probe is run by this reviewer.
hostcmd="/opt/homebrew/bin/python3 -I -B - <<'PY'\nimport json,os,subprocess\nargs=['/usr/bin/sw_vers'];env=dict(PATH='/usr/bin:/bin',LC_ALL='C');p=subprocess.run(args,env=env,capture_output=True,text=True)\nprint(json.dumps(dict(command=args,environment=env,returncode=p.returncode,stdout=p.stdout,stderr=p.stderr,uname=list(os.uname()))))\nPY"
expected_host_obs=dict(command=['/usr/bin/sw_vers'],environment=dict(PATH='/usr/bin:/bin',LC_ALL='C'),returncode=0,stderr='',stdout=history['host']['stdout'],uname=history['host']['uname'])
for name,chunk in [('GENUINE_PREDISPATCH_HOST.json','c804b9'),('GENUINE_POST_HOST.json','1b4e18')]:
 hv=load(A/name);closed(hv,'arguments observation result','actual host transcript');eq(hv['arguments'],dict(cmd=hostcmd,login=False,max_output_tokens=4000,yield_time_ms=1000),'entire actual host arguments '+name);eq(hv['observation'],expected_host_obs,'whole actual host observation '+name);eq(json.loads(hv['result']['output']),expected_host_obs,'whole raw genuine host stdout '+name);closed(hv['result'],'chunk_id exit_code original_token_count output wall_time_seconds','host terminal');eq([hv['result']['chunk_id'],hv['result']['exit_code']],[chunk,0],'host actual terminal result '+name);ck('session_id' not in hv['result'],'no host pending session')
eq(load(A/'POST_HOST.json'),dict(schema='ri209-root-host-command-record-v1',**expected_host_obs,genuine_tool=pin(A/'GENUINE_POST_HOST.json')),'all post host fields')
post_supplier=load(A/'POST_SUPPLIER.json');eq({k:v for k,v in post_supplier.items() if k!='observed_at_unix_ns'},{k:v for k,v in supplier.items() if k!='observed_at_unix_ns'},'whole supplier bracket unchanged except observation instant');ck(type(post_supplier['observed_at_unix_ns']) is int and post_supplier['observed_at_unix_ns']>supplier['observed_at_unix_ns'],'fresh integer supplier observation time')
# Entire current operation records; no scientific/candidate body is parsed.
binding_refs=dict(admission=pin(D/'ADMIT_RECONCILE.json'),preflight=pin(D/'RECONCILE_PREFLIGHT.json'),source_manifest=pin(W/'SOURCE_PINS.json'),source_review=pin(D/'ROOT_SOURCE_REVIEW.json'),sources=pin(D/'SOURCES_BEFORE.json'),supplier=pin(D/'SUPPLIER_BEFORE.json'),E_before=pin(D/'E_BEFORE.json'),host_tool_receipts=pin(D/'HOST_BEFORE.json'),monitor_bootstrap=pin(D/'RECONCILE_BOOTSTRAP.py'))
bindings={k:identity(v['path']) for k,v in binding_refs.items()}
for k,v in bindings.items():eq({n:v[n] for n in ('path','bytes','sha256')},binding_refs[k],'full actual control binding '+k)
eq(load(O/'BEFORE.json'),dict(E=live,source_states=roles,source_observations=sources,bindings=bindings),'complete current BEFORE')
for row,decl in zip(roles['copies'],g['copied_files']):eq(m.pure(row['original']),m.pure(decl['source']),'copy source declaration');eq(m.pure(row['copy']),m.pure(decl['source']),'copy bytes declaration')
for row,decl in zip(roles['history'],g['history_originals']):eq(m.pure(row),m.pure(decl),'history declaration')
for row,decl in zip(roles['target_originals'],g['sources']):eq(m.pure(row),decl['pin'],'target original declaration')
accepted_candidate=load(base['roles']['candidate_acceptance']['path']);eq(accepted_candidate['result'],candidate,'candidate accepted whole pin');eq([accepted_candidate['status'],accepted_candidate['candidate_is_complete_canonical_result'],accepted_candidate['freeze_installed']],['ACCEPT_COMPLETE_ADMINISTRATIVE_FREEZE_CANDIDATE',True,False],'candidate acceptance remains distinct from operation');eq(sorted(load(base['roles']['historical_E']['path']),key=lambda v:v['relative']),oldbefore['E'],'original accepted E historical whole tree')
eq(load(O/'ATTEMPT.json'),dict(schema='ri226-exclusive-read-only-reconciliation-attempt-v1',admission=pin(D/'ADMIT_RECONCILE.json'),candidate=candidate,destination=str(E/'AUTHORIZED_FREEZE.json'),original_complete=retained['original_complete'],original_status=retained['original_status'],postflight=retained['postflight'],E_read_only=True,no_retry=True,scientific_execution=False),'complete ten-field ATTEMPT')
frozen=dict(schema='ri156-complete-copy-card-observation-v1',root=str(E),stage='frozen',source_states=roles,cards={'AUTHORIZED_FREEZE.json':slim(E/'AUTHORIZED_FREEZE.json')},tree=[dict(relative=r['relative'],kind=r['kind'],**(m.pure(r['identity']) if r['kind']=='file' else {})) for r in live],tmp_empty=True,scientific_body_decoded=False,source_acceptance_created=False);eq(load(O/'FROZEN.json'),frozen,'entire independently reconstructed nine-field FROZEN')
supplier_actual=dict(files=[identity(v['path']) for v in supplier['vendor']+supplier['tools']],namespace=supplier['namespace'],absent=[dict(path=p,absent=True) for p in supplier['absent']],uname=list(os.uname()))
observation=dict(E_after=live,binding_actual=bindings,frozen=frozen,read_only_reconciliation=dict(original_complete=retained['original_complete'],original_status=retained['original_status'],postflight=retained['postflight'],E_read_only=True),retained_failure_after=retained,source_states_after=roles,sources_actual=sources,supplier_actual=supplier_actual);eq(load(O/'OBSERVATIONS.json'),observation,'whole eight-field OBSERVATIONS')
produced={n:pin(O/n) for n in ['ATTEMPT.json','BEFORE.json','FROZEN.json','OBSERVATIONS.json']}
tailvalues=dict(source_inputs=sources,root_bindings=bindings,supplier=supplier_actual,E_and_frozen=produced['FROZEN.json'],save_observations=produced['OBSERVATIONS.json'],ordinary_outputs=produced,final_E=live,output_namespace=[identity(O/n) for n in sorted(produced)])
complete=load(O/'COMPLETE.json');timing_check(complete['timing'],complete['elapsed_seconds_before_complete_write'],'current operation timing')
expected_complete=dict(schema='ri226-read-only-reconciliation-completion-v1',status='RECONCILED_PENDING_INDEPENDENT_ROOT_REVIEW',admission=pin(D/'ADMIT_RECONCILE.json'),candidate=candidate,destination=str(E/'AUTHORIZED_FREEZE.json'),original_complete=retained['original_complete'],original_status=retained['original_status'],postflight=retained['postflight'],E_read_only=True,first_error=None,independent_tails={k:dict(error=None,value=v) for k,v in tailvalues.items()},produced_outputs=produced,elapsed_seconds_before_complete_write=complete['elapsed_seconds_before_complete_write'],timing=complete['timing'],complete_not_self_hashed=True,scientific_execution=False,mode_admission_issued=False,ret_paused=True);eq(complete,expected_complete,'entire18-field COMPLETE and all eight exact tail values')
eq(sorted(p.name for p in O.iterdir()),sorted(list(produced)+['COMPLETE.json']),'entire five-file operation namespace')
for p in O.iterdir():
 i=identity(p);ck(i['resolved_path']==str(p) and i['symlink_chain']==[] and stat.S_ISREG(i['state'][2]) and i['state'][3]==1 and i['bytes']<=67108864,'bounded regular operation output');ck(p.read_bytes()==m.canonical(load(p)),'entire canonical operation record')
# Every monitor sample/attempt, including initial and terminal sampling gap.
monitor=load(D/'monitor/RECONCILE.COMPLETION.json');closed(monitor,'child_exit_code command elapsed_seconds environment final_sample_gap_passed final_sample_to_reap_gap_seconds first_error monitor_attempts passed peak_sampled_rss_kib samples stderr stdout stop_reason tail_errors wall_seconds','entire monitor receipt')
eq([monitor[k] for k in ['child_exit_code','command','environment','final_sample_gap_passed','first_error','passed','stop_reason','tail_errors','wall_seconds']],[0,child,ENV,True,None,True,None,[],180],'all fixed monitor fields');finite(monitor['elapsed_seconds'],'monitor elapsed');ck(0<monitor['elapsed_seconds']<180,'strict monitor wall limit');eq([len(monitor['samples']),len(monitor['monitor_attempts'])],[63,63],'complete63 actual samples and raw attempts')
lasttime=0
for ix,(raw,sample) in enumerate(zip(monitor['monitor_attempts'],monitor['samples'])):
 closed(raw,'elapsed_seconds returncode stdout stderr','raw attempt '+str(ix));closed(sample,'elapsed_seconds rss_kib gap_seconds','sample '+str(ix));eq(raw['returncode'],0,'raw ps exit');eq(raw['stderr'],'','raw ps stderr');ck(type(raw['stdout']) is str and raw['stdout'].strip().isdigit(),'raw whole RSS parse');eq(int(raw['stdout'].strip()),sample['rss_kib'],'parsed raw RSS equals saved sample');eq(raw['elapsed_seconds'],sample['elapsed_seconds'],'raw and sample timestamps');finite(sample['elapsed_seconds'],'sample time');finite(sample['gap_seconds'],'sample gap');ck(type(sample['rss_kib']) is int and 0<=sample['rss_kib']<=524288,'sample integer RSS bound');ck(0<=sample['gap_seconds']<=.1 and abs(sample['elapsed_seconds']-lasttime-sample['gap_seconds'])<1e-12,'whole sample arithmetic and gap');ck(lasttime<=sample['elapsed_seconds']<=monitor['elapsed_seconds'],'sample monotonic and pre-reap');lasttime=sample['elapsed_seconds']
finite(monitor['final_sample_to_reap_gap_seconds'],'final gap');ck(abs(monitor['elapsed_seconds']-lasttime-monitor['final_sample_to_reap_gap_seconds'])<1e-12 and 0<=monitor['final_sample_to_reap_gap_seconds']<=.1,'entire final sample-to-reap gap');eq(monitor['peak_sampled_rss_kib'],max(v['rss_kib'] for v in monitor['samples']),'computed peak RSS');eq(monitor['peak_sampled_rss_kib'],74208,'actual observed peak')
for key in ['stdout','stderr']:
 eq(monitor[key],pin(D/'monitor'/('RECONCILE.'+key)),'entire monitor stream identity');eq(monitor[key]['bytes'],0,'empty actual bounded stream')
ma=load(D/'monitor/RECONCILE.ATTEMPT.json');closed(ma,'command environment pid_owner scientific_target_entry wall_seconds','complete monitor ATTEMPT');eq({k:v for k,v in ma.items() if k!='pid_owner'},dict(command=child,environment=ENV,scientific_target_entry=False,wall_seconds=180),'whole monitor ATTEMPT except parent pid');ck(type(ma['pid_owner']) is int and ma['pid_owner']>0,'parent PID retained not child identity');eq(sorted(p.name for p in (D/'monitor').iterdir()),['RECONCILE.ATTEMPT.json','RECONCILE.COMPLETION.json','RECONCILE.stderr','RECONCILE.stdout'],'whole four-file monitor namespace')
# Same-author checker is an attributed outcome, not the oracle for our checks.
sameauthor=load(D/'RECONCILIATION_POSTCHECK.json');expected_post=dict(schema='ri226-independent-reconciliation-postcheck-v1',status='PASS_READ_ONLY_RECONCILIATION_PENDING_ROOT_ACCEPTANCE',checks=161124,admission=pin(D/'ADMIT_RECONCILE.json'),candidate=candidate,original_complete=retained['original_complete'],original_status=retained['original_status'],retained_postflight=retained['postflight'],E_read_only=True,installed_freeze=pin(E/'AUTHORIZED_FREEZE.json'),frozen_observation=produced['FROZEN.json'],complete=pin(O/'COMPLETE.json'),whole_E=live,source_files=971,copy_pairs=48,history_roles=124,target_original_roles=30,E_files=49,E_directories=9,prior_roles=base['prior_role_count'],operation_files=5,monitor_files=4,genuine_outer=pin(A/'GENUINE_OUTER.json'),external_tool_origin_and_host_receipts_require_root_review=True,scientific_execution=False,mode_admission_issued=False,ret_paused=True);eq(sameauthor,expected_post,'entire attributed postcheck result independently reconstructed except attributed count')
posttool=load(A/'GENUINE_POSTCHECK_TOOL.json');closed(posttool,'arguments initial','same-author genuine tool record');eq(posttool['arguments']['cmd'],shlex.join(['/opt/homebrew/bin/python3','-I','-B',str(W/'check_reconciliation.py'),'--outer',str(A/'GENUINE_OUTER.json'),'--report',str(D/'RECONCILIATION_POSTCHECK.json')]),'exact sameauthor checker command');eq([posttool['initial']['chunk_id'],posttool['initial']['exit_code']],['cfb84c',0],'actual sameauthor checker terminal');ck('session_id' not in posttool['initial'],'sameauthor checker synchronous terminal');eq(json.loads(posttool['initial']['output']),dict(report=pin(D/'RECONCILIATION_POSTCHECK.json'),checks=161124,status=expected_post['status']),'whole raw sameauthor checker stdout')
# Literal review of the pre-execution collector correction, not execution.
oldcap=(A/'capture_post.py').read_text();newcap=(A/'capture_post_v2.py').read_text();oldfrag="host=dict(argv=obs['command'],stdout=obs['stdout'],uname=list(os.uname()))";newfrag="host=dict(argv=obs['command'],exit_code=obs['returncode'],stderr=obs['stderr'],stdout=obs['stdout'],uname=list(os.uname()))";eq(oldcap.count(oldfrag),1,'one old collector host literal');ck(newcap==oldcap.replace(oldfrag,newfrag),'whole collector V2 delta exactly two added host fields')
# Repeated final finite current selection evidence; no regeneration or execution.
eq(sorted(p.name for p in D.iterdir()),sorted(expected_c['root_namespace_expected_after']+['ADMIT_RECONCILE.json','DISPATCH.json','RECONCILIATION_POSTCHECK.json']),'exact16 root namespace');eq(list((D/'tmp').iterdir()),[],'temporary directory empty')
for p in [E/'ADMIT_NORMAL.json',E/'ADMIT_OPTIMIZED.json']:ck(not os.path.lexists(p),'no mode authority '+str(p))
for row in live:
 p=E/row['relative'];eq(state(p),row['state'],'final current E state')
 if row['kind']=='directory':eq(sorted(v.name for v in p.iterdir()),row['entries'],'final current E membership')
for p,row in list(seen.items()):eq(m.identity(p),row,'whole final observed selection stable '+p)
result=dict(schema='ri234-independent-actual-reconciliation-check-v1',status='PASS_COMPLETE_ACTUAL_READ_ONLY_RECONCILIATION_CUSTODY_PENDING_ROOT_ACCEPTANCE',checks=len(labels),labels=labels,whole_file_identities=[seen[p] for p in sorted(seen)],counts=dict(distinct_files=len(seen),source_domain=971,old_sources=904,prepared_outputs=9,preparation_dependencies=992,vendor=1810,vendor_bytes=48024515,tools=4,supplier_namespace=195,supplier_absences=2,E_files=49,E_directories=9,copy_pairs=48,history_roles=124,target_original_roles=30,prior_roles=810,operation_files=5,monitor_files=4,monitor_samples=63,monitor_raw_attempts=63,independent_tails=8),genuine=pin(A/'GENUINE_OUTER.json'),operation_files=[identity(O/n) for n in sorted(list(produced)+['COMPLETE.json'])],whole_E=live,monitor_summary=dict(elapsed_seconds=monitor['elapsed_seconds'],peak_sampled_rss_kib=monitor['peak_sampled_rss_kib'],maximum_sample_gap_seconds=max(v['gap_seconds'] for v in monitor['samples']),final_gap_seconds=monitor['final_sample_to_reap_gap_seconds'],initial_chunk='5709fd',session=77528,terminal_chunk='d0b911',exit_code=0),original_status='REFUSED_RETAIN_ALL_PARTIALS',actual_operation_status=complete['status'],scientific_body_decoded=False,subject_execution_by_reviewer=False,mode_admission=False,qualification_credit=0,RET_paused=True)
raw=m.canonical(result)
with (R/'CHECK_RESULT.json').open('xb') as f:f.write(raw);f.flush();os.fsync(f.fileno())
print(json.dumps(dict(report=dict(path=str(R/'CHECK_RESULT.json'),bytes=len(raw),sha256=hashlib.sha256(raw).hexdigest()),checks=len(labels),whole_files=len(seen),counts=result['counts'],monitor=result['monitor_summary'],status=result['status'])))
