"""
DET v8.1 — Correlation-Class Theorem (T6)

Characterize the bipartite correlation classes generated by a lawful local
pair-kernel 𝔇 in the (2,2,2) scenario (two parties, two binary settings each,
two binary outcomes), and then optimize CHSH in each class:

    local (classical)  ⊆  quantum  ⊆  almost-quantum  ⊆  no-signalling
        |S| ≤ 2            2√2           2√2               4

THE HONEST RESULT UP FRONT: strong positivity + composition do NOT isolate the
quantum set. The natural DET pair-kernel relaxation is the ALMOST-QUANTUM set
Q̃ (the first NPA level), which is strictly larger than the quantum set Q and
strictly smaller than the no-signalling set NS. Whether a DET-native condition
— "global record extendability" (𝔇_n = Marginal(𝔇_{n+1}) for every lawful
future refinement) — collapses Q̃ down to Q is the open question this module
frames but does NOT resolve. If it cannot be forced, DET derives "almost
quantum", not quantum mechanics — a refutation of the "DET derives QM" claim,
not a confirmation.

What is implemented rigorously (pure stdlib, no external SDP solver):

  - the no-signalling polytope and the local (classical) polytope exactly,
    via the 8 CHSH facets (Fine's theorem);
  - the Tsirelson bound 2√2 as a sum-of-squares / operator-norm certificate
    (B² = 4I − [A₀,A₁][B₀,B₁]); this bound applies to BOTH quantum and
    almost-quantum, so CHSH alone cannot separate them;
  - the almost-quantum set as the NPA level-1 moment matrix Γ (9×9);
    membership is VERIFIED by an explicit PSD Γ for the Bell state, and the
    PR box is shown to lie OUTSIDE Q̃ (it violates the 2√2 bound);
  - global record extendability as its concrete operational form: the level-1
    Γ must embed as a principal submatrix of a PSD level-2 moment matrix Γ²
    (13×13). Demonstrated on the Bell state (extends) and the PR box (already
    excluded at level 1).

What is NOT done here (stated to avoid overclaiming):

  - a general SDP feasibility solver for arbitrary Q̃ membership (the codebase
    convention is pure stdlib; membership here is by explicit certificate);
  - the strict inclusion Q ⊊ Q̃ is CITED (Navascués, Guryanova, Acín, Pironio
    2015), not re-derived — no explicit almost-quantum-but-not-quantum witness
    is constructed;
  - the "global record extendability ⇒ Q" collapse is stated as a conjecture
    (AX-DET candidate), not a theorem.

DERIVATION CERTIFICATE (honest provenance):

  no-signalling polytope         MATH — standard linear constraints.
  local polytope / 8 CHSH facets MATH — Fine (1982); Clauser–Horne–Shimony–
                                          Holt (1969), credited.
  Tsirelson bound 2√2            MATH — Cirel'son (1980); SOS/operator-norm
                                          certificate, credited.
  almost-quantum = NPA level 1   MATH — Navascués–Pironio–Acín (2008);
                                          Navascués et al. (2015), credited.
  Q ⊆ Q̃                          TH-DET — a quantum pair-kernel Gram vector
                                          realization induces a level-1 Γ.
  PR box ∉ Q̃                     TH-DET — violates the 2√2 CHSH bound.
  global record extendability    AX-DET — candidate principle (open conjecture).
"""

from __future__ import annotations

import itertools
import math


# ── A (2,2,2) no-signalling correlation ─────────────────────────────────────
#
# P(ab|xy) for a,b ∈ {0,1}, x,y ∈ {0,1}. Stored as a flat 4×4 matrix
# M[s][o], where the setting s = (x,y) indexes the row and the outcome
# o = (a,b) indexes the column:  s = 2x + y,  o = 2a + b.


class NoSignallingCorrelation:
    """A bipartite (2,2,2) correlation P(ab|xy).

    Represented by M[setting][outcome] with
        setting = 2x + y   (x = Alice setting, y = Bob setting)
        outcome = 2a + b   (a = Alice outcome, b = Bob outcome).
    """

    def __init__(self, M: list[list[float]]):
        if len(M) != 4 or any(len(row) != 4 for row in M):
            raise ValueError("M must be 4×4 (settings × outcomes)")
        self.M = [row[:] for row in M]

    # -- accessors ----------------------------------------------------------
    def p(self, x: int, y: int, a: int, b: int) -> float:
        return self.M[2 * x + y][2 * a + b]

    def marginal_alice(self, x: int, a: int) -> float:
        """P(a|x) — must be independent of y for no-signalling."""
        return sum(self.p(x, 0, a, b) for b in (0, 1))

    def marginal_bob(self, y: int, b: int) -> float:
        """P(b|y) — must be independent of x for no-signalling."""
        return sum(self.p(0, y, a, b) for a in (0, 1))

    def correlation(self, x: int, y: int) -> float:
        """E(x,y) = ⟨A_x B_y⟩ = Σ_{ab} (−1)^{a+b} P(ab|xy)."""
        return sum((1.0 if a == b else -1.0) * self.p(x, y, a, b)
                   for a in (0, 1) for b in (0, 1))

    def correlations(self) -> list[float]:
        """[E00, E01, E10, E11]."""
        return [self.correlation(x, y) for x in (0, 1) for y in (0, 1)]

    def chsh(self) -> float:
        """S = E00 + E01 + E10 − E11."""
        e00, e01, e10, e11 = self.correlations()
        return e00 + e01 + e10 - e11

    # -- validation ---------------------------------------------------------
    def is_normalized(self, tol: float = 1e-9) -> bool:
        return all(abs(sum(row) - 1.0) < tol for row in self.M)

    def is_no_signalling(self, tol: float = 1e-9) -> bool:
        # Alice: P(a|x) independent of y.
        alice_ok = all(
            abs(self.marginal_alice(x, a) - sum(self.p(x, 1, a, b) for b in (0, 1))) < tol
            for x in (0, 1) for a in (0, 1)
        )
        # Bob: P(b|y) independent of x.
        bob_ok = all(
            abs(self.marginal_bob(y, b) - sum(self.p(1, y, a, b) for a in (0, 1))) < tol
            for y in (0, 1) for b in (0, 1)
        )
        return alice_ok and bob_ok

    def validate(self, tol: float = 1e-9) -> dict:
        return {
            "normalized": self.is_normalized(tol),
            "no_signalling": self.is_no_signalling(tol),
            "valid": self.is_normalized(tol) and self.is_no_signalling(tol),
        }

    # -- correlation-class membership ---------------------------------------
    def is_classical(self, tol: float = 1e-9) -> bool:
        """Local (LHV) membership = all 8 CHSH facets (Fine's theorem).

        The local polytope for (2,2,2) is exactly the intersection of the
        8 CHSH inequalities  Σ_k c_k E_k ≤ 2  for c ∈ {±1}⁴ with Πc = −1.
        """
        return all(
            sum(c[k] * self.correlations()[k] for k in range(4)) <= 2.0 + tol
            for c in _chsh_facet_vectors()
        )


# ── The 8 CHSH facet vectors ────────────────────────────────────────────────


def _chsh_facet_vectors() -> list[tuple[int, int, int, int]]:
    """The 8 coefficient vectors c ∈ {±1}⁴ with product −1 (odd # of −1)."""
    return [c for c in itertools.product((1, -1), repeat=4)
            if c[0] * c[1] * c[2] * c[3] == -1]


# ── Canonical correlation constructors ──────────────────────────────────────


def local_deterministic_correlation() -> NoSignallingCorrelation:
    """A local-deterministic vertex: all outcomes fixed to a=b=0.

    E(x,y) = +1 for all settings, so S = 1+1+1−1 = 2 (saturates local bound).
    """
    M = [[0.0] * 4 for _ in range(4)]
    for s in range(4):
        M[s][0] = 1.0  # outcome (0,0) with probability 1.
    return NoSignallingCorrelation(M)


def pr_box() -> NoSignallingCorrelation:
    """The Popescu–Rohrlich box: a⊕b = x·y, uniform marginals.

    E(x,y) = (−1)^{x·y}, so E00=E01=E10=+1, E11=−1, giving S = 4.
    """
    M = [[0.0] * 4 for _ in range(4)]
    for x in (0, 1):
        for y in (0, 1):
            for a in (0, 1):
                b = (a + x * y) % 2
                M[2 * x + y][2 * a + b] = 0.5
    return NoSignallingCorrelation(M)


def bell_state_correlation() -> NoSignallingCorrelation:
    """The CHSH-optimal |Φ⁺⟩ correlation E(x,y) = cos(2(θ_x − φ_y)).

    Settings θ = (0, −π/4), φ = (−π/8, π/8), tuned to saturate the specific
    CHSH functional S = E00 + E01 + E10 − E11 at its Tsirelson bound 2√2.
    """
    angles_a = (0.0, -math.pi / 4)
    angles_b = (-math.pi / 8, math.pi / 8)
    M = [[0.0] * 4 for _ in range(4)]
    for x in (0, 1):
        for y in (0, 1):
            e = math.cos(2 * (angles_a[x] - angles_b[y]))
            for a in (0, 1):
                for b in (0, 1):
                    M[2 * x + y][2 * a + b] = (1 + (1 if a == b else -1) * e) / 4.0
    return NoSignallingCorrelation(M)


# ── Bounds with proofs ──────────────────────────────────────────────────────


def chsh_local_bound() -> dict:
    """The classical (LHV) CHSH bound |S| ≤ 2, with its proof.

    Every local correlation is a convex combination of 16 deterministic
    strategies, so S is a convex combination of deterministic S-values. Each
    deterministic strategy assigns A_x,B_y ∈ {±1}, giving S = A₀B₀ + A₀B₁ +
    A₁B₀ − A₁B₁ = A₀(B₀+B₁) + A₁(B₀−B₁) ∈ {±2}. Hence |S| ≤ 2.
    """
    deterministic_values = set()
    for A0 in (1, -1):
        for A1 in (1, -1):
            for B0 in (1, -1):
                for B1 in (1, -1):
                    s = A0 * B0 + A0 * B1 + A1 * B0 - A1 * B1
                    deterministic_values.add(s)
    return {
        "bound": 2.0,
        "deterministic_S_values": sorted(deterministic_values),
        "proof": (
            "S = A₀(B₀+B₁) + A₁(B₀−B₁). For any deterministic ±1 assignment "
            "this is ±2; local correlations are convex mixtures of these."
        ),
        "saturated_by": "local_deterministic_correlation (S = 2)",
    }


def chsh_no_signalling_bound() -> dict:
    """The no-signalling CHSH bound |S| ≤ 4, saturated by the PR box."""
    return {
        "bound": 4.0,
        "proof": (
            "S = E00 + E01 + E10 − E11 ≤ |E00|+|E01|+|E10|+|E11| ≤ 4, "
            "since each |E(x,y)| ≤ 1. Tight: the PR box has S = 4."
        ),
        "saturated_by": "pr_box (S = 4)",
    }


def chsh_tsirelson_bound() -> dict:
    """The quantum/almost-quantum CHSH bound |S| ≤ 2√2 via SOS certificate.

    For ±1 observables A_x, B_y with A_x² = B_y² = I and [A_x, B_y] = 0, the
    CHSH operator B = A₀B₀ + A₀B₁ + A₁B₀ − A₁B₁ satisfies

        B² = 4I − [A₀,A₁][B₀,B₁],

    so ‖B‖² ≤ 4 + ‖[A₀,A₁]‖‖[B₀,B₁]‖ ≤ 4 + 2·2 = 8, hence ‖B‖ ≤ 2√2. The
    only algebraic facts used are A_x²=B_y²=I and cross-party commutativity,
    which also hold in the almost-quantum (NPA level-1) set — so this bound
    is shared by Q and Q̃. CHSH therefore cannot separate Q from Q̃.
    """
    return {
        "bound": 2 * math.sqrt(2),
        "identity": "B² = 4I − [A₀,A₁][B₀,B₁]",
        "proof": (
            "‖B‖² = ‖B²‖ ≤ 4 + ‖[A₀,A₁]‖‖[B₀,B₁]‖ ≤ 4 + 2·2 = 8 ⟹ ‖B‖ ≤ 2√2. "
            "Uses only A_x²=B_y²=I and [A_x,B_y]=0 (valid in Q and Q̃)."
        ),
        "saturated_by": "bell_state_correlation (S = 2√2)",
        "shared_by_quantum_and_almost_quantum": True,
    }


def verify_tsirelson_identity() -> dict:
    """Numerically verify the SOS certificate B² = 4I − [A₀,A₁][B₀,B₁].

    Builds the CHSH operator B = A₀B₀ + A₀B₁ + A₁B₀ − A₁B₁ from the explicit
    Bell-state observables, checks the operator identity, and confirms the
    spectral norm ‖B‖ = 2√2 — the concrete Tsirelson bound.
    """
    obs, _ = _bell_observables()
    A0, A1 = obs["A0"], obs["A1"]
    B0, B1 = obs["B0"], obs["B1"]

    def add(*Ms):
        n = len(Ms[0])
        return [[sum(M[i][j] for M in Ms) for j in range(n)] for i in range(n)]

    def scale(s, M):
        return [[s * M[i][j] for j in range(len(M))] for i in range(len(M))]

    B_op = add(_matmul(A0, B0), _matmul(A0, B1), _matmul(A1, B0),
               scale(-1.0, _matmul(A1, B1)))
    Bsq = _matmul(B_op, B_op)
    comm_A = add(_matmul(A0, A1), scale(-1.0, _matmul(A1, A0)))  # [A0,A1]
    comm_B = add(_matmul(B0, B1), scale(-1.0, _matmul(B1, B0)))  # [B0,B1]
    rhs = add(scale(4.0, _identity(4)), scale(-1.0, _matmul(comm_A, comm_B)))

    n = 4
    max_err = max(abs(Bsq[i][j] - rhs[i][j]) for i in range(n) for j in range(n))

    # B is real symmetric here (all σ_θ are real symmetric), so the spectral
    # norm is the max |eigenvalue|.
    B_real = [[B_op[i][j].real for j in range(n)] for i in range(n)]
    norm_B = max(abs(e) for e in _jacobi_eigh_real(B_real))

    return {
        "identity_error": max_err,
        "identity_holds": max_err < 1e-8,
        "operator_norm_B": norm_B,
        "matches_tsirelson": abs(norm_B - 2 * math.sqrt(2)) < 1e-8,
    }


# ── Small linear-algebra helpers (pure stdlib) ──────────────────────────────


def _identity(n: int) -> list[list[complex]]:
    return [[(1.0 if i == j else 0j) for j in range(n)] for i in range(n)]


def _adjoint(A: list[list[complex]]) -> list[list[complex]]:
    n = len(A)
    m = len(A[0])
    return [[A[j][i].conjugate() for j in range(n)] for i in range(m)]


def _matmul(A: list[list[complex]], B: list[list[complex]]) -> list[list[complex]]:
    n = len(A)
    m = len(B[0])
    k = len(B)
    C = [[0j] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            C[i][j] = sum(A[i][r] * B[r][j] for r in range(k))
    return C


def _tensor(A: list[list[complex]], B: list[list[complex]]) -> list[list[complex]]:
    na, ma = len(A), len(A[0])
    nb, mb = len(B), len(B[0])
    C = [[0j] * (ma * mb) for _ in range(na * nb)]
    for i in range(na):
        for j in range(ma):
            for p in range(nb):
                for q in range(mb):
                    C[i * nb + p][j * mb + q] = A[i][j] * B[p][q]
    return C


def _expectation(psi: list[complex], M: list[list[complex]]) -> float:
    n = len(psi)
    out = 0j
    for i in range(n):
        acc = 0j
        for j in range(n):
            acc += M[i][j] * psi[j]
        out += psi[i].conjugate() * acc
    return out.real


def _jacobi_eigh_real(A: list[list[float]], tol: float = 1e-11,
                      max_iter: int = 2000) -> list[float]:
    """Eigenvalues of a real symmetric matrix (descending), via cyclic Jacobi."""
    n = len(A)
    a = [row[:] for row in A]
    for _ in range(max_iter):
        p, q, mx = 0, 1, 0.0
        for i in range(n):
            for j in range(i + 1, n):
                if abs(a[i][j]) > mx:
                    mx, p, q = abs(a[i][j]), i, j
        if mx < tol:
            break
        app, aqq, apq = a[p][p], a[q][q], a[p][q]
        theta = 0.5 * math.atan2(2.0 * apq, aqq - app)
        c, s = math.cos(theta), math.sin(theta)
        for k in range(n):
            if k == p or k == q:
                continue
            akp, akq = a[k][p], a[k][q]
            a[k][p] = a[p][k] = c * akp - s * akq
            a[k][q] = a[q][k] = s * akp + c * akq
        a[p][p] = c * c * app - 2.0 * s * c * apq + s * s * aqq
        a[q][q] = s * s * app + 2.0 * s * c * apq + c * c * aqq
        a[p][q] = a[q][p] = 0.0
    return sorted((a[i][i] for i in range(n)), reverse=True)


def _is_psd(M: list[list[float]], tol: float = 1e-8) -> bool:
    return all(e >= -tol for e in _jacobi_eigh_real(M))


# ── Bell-state quantum realization (used to build explicit NPA certificates) ─


_I2 = [[1, 0], [0, 1]]
_X = [[0, 1], [1, 0]]
_Z = [[1, 0], [0, -1]]


def _sigma(theta: float) -> list[list[complex]]:
    """σ_θ = cos(2θ)σ_z + sin(2θ)σ_x  (a ±1, self-adjoint observable)."""
    c = math.cos(2 * theta)
    s = math.sin(2 * theta)
    return [[c + 0j, s + 0j], [s + 0j, -c + 0j]]


def _bell_observables() -> tuple[dict, list[complex]]:
    """CHSH-optimal observables on |Φ⁺⟩ and the state vector.

    A_x = σ(θ_x) ⊗ I, B_y = I ⊗ σ(φ_y) with θ=(0,−π/4), φ=(−π/8,π/8).
    Returns (word -> 4×4 matrix) for the singles and joints, plus |Φ⁺⟩.
    """
    th_a = (0.0, -math.pi / 4)
    th_b = (-math.pi / 8, math.pi / 8)
    obs = {"": _identity(4)}
    obs["A0"] = _tensor(_sigma(th_a[0]), _I2)
    obs["A1"] = _tensor(_sigma(th_a[1]), _I2)
    obs["B0"] = _tensor(_I2, _sigma(th_b[0]))
    obs["B1"] = _tensor(_I2, _sigma(th_b[1]))
    obs["A0B0"] = _tensor(_sigma(th_a[0]), _sigma(th_b[0]))
    obs["A0B1"] = _tensor(_sigma(th_a[0]), _sigma(th_b[1]))
    obs["A1B0"] = _tensor(_sigma(th_a[1]), _sigma(th_b[0]))
    obs["A1B1"] = _tensor(_sigma(th_a[1]), _sigma(th_b[1]))
    # |Φ⁺⟩ = (|00⟩ + |11⟩)/√2.
    inv2 = 1.0 / math.sqrt(2.0)
    psi = [inv2, 0.0, 0.0, inv2]
    return obs, psi


def _level1_words() -> list[str]:
    return ["", "A0", "A1", "B0", "B1", "A0B0", "A0B1", "A1B0", "A1B1"]


def _level2_words() -> list[str]:
    # Length ≤ 2, reduced by A_x²=B_y²=I and [A_x,B_y]=0.
    return ["", "A0", "A1", "B0", "B1",
            "A0A1", "A1A0", "B0B1", "B1B0",
            "A0B0", "A0B1", "A1B0", "A1B1"]


def _word_matrix(word: str, obs: dict) -> list[list[complex]]:
    """Expand a level-≤2 word into its 4×4 operator (via the map `obs`)."""
    if word == "":
        return obs[""]
    # Products of known building blocks (all self-adjoint ±1).
    if word in obs:
        return obs[word]
    if word == "A0A1":
        return _matmul(obs["A0"], obs["A1"])
    if word == "A1A0":
        return _matmul(obs["A1"], obs["A0"])
    if word == "B0B1":
        return _matmul(obs["B0"], obs["B1"])
    if word == "B1B0":
        return _matmul(obs["B1"], obs["B0"])
    raise ValueError(f"unknown word {word!r}")


def _moment_matrix(words: list[str], obs: dict, psi: list[complex]) -> list[list[float]]:
    """Γ[u,v] = ⟨ψ| u† v |ψ⟩ for words u,v.

    Using the adjoint u† is essential for non-self-adjoint words (e.g. A₀A₁):
    Γ is then a Gram matrix of the vectors {u|ψ⟩} and is therefore PSD.
    """
    n = len(words)
    W = [_word_matrix(w, obs) for w in words]
    G = [[0.0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            G[i][j] = _expectation(psi, _matmul(_adjoint(W[i]), W[j]))
    return G


# ── Almost-quantum (NPA level-1) membership by explicit certificate ─────────


def _npa_level1_constraints(G: list[list[float]], corr: NoSignallingCorrelation,
                            tol: float = 1e-8) -> dict:
    """Verify a 9×9 Γ obeys the NPA level-1 linear constraints and recovers
    the correlation's marginals/correlations."""
    words = _level1_words()
    idx = {w: i for i, w in enumerate(words)}
    ok = {"G00": abs(G[idx[""]][idx[""]] - 1.0) < tol}
    ok["A0_sq"] = abs(G[idx["A0"]][idx["A0"]] - 1.0) < tol
    ok["A1_sq"] = abs(G[idx["A1"]][idx["A1"]] - 1.0) < tol
    ok["B0_sq"] = abs(G[idx["B0"]][idx["B0"]] - 1.0) < tol
    ok["B1_sq"] = abs(G[idx["B1"]][idx["B1"]] - 1.0) < tol
    # ⟨A_x B_y⟩ recovered from Γ[∅, A_xB_y] and Γ[A_x, B_y].
    for x in (0, 1):
        for y in (0, 1):
            w = f"A{x}B{y}"
            e = corr.correlation(x, y)
            ok[f"E{x}{y}_empty"] = abs(G[0][idx[w]] - e) < tol
            ok[f"E{x}{y}_cross"] = abs(G[idx[f"A{x}"]][idx[f"B{y}"]] - e) < tol
    ok["all_constraints"] = all(ok.values())
    return ok


def bell_state_npa_level1() -> dict:
    """Explicit NPA level-1 certificate for the Bell-state correlation.

    Builds the 9×9 moment matrix Γ from the quantum realization and verifies
    it is PSD and satisfies the level-1 constraints. This PROVES Bell ∈ Q̃.
    """
    obs, psi = _bell_observables()
    words = _level1_words()
    G = _moment_matrix(words, obs, psi)
    corr = bell_state_correlation()
    return {
        "psd": _is_psd(G),
        "min_eigenvalue": min(_jacobi_eigh_real(G)),
        "constraints": _npa_level1_constraints(G, corr),
        "chsh": corr.chsh(),
    }


def pr_box_not_almost_quantum() -> dict:
    """PR box is not almost-quantum: S = 4 > 2√2 = the Q̃ CHSH bound."""
    pb = pr_box()
    return {
        "chsh": pb.chsh(),
        "almost_quantum_bound": 2 * math.sqrt(2),
        "violates": pb.chsh() > 2 * math.sqrt(2) + 1e-9,
        "conclusion": "PR box ∉ Q̃ (and a fortiori ∉ Q); NS ⊋ Q̃.",
    }


# ── Global record extendability (DET candidate principle, operational form) ──


def global_record_extendability() -> dict:
    """Test whether the Bell-state level-1 Γ extends to a PSD level-2 Γ².

    "Global record extendability" (𝔇_n = Marginal(𝔇_{n+1})) is made concrete
    as: the level-1 moment matrix must be the principal submatrix of a PSD
    level-2 moment matrix (NPA level 2). The Bell state passes (it is quantum,
    so it extends to every level); the PR box already fails level 1.
    """
    obs, psi = _bell_observables()
    w1 = _level1_words()
    w2 = _level2_words()
    G1 = _moment_matrix(w1, obs, psi)
    G2 = _moment_matrix(w2, obs, psi)
    # Level-1 words sit at level-2 indices 0..4 and 9..12.
    l2_index = {w: i for i, w in enumerate(w2)}
    principal_ok = all(
        abs(G1[i][j] - G2[l2_index[w1[i]]][l2_index[w1[j]]]) < 1e-9
        for i in range(len(w1)) for j in range(len(w1))
    )
    return {
        "level1_psd": _is_psd(G1),
        "level2_psd": _is_psd(G2),
        "level1_is_principal_submatrix": principal_ok,
        "level2_min_eigenvalue": min(_jacobi_eigh_real(G2)),
        "extends": _is_psd(G2) and principal_ok,
        "note": (
            "Bell state extends (quantum ⇒ all NPA levels). PR box fails at "
            "level 1 (S=4>2√2). Whether extendability forces Q̃ → Q is the "
            "open DET conjecture."
        ),
    }


# ── Derivation certificate ──────────────────────────────────────────────────


def derivation_certificate() -> dict:
    return {
        "theorem": "T6 — Correlation-Class Theorem",
        "deliverables": {
            "no-signalling polytope": "MATH — standard linear constraints",
            "local polytope = 8 CHSH facets": "MATH — Fine (1982), CHSH (1969), credited",
            "Tsirelson bound 2√2 (SOS certificate)": "MATH — Cirel'son (1980), credited",
            "almost-quantum = NPA level 1": "MATH — Navascués–Pironio–Acín (2008), Navascués et al. (2015), credited",
            "Q ⊆ Q̃ (quantum induces a level-1 Γ)": "TH-DET",
            "PR box ∉ Q̃": "TH-DET — violates the 2√2 bound",
            "global record extendability": "AX-DET — candidate principle (open conjecture)",
        },
        "not_derived_here": [
            "the strict inclusion Q ⊊ Q̃ — cited (Navascués et al. 2015), not re-derived; no explicit Q̃∖Q witness",
            "a general SDP solver for arbitrary Q̃ membership (pure-stdlib convention)",
            "the 'global record extendability ⇒ Q' collapse — stated as a conjecture",
            "why-ℂ (complex field selection) — still open, feeds T6's full resolution",
        ],
        "status": (
            "Characterized classical / almost-quantum / no-signalling and their "
            "CHSH values 2 / 2√2 / 4. The quantum set sits inside almost-quantum; "
            "CHSH cannot separate them. T6 lands on ALMOST-QUANTUM unless global "
            "record extendability is proven to collapse it."
        ),
    }


# ── End-to-end T6 ───────────────────────────────────────────────────────────


def run_t6() -> dict:
    """The full correlation-class picture: nested sets and CHSH values."""
    local = local_deterministic_correlation()
    bell = bell_state_correlation()
    pr = pr_box()

    local_bound = chsh_local_bound()
    tsirelson = chsh_tsirelson_bound()
    ns_bound = chsh_no_signalling_bound()

    npa1 = bell_state_npa_level1()
    pr_not_aq = pr_box_not_almost_quantum()
    extend = global_record_extendability()

    return {
        "chsh_values": {
            "local (deterministic)": local.chsh(),
            "Bell state": bell.chsh(),
            "PR box": pr.chsh(),
        },
        "bounds": {
            "local": local_bound["bound"],
            "quantum/almost-quantum": tsirelson["bound"],
            "no_signalling": ns_bound["bound"],
        },
        "membership": {
            "Bell state is_classical": bell.is_classical(),
            "Bell state is_no_signalling": bell.validate(),
            "PR box is_classical": pr.is_classical(),
            "PR box is_no_signalling": pr.validate(),
            "Bell ∈ Q̃ (level-1 PSD + constraints)": npa1,
            "PR ∉ Q̃ (S=4>2√2)": pr_not_aq,
        },
        "global_record_extendability": extend,
        "certificate": derivation_certificate(),
        "interpretation": (
            "local S=2 < Bell S=2√2 < PR S=4. Bell is in almost-quantum "
            "(level-1 PSD certificate) and extends to level 2; PR box is "
            "no-signalling but not almost-quantum. Quantum ⊆ almost-quantum, "
            "and CHSH cannot separate them (both bound at 2√2). The strict "
            "Q ⊊ Q̃ gap is the open DET question, attacked via global record "
            "extendability."
        ),
    }
