"""DET — U(1) emergence (why one phase Ω, why reversible dynamics).

The open residue of `why_complex.py`: ℂ is forced by (Ω ≠ 0, empirically) +
(reversibility ⇒ U(m)), but WHY the record carries exactly ONE phase Ω and WHY
the dynamics is reversible were left as the speculative §3.4 targets. This
module addresses both with DET-native shape arguments.

  1. One arrow ⟹ one phase.  The decoherence functional 𝔇 = G + iΩ is
     Hermitian, so its imaginary part Ω is a SINGLE antisymmetric form.  A
     quaternionic (ℍ) structure needs THREE independent antisymmetric forms
     (i, j, k) — three arrows of time.  The record carries ONE causal order ≺,
     hence one arrow, hence one Ω ⟹ ℂ (not ℍ).

  2. Irreversible record, reversible possibility.  Reversibility is a property
     of the POSSIBILITY STRUCTURE, not the record.  The record grows
     irreversibly (the arrow of time); the possibility structure Ω it generates
     is open support, navigated without bias — and unbiased navigation of an
     open support is reversible (unitary).  Irreversibility (record) and
     reversibility (possibility) are complementary, not contradictory.

Honest boundary: both are SHAPE ARGUMENTS (like the ℍ argument in
why_complex.py), not derivations from primitives.  They close the "why one Ω /
why reversible" residue *conceptually*, leaving the full emergence (continuous
U(1) from discrete ±1 statistics) as the still-open research program.
"""

from __future__ import annotations


def one_arrow_implies_one_phase() -> dict:
    """A single causal order implies a single phase Ω (hence ℂ, not ℍ)."""

    # Concrete: a Hermitian 𝔇 decomposes into exactly one antisymmetric part.
    D = [[0.5, 0.2 + 0.1j], [0.2 - 0.1j, 0.5]]
    n = len(D)
    G = [[D[i][j].real for j in range(n)] for i in range(n)]
    Om = [[D[i][j].imag for j in range(n)] for i in range(n)]
    antisymmetric = all(
        abs(Om[i][j] + Om[j][i]) < 1e-12 for i in range(n) for j in range(n)
    )
    symmetric = all(
        abs(G[i][j] - G[j][i]) < 1e-12 for i in range(n) for j in range(n)
    )
    return {
        "hermitian_decomposition": "𝔇 = G + iΩ (G symmetric, Ω antisymmetric)",
        "handwritten_2x2_is_hermitian": antisymmetric and symmetric,
        "one_arrow_gives_one_phase": (
            "the record carries one causal order ≺ — one arrow of time — so one "
            "antisymmetric form Ω, hence one imaginary unit: ℂ. ℍ would need "
            "three independent Ω (i, j, k), i.e. three arrows."
        ),
        "computed_vs_asserted": (
            "the numeric check only verifies the hand-written 2×2 matrix is "
            "Hermitian (one antisymmetric imaginary part); the 'one arrow forbids "
            "three Ω' claim is a shape ARGUMENT, not computed here."
        ),
        "conclusion": "one arrow ⟹ one Ω ⟹ ℂ (not ℍ).",
    }


def irreversible_record_reversible_possibility() -> dict:
    """Why reversible dynamics: reversibility is about possibility, not record."""

    return {
        "record_is_irreversible": (
            "the record R grows asymmetrically through commit events (the arrow "
            "of time) — this is why there is ONE Ω."
        ),
        "possibility_is_open": (
            "the possibility structure Ω generated by L is open support — a "
            "constraint, not a biased selector of outcomes."
        ),
        "unbiased_navigation_is_reversible": (
            "navigating an open support without bias is reversible (unitary): "
            "the law map L is a constraint structure, so its dynamics preserves "
            "the phase structure Ω. Reversibility = unbiased navigation."
        ),
        "complementarity": (
            "irreversible record + reversible possibility are complementary, not "
            "contradictory: the record is the committed trace (irreversible), the "
            "possibility structure is the uncommitted future (navigated reversibly)."
        ),
    }


def u1_emergence_resolution() -> dict:
    """The full account: one arrow ⟹ one Ω, and reversibility as unbiased navigation."""

    return {
        "residue_addressed": "why one Ω, and why reversible (why_complex.py §3.4)",
        "one_phase": one_arrow_implies_one_phase(),
        "reversibility": irreversible_record_reversible_possibility(),
        "provenance": {
            "𝔇 = G + iΩ, single antisymmetric part": "MATH — Hermiticity",
            "one causal order ⟹ one Ω": "TH-DET — shape argument",
            "open support navigated without bias is reversible": "TH-DET — reading",
            "ℍ needs three Ω": "MATH — quaternion algebra (why_complex.py)",
        },
        "honest_boundary": (
            "shape arguments, not derivations. The full U(1) emergence (continuous "
            "complex phase from discrete ±1 statistics) remains the open research "
            "program (RED_TEAM_RESPONSE.md). These arguments close the conceptual "
            "'why one Ω / why reversible' residue, not the constructive derivation."
        ),
    }
