"""Root issues a consumer interface for a previously accepted actual qualification."""
from pathlib import Path
import hashlib, importlib.util, shlex
hp=Path('/Volumes/AI_DATA/development/det-review-evidence/ri122-root-execution-review-6whn_vky/metadata.py');b=hp.read_bytes()
assert len(b)==3144 and hashlib.sha256(b).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',hp);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=Path(__file__).resolve().parent
H=m.B/'ri170-measurement-current-e-preflight-gikj2giy';R=m.load(H/'REFERENCE_BINDINGS.json')['references']
check=m.load(m.D/'RI170_ROOT_METADATA_CHECK.json');assert check['status']=='PASS_WITH_DOCUMENTATION_COUNT_CORRECTION' and check['unique_paths']==614
for row in check['identities']:m.verify(row['path'],row)
review=m.save('RI170_ROOT_ADJUDICATION.json',dict(schema='ri170-root-source-preflight-review-v1',status='ACCEPT_SOURCE_PROPOSAL_WITH_EXPLICIT_FIELD_COUNT_CORRECTION',source=m.ref(H/'SOURCE_ONLY_HANDOFF.json'),manual_review=m.ref(m.D/'RI170_ROOT_SOURCE_REVIEW.md'),independent_metadata=m.ref(m.D/'RI170_ROOT_METADATA_CHECK.json'),replay=m.ref(m.D/'ri170-metadata-replay/METADATA_CHECK.json'),correction='Adapter closed field count is12, not prose13; listed names and code agree. Immutable author text retained.',actual_inert_qualification=R['actual_inert106_root_decision'],subject_execution=False,current_runtime_observation=False,copy_capture_or_profile_admission=False,scientific_credit=False,next_action='Issue the precise consumer qualification from the accepted genuine106-control outcome; then fresh root copy-only preflight/admission before unchanged exact48 copy. Independently accept the copy before separate current-E capture.'))
a=m.load(R['actual_inert106_root_decision']['path']);summary=m.load(a['actual_summary']['path']);initial=m.load(a['genuine_initial']['path']);terminal=m.load(a['genuine_terminal']['path']);monitor=m.load(summary['monitor']['path']);result=m.load(summary['result']['path']);inventory=m.load(R['inert_inventory']['path'])
assert a['status']=='ACCEPT_ONE_GENUINE_INERT_METADATA_QUALIFICATION' and result['order']==inventory['combined_order'] and result['counts']==dict(total=106,passed=106,failed=0)
assert monitor['passed'] is True and monitor['child_exit_code']==0 and terminal['actual']['exit_code']==0
args=shlex.split(initial['dispatch']['exec_command']['cmd']);assert args[:2]==['/usr/bin/env','-i']
assert dict(x.split('=',1) for x in args[2:12])==monitor['environment'] and args[12]=='/usr/bin/perl'
outer=m.save('RI162_GENUINE_OUTER_CONSUMER_BINDING.json',dict(schema='ri170-root-accepted-inert-genuine-outer-binding-v1',status='BIND_PREVIOUSLY_ACCEPTED_ACTUAL_TOOL_COMPLETION',accepted_root_decision=R['actual_inert106_root_decision'],genuine_initial=a['genuine_initial'],genuine_terminal=a['genuine_terminal'],actual_tool_chain=dict(initial_chunk='f3f711',session_id=66856,terminal_chunk='9921e9',exit_code=0),command=initial['dispatch']['exec_command'],environment=monitor['environment'],monitored_child_command=monitor['command'],monitor=summary['monitor'],completion=summary['complete'],result=summary['result'],actual_summary=a['actual_summary'],independent_review=a['independent_review'],external_timeout_seconds=960,new_execution=False,scientific_execution=False,fixture_credentials_remain_non_genuine=True))
card=m.save('RI162_CONSUMER_QUALIFICATION.json',dict(schema='ri156-root-inert-controls-review-v1',status='ACCEPT_EXACT_INERT_ADAPTER_CONTROLS',source_manifest=R['source_manifest'],report=summary['result'],genuine_outer=outer,independent_review=a['independent_review'],controls=inventory['combined_order'],all_passed=True,scientific_execution=False))
q=m.load(card['path']);assert len(q)==9 and q['source_manifest']==a['source_manifest'] and q['controls']==result['order']
for k in ('source_manifest','report','genuine_outer','independent_review'):m.verify(q[k]['path'],q[k])
assert all(not Path(p).exists() for p in m.load(H/'PREFLIGHT_PROPOSAL.json')['paths_proposed_not_created'].values())
print(m.save('RI170_CONSUMER_INTERFACE_CHECK.json',dict(schema='ri170-root-issued-interface-check-v1',status='PASS',source_adjudication=review,qualification=card,genuine_outer=outer,exact_required_nine_fields=True,ordered_actual_controls=106,scientific_credit=False,actual_current_E_admission=False,proposed_roots_absent=True)))
