from pathlib import Path
import importlib.util,hashlib,json,sys,os
B=Path('/Volumes/AI_DATA/development/det-review-evidence');R=Path(Path('/private/tmp/ri230_root_path.txt').read_text());W=B/'ri229-reconciliation-preparation-t93t1607/worker_proposal';I=B/'ri229-independent-preparation-review-ajsf_qna';D=B/'ri226-directory-custody-recovery-yvfg_p1b'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=R
m.verify(I/'HANDOFF.json',dict(bytes=7768,sha256='d78cd1f9e9c14304504a69796c4df9267454c6543344ecee6f35f8ba90bb35df'));hand=m.load(I/'HANDOFF.json');assert sorted(p.name for p in I.iterdir())==hand['namespace']
for row in hand['files']:m.verify(row['path'],row)
with (R/'RI229_ROOT_REVIEW.md').open('xb') as f:f.write(Path('/private/tmp/ri230_preparation_review.md').read_bytes())
review=m.save('RI229_PREPARATION_SOURCE_ACCEPTANCE.json',dict(schema='ri229-root-preparation-source-decision-v1',status='ACCEPT_RI229_PREPARATION_SOURCE_ONLY',source_manifest=m.ref(W/'SOURCE_PINS.json'),recovery_source_review=m.ref(D/'ROOT_SOURCE_REVIEW.json'),packet=m.ref(W/'HANDOFF.json'),independent_review=m.ref(I/'HANDOFF.json'),root_manual_review=m.ref(R/'RI229_ROOT_REVIEW.md'),root_metadata=m.ref(R/'RI229_ROOT_SOURCE_METADATA.json'),independent_full_read='b9bbe4 exit0',root_actual_metadata='6efaae/session1066 ->5dfce3 exit0',independent_actual_metadata=['f85304 exit0,3999 predicates/997 opaque files, whole author report matched','b4f4c1 exit0,6005 predicates/1011 opaque files'],independent_checker_diagnostics_retained=['24b66b','430526','29da41'],scope='Exact preparation source only; an additional root one-preparation decision and actual host/interpreter/source authentication are required.',preparation_executed=False,reconciliation_admitted=False,mode_admission=False,qualification_credit=0,RET_paused=True))
manifest=m.ref(W/'SOURCE_PINS.json');writer=m.verify(W/'prepare_reconciliation.py',dict(bytes=27651,sha256='3fb022aa2f9ed0d5f79fde2f58b7ec8abf7a5ea66b88e3759d2272f9cb198e82'));host=m.ref(R/'GENUINE_PREPARATION_HOST_TOOL.json');v=m.load(host['path']);assert v['result']['exit_code']==0 and v['result']['chunk_id']=='ff059f'
interpreter=m.identity('/opt/homebrew/bin/python3');assert sys.flags.isolated==1 and sys.flags.dont_write_bytecode==1 and sys.flags.optimize==0
argv=['/opt/homebrew/bin/python3','-I','-B',writer['path'],'--preparation-manifest-bytes',str(manifest['bytes']),'--preparation-manifest-sha256',manifest['sha256'],'--preparation-review',review['path'],'--preparation-review-bytes',str(review['bytes']),'--preparation-review-sha256',review['sha256'],'--host-transcript',host['path'],'--host-transcript-bytes',str(host['bytes']),'--host-transcript-sha256',host['sha256']]
for name in ['tmp','monitor','RECONCILE_PREFLIGHT.json','ADMIT_RECONCILE.json','DISPATCH.json']:assert not os.path.lexists(D/name)
decision=m.save('ROOT_ONE_PREPARATION_DECISION.json',dict(schema='ri230-root-one-administrative-preparation-v1',status='AUTHORIZE_ONE_ADMINISTRATIVE_PREPARATION_ONLY',source_review=review,source_manifest=manifest,writer=writer,administrative_interpreter=interpreter,observed_flags=dict(isolated=1,dont_write_bytecode=1,optimize=0),interpreter_and_tool_origin='Existing genuine root administrative tool route; no new hermetic or OS-loader claim',host=host,command=argv,cwd=str(D),login=False,one_attempt=True,outputs='Nine exclusive administrative files and two empty control directories in D only, under exact reviewed source',on_failure='Preserve all partials and genuine return; no retry, overwrite or cleanup.',reconciliation_admitted=False,reconciliation_dispatched=False,E_write=False,mode_authority=False,scientific_execution=False,qualification_credit=0,RET_paused=True))
with (R/'preparation_decision.py').open('xb') as f:f.write(Path(__file__).read_bytes())
print(json.dumps(dict(source_review=review,decision=decision,command=argv)))
