from pathlib import Path
import hashlib,importlib.util,tempfile,os
hp=Path('/Volumes/AI_DATA/development/det-review-evidence/ri122-root-execution-review-6whn_vky/metadata.py');raw=hp.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',hp);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);R=m.B/'ri247-root-hook-branch-review-6fgw5qd9';m.D=R
q=m.B/'ri246-native-hook-literals-0_fkiagp';w=Path('/private/tmp/ri244-preparation-proposal-3udz0imk');ir=Path('/private/tmp/ri244-independent-source-review-n9x3lh9m')
def copy(p,name,expected=None):
 if expected:m.verify(p,expected)
 b=p.read_bytes();m.verify(p,m.pin(b))
 with (R/name).open('xb') as f:f.write(b);f.flush();os.fsync(f.fileno())
 assert (R/name).read_bytes()==b
 return m.ref(R/name)
native_review=copy(Path('/private/tmp/ri246-independent-review-ed850a.txt'),'RI246_INDEPENDENT_REVIEW.txt',dict(bytes=13914,sha256='a63b92a07098e4b14fe4a681a1cea72df4cf1d63c35084d31f619105c8d39d10'))
manual='''RI247 root manual adjudication of RI246, 1 October 2026 UTC.
Root independently acquired the six values under the explicit RI246 admission before reading the author proofs; original receipt 3dff90 and complete source state are retained in the preceding root preliminary report. The current original body was opaquely reauthenticated by a61c9d/dde298, with 98 identities, 91 sources and 15 inherited boundaries. Complete author manuscripts were read in49abc5, current metadata declarations in8c018b, actual final checker text in61a02f, and complete independent report in513577 andd540ef. No scientific parser or arithmetic engine ran.
The complete original indices57,58,59,61,60,62 bind role order x0,x1,y00,y01,y10,y11 to defaults1/8,1/8 and explicit429/1000,429/1000,181/200,181/200. The 0,2,1,3 role permutation and long-arm selected bit remain. The f probabilities are19/1760,7/1760; the g probabilities are1677/5000 (twice) and8869/11000 (twice); newborn1/2 remains separate. The common denominator1000 equals8*125,1000*1,200*5 and is below2^50. More directly, both y minima exceed1/4, so their cleared deductions exceed344 and392, each greater than205 before the positive x deduction. Thus both positive-part arguments are strictly negative, P0=P1=0. Positive c0,c1 and gamma give N0=N1=F=d=0. Inherited theta,K positivity makes d7 strictly negative. This is an exact actual branch decision for the prescribed finite law, conditional on the accepted component reconstruction and finite-law premises.
The accepted complete RI238 iff therefore reduces to normalized existence iff the original C_b=0. All thirteen equations and ten coordinates, u2=-1, global shared forms, all records/ideals/newborns and strict endpoints remain. Vanishing hook corrections do not imply a canonical allocation sign. There is no actual normalized witness or signed inconsistency yet. Full-vector audit, scientific qualification, improvement, optimality, amplitude, all-size geometry/gravity/QM and physical claims stay unresolved.
The author failures source-pin matches and diagnostics match are genuine exit1 outcomes. Actual commands show repairs to fieldwise pin comparison and key-order-independent administrative comparison. They did not alter scientific inputs or relax scope. Final author exit0 is genuine but its retrieved output remains API-truncated; the complete literal and both failures are untruncated. Root and nonauthor independent metadata checks corroborate current facts, not a claimed complete replay. The inherited423-object manifest remains by reference. Same-source sign and denominator arguments are two checks, not independent data.
'''
with (R/'RI246_ROOT_MANUAL_REVIEW.md').open('x') as f:f.write(manual)
na=m.save('RI246_ROOT_ADJUDICATION.json',dict(schema='ri247-native-six-hook-root-adjudication-v1',status='ACCEPT_ACTUAL_SIX_HOOK_WITNESS_AND_NONEXCEPTIONAL_BRANCH_ONLY',subject=m.ref(q/'HANDOFF.json'),independent_review=native_review,manual_review=m.ref(R/'RI246_ROOT_MANUAL_REVIEW.md'),metadata_check=m.ref(R/'RI246_ROOT_METADATA_CHECK.json'),genuine_author_tools=m.ref(R/'RI246_GENUINE_AUTHOR_TOOLS.json'),literal_admission=m.ref(m.B/'ri245-root-hook-review-ichvs643/RI246_SIX_HOOK_LITERAL_ADMISSION.json'),accepted='P0=P1=N0=N1=F=d=0; d != d7; normalized existence iff actual C_b=0',canonical_Cb_resolved=False,actual_normalized_witness=False,actual_signed_inconsistency=False,scientific_execution=False,qualification_credit=0,all_size_or_physical_claim=False))
Q=Path(tempfile.mkdtemp(prefix='ri248-native-canonical-companion-',dir=m.B))
assignment='''RI248: actual canonical companion-row/gap decision after RI246 acceptance.
Exclusive output reservation: %s
Accepted predecessor: %s
Use the fixed prescribed finite law and accepted RI246 zero-hook witness. The actual branch is d=0 != d7; the full normalized system now exists iff original C_b=0. Resolve a concrete sufficient bound kappa0-kappa1<=1/70 or M1-M0<=41/24640 (the stronger1/625 bound suffices), or identify precisely why the actual canonical optimum defeats that route.
Derive the COMPLETE marked companion P_tau row/slack and history-weighted objective comparison for each relevant sector, exploiting accepted N0=N1=0 only where logically warranted. Preserve all coupled P/Y and companion constraints, actual primary optimum and sequential lexicographic tie order. RI240 already gives kappa_i=0 OR a carrying P_tau row is tight OR T_i<=L_i; merely repeating that alternative, erasing canonical terms or using a kappa-only transfer is not progress. Determine whether those alternatives yield the actual bound or a sound obstruction. If indispensably missing coefficients prevent the decision, provide exact minimal component/selector/source binding and a justified acquisition design; do not acquire them.
Manual native proof/reduction only, with authenticated admitted analytic text and metadata. Preserve all13 equations/10 coordinates, u2=-1, global recovery, records/ideals/newborns, strict endpoints and all15 inherited boundaries. Retain423-source manifest by reference. RI246's six literal exception is closed: its accepted witness may be used analytically, but this assignment admits no new original body, coefficient, vector, graph/LP, automatic scientific arithmetic, subject import/compile/AST/execution, runtime/measurement/RET, Git/index or repository edit. Root owns admission and independent acceptance. Seal source references, proof/obstruction, actual administrative checks and diagnostics with exact final handoff. End at handoff; root will independently adjudicate and select a justified successor.
'''%(Q,na['path'])
with (R/'RI248_ASSIGNMENT.md').open('x') as f:f.write(assignment)
print(na);print(m.save('RI248_ASSIGNMENT.json',dict(schema='ri248-native-canonical-companion-assignment-v1',status='ASSIGNED_AFTER_PREDECESSOR_ADJUDICATION',thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(Q),predecessor=na,assignment=m.ref(R/'RI248_ASSIGNMENT.md'),new_literal_authority=False,scientific_execution=False)))
m.verify(ir/'HANDOFF.json',dict(bytes=3405,sha256='f967d8717bfe5d1fad60768bc1cd401713475eab5122d9cf29b1a21b9d4ee4c8'));ih=m.load(ir/'HANDOFF.json');assert sorted(p.name for p in ir.iterdir())==ih['namespace']
for row in ih['files']:m.verify(row['path'],row)
review=copy(ir/'REVIEW.md','RI244_INDEPENDENT_SOURCE_REVIEW.md',dict(bytes=13080,sha256='c4fc16071da4703006ad8bc5b51b38350d27500a542a8bbfa131172983cc517a'))
check=copy(Path('/private/tmp/ri247-ri244-source-check.json'),'RI244_ROOT_SOURCE_CHECK.json')
ma=m.save('RI244_SOURCE_ADJUDICATION.json',dict(schema='ri247-ri244-source-adjudication-v1',status='ACCEPT_EXACT_UNEXECUTED_PREPARATION_SOURCE_ONLY',subject=m.ref(w/'HANDOFF.json'),writer=m.ref(w/'prepare_unissued.py'),independent_handoff=m.ref(ir/'HANDOFF.json'),independent_review=review,root_source_check=check,root_complete_reads=['4226ce','cd537e','9d377a','09a36b','8f7c65'],root_metadata_receipt='47a235',root_opaque_identities=607,independent_receipt='24f048',independent_predicates=10654,independent_opaque_files=610,root_final_report_read='233c4e',output_custody_boundary=m.ref(ir/'OUTPUT_CUSTODY_BOUNDARY.json'),requires_final_literal_regular_files_and_full_states=True,preparation_executed=False,operational_authorization=False,scientific_qualification=False,administrative_metadata_helper_loaded=True,proposal_or_historical_preparation_helper_executed=False))
print(ma)
host=m.load('/private/tmp/ri247-genuine-preparation-host.json');assert host['result']['exit_code']==0 and host['result']['chunk_id']=='527491' and not host['result'].get('session_id')
hr=m.save('RI244_GENUINE_PREPARATION_HOST.json',host)
writer=m.verify(w/'prepare_unissued.py',dict(bytes=22091,sha256='02d5e3c3d617ea3c0299e313a63569d97121d6c16b57c3ce290544896ef1cfce'));admin=m.identity('/opt/homebrew/bin/python3')
print(m.save('RI244_ADMINISTRATIVE_STARTUP_BINDING.json',dict(writer=writer,ordinary_administrative_interpreter=admin,source_adjudication=ma,trust='Existing ordinary root administrative Python and standard library; no scientific supplier qualification claimed. Recheck before and after invocation.')))
print(m.save('RI244_PREPARATION_DECISION.json',dict(schema='ri244-root-unissued-preparation-decision-v1',status='AUTHORIZE_ONE_ADMINISTRATIVE_PREPARATION_ONLY',preparation_source={k:writer[k] for k in ('path','bytes','sha256')},proposal_handoff=m.ref(w/'HANDOFF.json'),output=str(m.B/'ri244-current-normal-premode-2kfsmiea'),host_transcript=hr,root_attests_fresh_genuine_host_tool_origin=True,operational_authorization=False)))
