"""Root source-only adjudication after complete nonauthor review; no cases run."""
import hashlib,importlib.util,tempfile
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=Path(__file__).parent
hp=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=hp.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',hp);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
R=B/'ri171-independent-supervisor-source-review-fw3b83xu';S=B/'ri171-supervisor-qualification-source-zksymhs1'
m.verify(R/'HANDOFF.json',dict(bytes=3595,sha256='7691441c118298449b0fbfb8c9bd0123d481e642e2640398420561be7d239ee5'))
h=m.load(R/'HANDOFF.json');assert sorted(p.name for p in R.iterdir())==h['namespace']==h['compact_publication_subset'] and len(h['payloads'])==7
published=[m.ref(R/'HANDOFF.json')]+h['payloads'];ids=[m.verify(r['path'],r) for r in published]
review=m.load(R/'ADMIN_CHECK.json');assert review['check_count']==3525 and review['observed_identity_count']==55 and review['case_count']==92 and review['actual_control_outcomes']==0
for r in review['observed_identities']:
 now=m.verify(r['path'],r);assert now['state']==r['fresh_state'];ids.append(now)
manifest=m.load(S/'CASE_MANIFEST.json');assert len(manifest['cases'])==92 and all(r['executed'] is False for r in manifest['cases'])
source=m.load(S/'HANDOFF.json');assert sorted(p.name for p in S.iterdir())==source['namespace'] and len(source['payloads'])==29
for r in ids:assert m.identity(r['path'])==r
print(m.save('RI171_REVIEW_AUTHENTICATION.json',dict(status='PASS_COMPLETE_SEALED_REVIEW_AND_UNCHANGED_SOURCE',published=published,identities=ids,source_namespace=30,review_namespace=8,input_identities=55,actual_cases=0,reviewer_check=dict(receipt='59ddad',exit_code=0,predicates=3525),reviewer_seal=dict(receipt='79ca16',exit_code=0),reviewer_final=dict(receipt='1f20b3',exit_code=0))))
v=m.load(R/'VERDICT.json');assert v['decision']=='REQUIRE_SOURCE_REPAIRS_BEFORE_QUALIFICATION_ADMISSION'
decision=m.save('RI171_ROOT_ADJUDICATION.json',dict(schema='ri171-root-source-decision-v1',status='REQUIRE_SOURCE_REPAIR_BEFORE_QUALIFICATION',subject=m.ref(S/'HANDOFF.json'),nonauthor_review=m.ref(R/'HANDOFF.json'),review_authentication=m.ref(D/'RI171_REVIEW_AUTHENTICATION.json'),findings=v['findings'],root_review='Root read all five complete new modules and independently traced the reported branches against unchanged RI169 source. Caller read selects ps first; transient oracle lacks role binding; late_observer is shadowed twice; ordinary failed receipts omit completed-return requirements; fallback/journal/observer/recovery obligations are incomplete; stderr drift grows an empty file. Root concurs with all five independently documented blockers.',root_source_reads=['04fc81','650053','d9502a','f8a894','ffd184','6049f4','5807b5'],root_review_reads=['f2f7f8','11d89b','696a75'],subject_supervisor_unchanged=True,defined_cases=92,executed_cases=0,qualification_accepted=False,scientific_execution=False,ret_paused=True))
print(decision)
reservation=tempfile.mkdtemp(prefix='ri176-supervisor-qualification-repair-',dir=B)
print(m.save('RI176_REPAIR_ASSIGNMENT.json',dict(schema='ri176-source-repair-assignment-v1',owner='/root/ri116_complete_caller_review',reservation=reservation,predecessor=decision,subject=m.ref(S/'HANDOFF.json'),independent_review=m.ref(R/'HANDOFF.json'),task='Repair RI171 qualification driver/oracle F01–F05 in this new exclusive source reservation. Keep the exact RI169 supervisor unchanged. Preserve the full92-case inventory and34 inherited recipes; add narrowly justified prospective oracle rejection cases if required, without executing them.',requirements=[f['required_repair'] for f in v['findings']],additional_constraints=['Make exact process-role and stream selection explicit in both fixture and independent saved oracle. Reconcile per-case injection and event order, full terminal outcome and complete applicable tail obligations.','Retain deliberate hard/receipt/deadline/nonreap incomplete semantics and actual root recovery responsibilities; signal sent never proves absence or reap.','Include source-only negative oracle plans or implementations for wrong-role transient, shadowed observer, candidate-only ordinary completion, omitted defining kill/sibling/reap/recovery evidence, and same-size drift versus size change. No fixture generation or target/checker execution now.','Preserve all315/310/312, observer.2+.2,8MiBstream64MiBjournal256KiBreceipt caps and current source/custody requirements. No lowered acceptance threshold, broader launcher redesign or new recovery budget.','All subject/vendor/helper imports, compile, AST, probe, run, scientific JSON/vector decoding, fixtures, actual runtime capture and operational cards are prohibited. Authenticated Homebrew Python-I-B or Node administrative identity/literal checks only; no system-Python shim.','No Git/index/repository writes or new agents. Preserve RI171/review/RI169 and every failed/intermediate historical record unchanged. Seal full source, dependency deltas, review-response map and actual administrative checks for fresh independent review. Root owns admission and publication; RET remains paused.'])))
