"""Root adjudication of the independently reviewed exact canonical formula."""
import importlib.util, tempfile
from pathlib import Path
s=importlib.util.spec_from_file_location('m','/Volumes/AI_DATA/development/det-review-evidence/ri122-root-execution-review-6whn_vky/metadata.py');m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=Path(__file__).resolve().parent
Q=m.B/'ri151-canonical-q-equalities-_546ie2h';R=m.B/'ri151-independent-face-review-uvQfBh5q'
m.verify(R/'HANDOFF.json',dict(bytes=8003,sha256='3910840dfd58f44a358f9c61d66c5f0a3cbe86accdfc1a62372f2c6556a3013f'))
h=m.load(R/'HANDOFF.json');v=m.load(R/'INDEPENDENT_FACE_REVIEW.json')
assert h['verdict']==v['status']=='ACCEPT_EXACT_CANONICAL_TARGET_FORMULA_WITH_FIXED_PREFIX_BUDGET_GAP' and h['required_repairs']==v['required_repairs']==[]
assert sorted(p.name for p in R.iterdir())==h['namespace'] and len(h['payloads'])==6
for r in h['payloads']:m.verify(r['path'],r)
assert h['subject_handoff']==m.ref(Q/'HANDOFF.json')
for r in m.load(Q/'HANDOFF.json')['payloads']:m.verify(r['path'],r)
for r in m.load(m.D/'ROOT_NATIVE_CHECK.json')['identities']:assert m.identity(r['path'])==r
a=m.load(R/'METADATA_CHECK.json');assert a['dependency_count']==150 and a['historical_reference_occurrences']==734 and a['current_reference_occurrences']==66 and a['final_stable_identity_rechecks']==160
decision=m.save('RI151_ROOT_ADJUDICATION.json',dict(schema='ri151-root-canonical-formula-adjudication-v1',status=v['status'],source_handoff=m.ref(Q/'HANDOFF.json'),independent_review=m.ref(R/'HANDOFF.json'),independent_narrative=m.ref(R/'INDEPENDENT_FACE_REVIEW.md'),root_manual_review=m.ref(m.D/'ROOT_MANUAL_REVIEW.json'),root_metadata_check=m.ref(m.D/'ROOT_NATIVE_CHECK.json'),accepted=h['accepted_manual_scope'],formula=v['manual_result'],independence=v['independence'],remaining=h['remaining'],preserved=h['preserved'],root_read='Complete three author manuscripts, root literal premise spans and root algebra in ROOT_MANUAL_REVIEW; complete independent narrative6d9289, verdict/finalcheck/diagnosticsdff36c, finalhandoff558afe. Final editorial scope narrows RI127 fresh reads to1-58 and60-205; mathematical text unchanged.',actual_checks=dict(root_closure='332f4e exit0',independent_closure='279d68 exit0',independent_final='8a9db4 exit0',independent_seal='d67b40 exit0'),scientific_body_decode=False,scientific_execution=False,physical_claim=False,ret_paused=True))
print(decision)
nextdir=Path(tempfile.mkdtemp(prefix='ri153-fixed-prefix-weighted-margin-',dir=m.B))
print(m.save('NATIVE_SUCCESSOR_RESERVATION.json',dict(schema='ri153-fixed-prefix-weighted-margin-assignment-v1',status='ASSIGNED_ANALYTIC_PROOF_ONLY_AFTER_RI151_ADJUDICATION',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(nextdir),predecessor=decision,question='Advance the actual fixed-prefix weighted comparison now that a_i=[41p_i-f_i/2-min(g_i0,g_i1)]_+/(41p_i*c_i) is proved. Derive structural inequalities or identities from the accepted through-four law that control its positive-part branches and the root-weighted difference sigma0*k0(x)-sigma1*k1(x). Target an explicit adequate uniform q/D3 lower bound on the SAME correlated actual-containing [0,Z], or a direct cleared endpoint inequality with a strictly stronger justified sufficient condition. If the fixed-prefix constraints cannot settle the margin, isolate a specific missing prefix relation and prove exactly how it enters the remaining inequality; do not merely restate the formula or give a freely chosen positive prefix/primary optimum as an actual counterexample. Keep the separate v/D3 floor, both RI147 joint endpoint budgets, Z/reference/full-complement correlations, actual rho membership, all other parent equations and H30 obligations explicit. Ordering sigma alone does not order kappa. Do not erase boundary/strict-restored distinctions.',permitted='Manual analytic proof and literal accepted source/premise reading; bounded administrative identity/reference checks. No scientific-body decode, actual numerical coefficient/probability/history/max/scale/H/z evaluation, symbolic/numerical engine, subject/helper import/compile/AST/probe/run, global graph enumeration, runtime/controller/card/admission, repository/index/Git or predecessor mutation.',expected='A substantive new fixed-prefix identity/inequality, quantitatively useful weighted-margin theorem or precise proved remaining prefix obstruction; full source-premise closure and sealed author packet for independent review.',preserved=h['preserved'],measurement='RI152 genuine65 guard run completed under unchanged bounds; complete independent actual review in progress.',ret_paused=True)))
