"""Longitudinal drift and change-point detection over the RET core.

The Gaussian RET core treats each record as generated by a fixed latent
parameter.  This fixture exercises the two extensions that close that gap:

1. ``evolve_ret_posterior`` adds a declared per-parameter random-walk process
   noise between separately committed actions, so stale parameter states grow
   more uncertain with time.
2. ``change_point_mixture`` + ``update_mixture_state`` form an online detector
   that adjudicates, for each new record, whether a change of the declared
   drift magnitude has occurred.

The truth is synthetic (a rate that shifts from 0 to 3 midway), so the run is a
matched-generator demonstration of the machinery, not evidence about any real
physical regime change.
"""

from __future__ import annotations

import json
import math

from det8.models.relational_tomography import (
    GaussianParameterState,
    GaussianPrior,
    RelationalAction,
    RelationalModel,
    change_point_mixture,
    change_probability,
    collapse_mixture,
    evolve_ret_posterior,
    initialize_ret_posterior,
    update_mixture_state,
)


def run_drift_change_point_fixture() -> dict:
    probe = RelationalAction("probe", "science", (0.0,), {"rate": (1.0,)})
    drift = {"rate": 3.0}
    change_prior = 0.1
    noise = 0.2

    # Online change-point detection across a sequence whose true rate shifts
    # from 0 to 3 midway.
    truth = [0.0] * 5 + [3.0] * 5
    state = GaussianParameterState(("rate",), (0.0,), ((1.0,),))
    trace = []
    for index, true_rate in enumerate(truth):
        updated = update_mixture_state(
            change_point_mixture(state, drift, change_prior),
            probe,
            (true_rate,),
            noise,
        )
        if len(updated.components) == 1:
            # The stable component was pruned: the observation is decisively
            # inconsistent with "no change".  The wider "changed" component is
            # never pruned, so a single surviving component means a detected
            # change with posterior ~1.
            probability = 1.0
        else:
            probability = change_probability(updated)
        state = collapse_mixture(updated)
        trace.append(
            {
                "record": index,
                "true_rate": true_rate,
                "change_probability": probability,
                "rate_mean": state.mean[0],
                "rate_standard_deviation": math.sqrt(
                    max(state.covariance[0][0], 0.0)
                ),
            }
        )
    change_peak = max(range(len(trace)), key=lambda i: trace[i]["change_probability"])

    # Longitudinal evolution: a drifting model's predictive variance grows
    # between separately committed measurements.
    drifting = RelationalModel(
        "drifting",
        "family",
        {"rate": GaussianPrior(0.0, 1.0)},
        drift_standard_deviations={"rate": 0.5},
    )
    current = initialize_ret_posterior([drifting])
    evolution_variances = [current.parameters["drifting"].covariance[0][0]]
    for _ in range(3):
        current = evolve_ret_posterior(current, 1)
        evolution_variances.append(current.parameters["drifting"].covariance[0][0])

    return {
        "fixture": "longitudinal drift and change-point detection",
        "drift_standard_deviation": drift["rate"],
        "change_prior": change_prior,
        "observation_noise": noise,
        "change_point_trace": trace,
        "change_peak_record": change_peak,
        "change_detected_at_shift": change_peak == 5,
        "evolution_variances": evolution_variances,
        "warning": (
            "The change-point detector distinguishes a declared drift magnitude "
            "from a stable parameter; it does not establish when a real physical "
            "regime changed absent such a declaration."
        ),
    }


if __name__ == "__main__":
    print(json.dumps(run_drift_change_point_fixture(), indent=2))
