"""Higher-height Riemann run with independent numerical count gates.

The critical-line roots are generated by sign changes of the double-precision
Riemann-Siegel Z function.  They are admitted to the extension only when:

* a continuous-argument Riemann--von Mangoldt count agrees at two resolutions;
* selected roots retain sign-changing brackets under Decimal reevaluation; and
* high-precision zeta residuals remain below the declared numerical tolerance.

This is a strong numerical cross-check, not proof-grade interval arithmetic.
"""

from __future__ import annotations

import cmath
import hashlib
import json
import math
from dataclasses import dataclass
from decimal import Decimal, getcontext, localcontext

from det8.models.examples.riemann_zero_search import (
    critical_line_zeros,
    riemann_question,
    riemann_siegel_theta,
    riemann_spacing_models,
    riemann_window_action,
    riemann_window_covariance,
    riemann_zeta,
    zero_window_statistics,
)
from det8.models.relational_scheduler import (
    CostWeights,
    SchedulerObjective,
    rank_actions,
)
from det8.models.relational_tomography import (
    initialize_ret_posterior,
    parameter_summary,
    update_ret_posterior,
)


RIEMANN_VALIDATION_WARNING = (
    "Agreement between critical-line sign changes, Decimal reevaluation, and a "
    "numerical Riemann-von Mangoldt count is bounded numerical certification, "
    "not a proof of RH and not proof-grade interval arithmetic."
)

_DECIMAL_PI = Decimal(
    "3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679"
)
_BERNOULLI_FRACTIONS = (
    (1, 6),
    (-1, 30),
    (1, 42),
    (-1, 30),
    (5, 66),
    (-691, 2730),
    (7, 6),
    (-3617, 510),
)


@dataclass(frozen=True)
class HighPrecisionComplex:
    real: Decimal
    imag: Decimal

    def magnitude(self) -> Decimal:
        return (self.real * self.real + self.imag * self.imag).sqrt()


def _add(
    left: tuple[Decimal, Decimal],
    right: tuple[Decimal, Decimal],
) -> tuple[Decimal, Decimal]:
    return left[0] + right[0], left[1] + right[1]


def _multiply(
    left: tuple[Decimal, Decimal],
    right: tuple[Decimal, Decimal],
) -> tuple[Decimal, Decimal]:
    return (
        left[0] * right[0] - left[1] * right[1],
        left[0] * right[1] + left[1] * right[0],
    )


def _divide(
    numerator: tuple[Decimal, Decimal],
    denominator: tuple[Decimal, Decimal],
) -> tuple[Decimal, Decimal]:
    scale = denominator[0] ** 2 + denominator[1] ** 2
    return (
        (numerator[0] * denominator[0] + numerator[1] * denominator[1])
        / scale,
        (numerator[1] * denominator[0] - numerator[0] * denominator[1])
        / scale,
    )


def _decimal_sin_cos(angle: Decimal) -> tuple[Decimal, Decimal]:
    """Return sin and cos with range reduction under the active context."""

    two_pi = 2 * _DECIMAL_PI
    reduced = angle % two_pi
    if reduced > _DECIMAL_PI:
        reduced -= two_pi
    squared = reduced * reduced
    sine = reduced
    cosine = Decimal(1)
    sine_term = reduced
    cosine_term = Decimal(1)
    threshold = Decimal(10) ** (-(getcontext().prec - 5))
    order = 1
    while True:
        sine_term *= -squared / Decimal((2 * order) * (2 * order + 1))
        cosine_term *= -squared / Decimal((2 * order - 1) * (2 * order))
        sine += sine_term
        cosine += cosine_term
        if abs(sine_term) < threshold and abs(cosine_term) < threshold:
            return sine, cosine
        order += 1


def _positive_base_power(
    base: int,
    exponent: tuple[Decimal, Decimal],
) -> tuple[Decimal, Decimal]:
    logarithm = Decimal(base).ln()
    magnitude = (exponent[0] * logarithm).exp()
    sine, cosine = _decimal_sin_cos(exponent[1] * logarithm)
    return magnitude * cosine, magnitude * sine


def high_precision_riemann_zeta(
    sigma: float | str | Decimal,
    height: float | str | Decimal,
    *,
    digits: int = 50,
) -> HighPrecisionComplex:
    """Evaluate zeta with Decimal Euler--Maclaurin arithmetic."""

    if digits < 24:
        raise ValueError("high-precision zeta requires at least 24 digits")
    with localcontext() as context:
        context.prec = digits + 12
        real = sigma if isinstance(sigma, Decimal) else Decimal(str(sigma))
        imag = height if isinstance(height, Decimal) else Decimal(str(height))
        if real == 1 and imag == 0:
            raise ValueError("zeta has a pole at s=1")
        s = (real, imag)
        cutoff = max(96, int(abs(float(imag)) / 2.0) + 48)
        total = (Decimal(0), Decimal(0))
        for integer in range(1, cutoff):
            total = _add(
                total,
                _positive_base_power(integer, (-real, -imag)),
            )
        total = _add(
            total,
            _divide(
                _positive_base_power(cutoff, (Decimal(1) - real, -imag)),
                (real - 1, imag),
            ),
        )
        half_tail = _positive_base_power(cutoff, (-real, -imag))
        total = _add(total, (half_tail[0] / 2, half_tail[1] / 2))

        rising = s
        for order, (numerator, denominator) in enumerate(
            _BERNOULLI_FRACTIONS, 1
        ):
            if order > 1:
                rising = _multiply(
                    rising,
                    (real + 2 * order - 3, imag),
                )
                rising = _multiply(
                    rising,
                    (real + 2 * order - 2, imag),
                )
            tail_power = _positive_base_power(
                cutoff,
                (-real - 2 * order + 1, -imag),
            )
            term = _multiply(rising, tail_power)
            coefficient = Decimal(numerator) / (
                Decimal(denominator) * Decimal(math.factorial(2 * order))
            )
            total = _add(
                total,
                (coefficient * term[0], coefficient * term[1]),
            )
        context.prec = digits
        return HighPrecisionComplex(+total[0], +total[1])


def _high_precision_theta(height: Decimal) -> Decimal:
    return (
        height / 2 * (height / (2 * _DECIMAL_PI)).ln()
        - height / 2
        - _DECIMAL_PI / 8
        + 1 / (48 * height)
        + 7 / (5760 * height**3)
        + 31 / (80640 * height**5)
    )


def high_precision_riemann_siegel_z(
    height: float | str | Decimal,
    *,
    digits: int = 50,
) -> Decimal:
    with localcontext() as context:
        context.prec = digits + 12
        decimal_height = (
            height if isinstance(height, Decimal) else Decimal(str(height))
        )
        zeta = high_precision_riemann_zeta(
            Decimal("0.5"), decimal_height, digits=digits + 6
        )
        sine, cosine = _decimal_sin_cos(_high_precision_theta(decimal_height))
        value = cosine * zeta.real - sine * zeta.imag
        context.prec = digits
        return +value


def _argument_increment(previous: complex, current: complex) -> float:
    product = previous.conjugate() * current
    return math.atan2(product.imag, product.real)


def numerical_riemann_von_mangoldt_count(
    height: float,
    *,
    vertical_step: float = 0.25,
    horizontal_step: float = 0.01,
) -> dict[str, object]:
    """Numerically continue arg(zeta) along the standard 2 -> 2+iT -> 1/2+iT path."""

    if height <= 10.0:
        raise ValueError("zero-count height must exceed 10")
    if vertical_step <= 0.0 or horizontal_step <= 0.0:
        raise ValueError("argument-continuation steps must be positive")
    previous = riemann_zeta(2.0 + 0.0j)
    argument = cmath.phase(previous)
    maximum_increment = 0.0

    vertical_segments = math.ceil(height / vertical_step)
    for index in range(1, vertical_segments + 1):
        current = riemann_zeta(2.0 + 1j * height * index / vertical_segments)
        increment = _argument_increment(previous, current)
        argument += increment
        maximum_increment = max(maximum_increment, abs(increment))
        previous = current

    horizontal_segments = math.ceil(1.5 / horizontal_step)
    for index in range(1, horizontal_segments + 1):
        sigma = 2.0 - 1.5 * index / horizontal_segments
        current = riemann_zeta(sigma + 1j * height)
        increment = _argument_increment(previous, current)
        argument += increment
        maximum_increment = max(maximum_increment, abs(increment))
        previous = current

    continuous_count = (
        riemann_siegel_theta(height) / math.pi
        + 1.0
        + argument / math.pi
    )
    nearest_integer = round(continuous_count)
    return {
        "height": height,
        "continuous_count": continuous_count,
        "nearest_integer_count": nearest_integer,
        "integer_closure_error": abs(continuous_count - nearest_integer),
        "unwrapped_argument_over_pi": argument / math.pi,
        "maximum_phase_increment": maximum_increment,
        "vertical_step": vertical_step,
        "horizontal_step": horizontal_step,
    }


def _precision_check(
    roots: tuple[float, ...],
    one_based_indices: tuple[int, ...],
    *,
    digits: int,
    bracket_half_width: float = 1.0e-8,
) -> tuple[dict[str, object], ...]:
    checks = []
    for one_based_index in one_based_indices:
        root = roots[one_based_index - 1]
        zeta = high_precision_riemann_zeta(0.5, root, digits=digits)
        left_value = high_precision_riemann_siegel_z(
            root - bracket_half_width, digits=digits
        )
        right_value = high_precision_riemann_siegel_z(
            root + bracket_half_width, digits=digits
        )
        checks.append(
            {
                "zero_index": one_based_index,
                "height": root,
                "zeta_residual": float(zeta.magnitude()),
                "bracket_half_width": bracket_half_width,
                "left_z_sign": -1 if left_value < 0 else 1,
                "right_z_sign": -1 if right_value < 0 else 1,
                "sign_change_confirmed": left_value * right_value < 0,
            }
        )
    return tuple(checks)


def run_validated_riemann_extension(
    *,
    zero_count: int = 512,
    precision_digits: int = 50,
    seed: int = 4_729,
) -> dict[str, object]:
    """Validate a higher zero record, then assimilate higher spacing windows."""

    if zero_count < 160:
        raise ValueError("validated extension requires at least 160 zeros")
    roots = critical_line_zeros(zero_count + 1)
    count_height = 0.5 * (roots[zero_count - 1] + roots[zero_count])
    coarse_count = numerical_riemann_von_mangoldt_count(count_height)
    fine_count = numerical_riemann_von_mangoldt_count(
        count_height,
        vertical_step=0.125,
        horizontal_step=0.005,
    )
    precision_indices = tuple(
        sorted({1, 128, zero_count // 2, 3 * zero_count // 4, zero_count})
    )
    precision_checks = _precision_check(
        roots,
        precision_indices,
        digits=precision_digits,
    )
    maximum_residual = max(
        float(check["zeta_residual"]) for check in precision_checks
    )
    count_agreement = (
        coarse_count["nearest_integer_count"]
        == fine_count["nearest_integer_count"]
        == zero_count
    )
    certification_passed = (
        count_agreement
        and coarse_count["integer_closure_error"] < 1.0e-7
        and fine_count["integer_closure_error"] < 1.0e-7
        and fine_count["maximum_phase_increment"] < math.pi / 2.0
        and maximum_residual < 1.0e-8
        and all(bool(check["sign_change_confirmed"]) for check in precision_checks)
    )

    posterior = initialize_ret_posterior(
        riemann_spacing_models(),
        complexity_penalty=0.8,
        open_model_prior=0.03,
        open_model_scale=1.0,
    )
    for start_index in (49, 25, 1, 97):
        action = riemann_window_action(start_index)
        statistics = zero_window_statistics(start_index)
        posterior = update_ret_posterior(
            posterior,
            action,
            statistics["observation"],
            riemann_window_covariance(24),
        )

    proposed_starts = tuple(
        sorted(
            {
                129,
                max(129, zero_count // 2 - 11),
                max(129, 3 * zero_count // 4 - 11),
                zero_count - 23,
            }
        )
    )
    proposed_actions = [riemann_window_action(start) for start in proposed_starts]
    objective = SchedulerObjective(
        riemann_question(),
        cost_weights=CostWeights(time=0.01),
        monte_carlo_samples_per_model=24,
    )
    extension_trace = []
    remaining = list(proposed_actions)
    if certification_passed:
        for step in range(min(3, len(remaining))):
            ranking = rank_actions(
                posterior,
                remaining,
                {
                    action.name: riemann_window_covariance(24)
                    for action in remaining
                },
                objective,
                seed=seed + step,
            )
            selected_name = str(ranking[0]["action"])
            selected = next(
                action for action in remaining if action.name == selected_name
            )
            remaining.remove(selected)
            statistics = zero_window_statistics(
                int(selected.metadata["start_index"]),
                int(selected.metadata["zero_count"]),
            )
            posterior = update_ret_posterior(
                posterior,
                selected,
                statistics["observation"],
                riemann_window_covariance(24),
            )
            extension_trace.append(
                {
                    "step": step + 1,
                    "action": selected.name,
                    "ranking": ranking[0],
                    "statistics": statistics,
                    "posterior": dict(posterior.model_weights),
                }
            )

    selected_model = max(posterior.model_weights, key=posterior.model_weights.get)
    zero_digest = hashlib.sha256(
        "\n".join(f"{root:.15f}" for root in roots[:zero_count]).encode("ascii")
    ).hexdigest()
    return {
        "search": "validated higher-height Riemann spacing extension",
        "warning": RIEMANN_VALIDATION_WARNING,
        "certification_kind": "two-resolution numerical count plus Decimal root checks",
        "interval_enclosure_performed": False,
        "zero_count": zero_count,
        "first_height": roots[0],
        "last_height": roots[zero_count - 1],
        "count_audit_height": count_height,
        "zero_record_sha256": zero_digest,
        "coarse_rvm_count": coarse_count,
        "fine_rvm_count": fine_count,
        "count_agreement": count_agreement,
        "precision_digits": precision_digits,
        "precision_checks": precision_checks,
        "maximum_checked_decimal_residual": maximum_residual,
        "certification_passed": certification_passed,
        "higher_windows_admitted": certification_passed,
        "proposed_window_starts": proposed_starts,
        "extension_trace": extension_trace,
        "selected_model": selected_model,
        "final_posterior": dict(posterior.model_weights),
        "selected_model_parameters": (
            parameter_summary(posterior, selected_model)
            if selected_model in posterior.models
            else {}
        ),
    }


if __name__ == "__main__":
    print(json.dumps(run_validated_riemann_extension(), indent=2))
