from pathlib import Path
import hashlib,importlib.util,json,tempfile
B=Path('/Volumes/AI_DATA/development/det-review-evidence');R=B/'ri234-root-reconciliation-tzop5ais';Q=B/'ri233-native-same-root-contrast-sa2lhrgp';N=B/'ri233-independent-root-transport-review-1d_n8ih1';I=B/'ri234-independent-reconciliation-review-1t1b_0pb';D=B/'ri226-directory-custody-recovery-yvfg_p1b';O=B/'ri226-freeze-reconciliation-operation-yvfg_p1b'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7';s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=R
expected=m.load('/private/tmp/ri234_sealed_reviews.json')
for row in expected['handoffs']:m.verify(row['path'],row)
seals=[]
for base in [N]:
 handoff=m.load(base/'HANDOFF.json');rows=handoff['files'];assert sorted(x.name for x in base.iterdir())==sorted(['HANDOFF.json']+[Path(r['path']).name for r in rows])
 observed=[m.identity(base/'HANDOFF.json')]+[m.verify(r['path'],r) for r in rows];seals.append(dict(handoff=m.ref(base/'HANDOFF.json'),identities=observed))
seal=m.save('ROOT_NATIVE_REVIEW_SEAL.json',dict(schema='ri234-final-nonauthor-seals-v1',reviews=seals,root_complete_reads=expected['root_complete_reads']))
native=m.save('RI233_ROOT_ADJUDICATION.json',dict(schema='ri233-root-native-adjudication-v1',status='ACCEPT_CONDITIONAL_ROOT_TRANSPORT_AND_EXACT_TWO_SECTOR_REDUCTION',packet=m.ref(Q/'HANDOFF.json'),independent_review=m.ref(N/'HANDOFF.json'),root_review=m.ref(R/'RI233_ROOT_REVIEW.md'),root_metadata=m.ref(R/'RI233_ROOT_METADATA.json'),actual_author_final=m.ref(R/'RI233_AUTHOR_FINAL_RECEIPT.json'),final_review_seals=seal,accepted=['Complete actual C5 root transport including e=theta*c','Finite root transport through supported C3-plus-cap rows at common rho/s layers','All five explicit allocation-offset cancellations and division-free zero-branch/reference equivalence','Every actual same-root contrast/minor vanishes for arbitrary W','Exact full reduction to five disconnected and eight connected cross-root equations,two connected identities','Complete held D4/D5 simplifications and allocation-free R10'],unresolved=['Actual nonzero connected contrasts','Full normalized u2=-1 witness or finite signed inconsistency','Improvement,optimality and maximal amplitude'],scientific_execution=False,qualification_credit=0,RET_paused=True))
nextq=Path(tempfile.mkdtemp(prefix='ri235-native-cross-root-d2-',dir=B))
assignment=m.save('RI235_NATIVE_ASSIGNMENT.json',dict(schema='ri235-native-cross-root-assignment-v1',status='ASSIGNED_AFTER_RI233_ADJUDICATION',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(nextq),predecessor=native,predecessor_packet=m.ref(Q/'HANDOFF.json'),source_references=m.ref(Q/'SOURCE_REFERENCES.json'),independent_review=m.ref(N/'HANDOFF.json'),question='Can the actual cross-root system decide the normalized witness, prioritizing the minimal D2 obstruction route?',requirements=['Use the accepted exact R11-R13 system, R7-R10 held identities and actual fixed law; same-root equations are now known identities.','Prioritize proving or refuting nonzero actual f_j(1)-f_j(0) for j=4,5,6,7. If all are nonzero their connected equations force U4,U5,U6,U7=0. Do not require j9,j10 as blanket prerequisites.','With those directions zero, D2 requires g2(0)*b1^2-g2(1)*b0^2=0 because theta^2*Gamma2/a>0. Determine an actual consequence for this coefficient from existing admitted law/normalization, without relaxing actual canonical allocations. A finite signed row combination may certify inconsistency if the necessary contrasts are proved nonzero.','Preserve every zero-contrast branch. If an actual connected contrast vanishes, retain the corresponding free direction and exploit the resulting reduced equations toward a full witness or signed inconsistency.','A conditional restatement of this criterion alone is not the intended result: prove at least one additional substantive actual-law contrast/sign/cancellation fact, then resolve the smallest remaining precise premise if a complete decision is not yet possible.','Retain all five disconnected/eight connected equations,ten unknowns,u2=-1,actual g1/g2 offsets,common T1/T2/T3/reference/Gamma recovery and positive full-slot denominators. Do not claim generic rank, numerical amplitude, full feasibility or a relaxed-allocation result as the actual-law decision.'],source_authority='Renew only already admitted exact analytic sources and accepted finite premises in RI233 SOURCE_REFERENCES, plus RI233 proofs and independent/root reviews. No new scientific body or coordinate authority; historical exceptions remain historical.',prohibitions=['No automatic scientific arithmetic,calculator,Fraction,graph/LP/numerical engine,H/z reconstruction or original coefficient/body parsing.','No scientific or runtime subject,fixtures,cards,measurement,RET,repository/Git/index operations.','Do not self-assign a successor. Return a bounded sealed result for root review; root selects the next justified step.'],qualification_credit=0,RET_paused=True))

print(json.dumps(dict(native=native,native_assignment=assignment,native_reservation=str(nextq))))
