import hashlib,importlib.util,tempfile
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri207-root-four-maxima-review-rrel_hre';Q=B/'ri205-native-four-maxima-7gkvoked'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
meta=m.load(D/'RI205_ROOT_METADATA_CHECK.json');assert meta['status']=='PASS_METADATA_NOT_MATHEMATICAL_EXECUTION' and len(meta['fresh_identities'])==21
for row in meta['fresh_identities']:assert m.identity(row['path'])==row
text='''# Root independent adjudication of RI205

Accept the complete four-maxima class as a conditional theorem about the named unchanged finite prefix. Root read both full manuscripts (efc264), all source references (3f1be2), the complete accepted RI41/RI63 analytic definitions (04f165), and the complete handoff/author record with embedded administrative checker (c8dc13). The printed numerical M5 was visible in inherited prose but was not used as an operand. No certificate/vector body or scientific executor was used. The nonauthor review independently agrees.

The omission partition is exact: four single sectors yield4-L, six double sectors, four triple sectors, and one all-four sector. Each labeled ideal, full base ideal and record remains. Double denominators can be full four-parent entries and use the all-ideal epsilon floor. Complete positive subrows exclude their positive full five-parent entries, giving strict C2<K. Shared canonical coordinates remain coupled.

The selected-ideal retained-cap repair is sufficient and correctly scoped. For S=A+i with nonempty A, any remaining old vertex is excluded from E_i and original coverage puts it below some omitted cap. For empty A the chain or a full antichain precursor has the same sole-omitted-maximum argument. Otherwise two distinct singleton precursors on the two-antichain give q_i({i})=(2/5)e and each potential4e^2. Their product divided by q_i is40e^3>4epsilon; two proper1/8 factors plus the third all-ideal floor yield q_i epsilon^2/16. This is not an unsupported all-ideal lemma for the retained-cap base. Strict complete subrow sums give C3_i<16K^2.

The new support argument is valid. A Ferrers cell order containing four original maxima needs four distinct positive row lengths and at least10cells. A largest induced Ferrers suborder of the six-terminal therefore misses an original maximum d. Its deletion preserves the largest Ferrers cardinality, so restoring d raises arbitrary-deletion defect by1. This uses induced-suborder inclusion, not false Ferrers heredity. If the original newborn differs from d, their incomparability gives an ordinary marked diamond connecting the two proper parent-five roles. Both first probabilities are positive and both second slots exclude the other maximum. The accepted finite RI63 theorem consequently forces the canonical boundary component to zero at these roles; theta restoration remains positive. All original marks and both newborn bits are transported.

Each all-four numerator q5 has at least four terminal maxima and is exactly theta*u5. Root checked the complete parity product when old maxima reappear after cap deletion. For one extra old deletion, numerator parent sizes are4 and2(three times), denominator sizes3(three times) and1: correction<=3*110^3. For two extra old deletions the denominator has size3 once and size1 three times, while positive factors have size2 three times and empty-parent1: correction<=27*110. Old maxima are uncovered precisely when no retained precursor contains them. Original coverage permits each old vertex in at most one retained triple, hence at most two occurrences total. All correction products are bounded by243*110^7, including both extras in the same triple.

The literal complete seed gives q1>=1/3 and q3>=1/110. Root checked all five shapes and both record cases. Antichain proper total1/5; edge-plus-isolate23/88; fork12/55 or6/55; join1/11; chain3/44, so their full complements meet the stated floors. No full probability was replaced by an invented potential. Identical-factor cancellation has pairs twice, singleton factors three times and B four times; c4=theta^4 Gamma B^3 product(q_pair)/product(q_single)^2. Thus complete B normalization bounds C4<=theta^4*243*110^15. The native M5>10^9 implies theta<2^-30 and243*110^15<2^113, giving C4<1/128 by hand.

The same native A5 witness retains multiplicities5,10,10,5,1. Since243/1024>1/5 and11^5=161051>160000, M5>5.12billion>5billion. The unchanged target then exceeds465billion. With K<76000,64*76000^2=369664000000 and6*76000=456000, giving U6<369664456005<370billion<T. No maximizing-parent or actual-theta evaluation is needed.

Root metadata990fe0 exit0 independently checks15direct sources/543096bytes, six current files,29selected references,current/prior six-file namespaces and15unchanged inherited boundaries. The complete author checker was read; reported final0603bd exit0 covers21identities/29references, distinct from recorded preseal0a19b6 with19/26. This attribution is not a replay of the author's code or the inherited423/26/18 collections. The original clipped status-display diagnostic is retained. Root entry typo ee7497 failed before snapshot or any subject activity; its correction preserves the same empty reservation and is recorded separately.

Nonauthor /root/qr_opportunities independently read both manuscripts with pre/post hashes1f75a7, accepted support/seed premises63eaf1, full author checker885e29 and sealed handoff/final pinsf2bfc3 (all exit0). Its later supplement reconciles externally reported0603bd with the reviewed checker, without claiming a replay. No mathematical blocker was found.

One through four maxima are now settled against T. Five/six maxima, global M6, actual W, both individual margins, H30 and physical correspondence remain open. All executable qualifications and original P2/P3,Y=1/4,sharedT1,other eight parents,fiveDi and92/34/35 plus31/139/20/42 obligations remain uncredited. RET alone remains paused.
'''
with (D/'RI205_ROOT_PROOF_REVIEW.md').open('x') as f:f.write(text)
decision=m.save('RI205_ROOT_ADJUDICATION.json',dict(schema='ri207-root-ri205-adjudication-v1',status='ACCEPT_COMPLETE_FOUR_MAXIMA_CLASS_CONDITIONAL_THEOREM',handoff=m.ref(Q/'HANDOFF.json'),proof=m.ref(Q/'FOUR_MAXIMA.md'),lemma=m.ref(Q/'FOUR_OMISSION_LEMMA.md'),metadata=m.ref(D/'RI205_ROOT_METADATA_CHECK.json'),root_review=m.ref(D/'RI205_ROOT_PROOF_REVIEW.md'),theorem='Every actual marked six-parent with four maxima has U6<4+6K+64K^2+1/128<369664456005<370000000000<465000000000<T, K=681472/9.',premises=m.load(Q/'HANDOFF.json')['inherited_premises_not_fresh_verification'],independent_nonauthor_review=True,whole_class_not_selected_records=True,global_M6_bound_proved=False,actual_W_decided=False,both_margins_or_H30_decided=False,scientific_execution=False,qualification_credit=False,ret_paused=True))
nextdir=Path(tempfile.mkdtemp(prefix='ri208-native-five-maxima-',dir=B))
assignment=m.save('RI208_NATIVE_ASSIGNMENT.json',dict(schema='ri208-native-assignment-v1',status='ASSIGNED_AFTER_RI205_INDEPENDENT_ADJUDICATION',reservation=str(nextdir),owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',predecessor=decision,question='Prove or refute U6<=T for the entire five-maxima six-parent class of the unchanged selected law; all compatible precursor choices, marked rows and proper ideals. A genuine violating parent refutes this sufficient bound only.',domain='R is one event; five cap precursors are empty or R and cover R. Partition all five omitted-maxima sector sizes, retaining every proper ideal and every actual shared canonical factor.',justified_starting_points=['One-omission mass5-L with0<L<5; ten double sectors have all-ideal q4 floor and candidate bound C2<K.','For each triple-omission sector the retained two caps belong to S. A nonempty A exhausts R; if A is empty, original coverage gives an omitted cap covering the sole old vertex. Reprove the selected-ideal denominator lower bound q_base(S)*epsilon^2/8; if correct this gives each of ten C3<8K^2, leaving U6 below5+10K+80K^2 before higher sectors.','RI205 support lemma applies to proper parent-five births ending with at least four maxima; prove where this gives exact theta factors in four/five omission sectors. Retain all additional old omitted maxima.','RI205 native M5>5e9 gives theta<2^-38 by hand, if useful. Use no printed maximum or actual scale. The unchanged T>465e9 leaves room only after proving complete higher-sector bounds.'],requirements=['Manual analytic reasoning on accepted seed/support/normalization/diamonds, not independent coordinate boxes.','Separate selected-ideal coverage from all-ideal claims; full q4 entries use all-ideal floor only.','Preserve every mark, labeled ideal multiplicity, repeated/empty/full precursor and canonical correction.','No new scientific body/vector/certificate read, automated proof arithmetic, graph/LP/subject execution or runtime/fixture/card changes.','Read current plan and reservation; source-only sealed packet and complete administrative diagnostics. Root owns independent adjudication, Git and successor.','If no whole-class closure, report a sharp proved partial inequality or actual obstruction; do not label a relaxed model counterexample as native.'],six_maxima_or_global_conclusion_preaccepted=False,ret_paused=True))
with (D/'adjudicate_native.py').open('xb') as f:f.write(Path(__file__).read_bytes())
print(decision);print(assignment);print(nextdir)
