from pathlib import Path
import hashlib,importlib.util,tempfile,stat,os
B=Path('/Volumes/AI_DATA/development/det-review-evidence');R=B/'ri249-root-premode-operation-hcybjv4k';Q=B/'ri248-native-canonical-companion-of3isoc8'
p=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=p.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7';s=importlib.util.spec_from_file_location('m',p);m=importlib.util.module_from_spec(s);exec(compile(raw,str(p),'exec'),m.__dict__);m.D=R
seen={}
def check(r):
 assert not r['path'].endswith(('/CERTIFICATE.json','/check.py'))
 v=m.verify(r['path'],r);assert not v['symlink_chain'] and v['resolved_path']==v['path'];seen[v['path']]=v;return v
hand=dict(path=str(Q/'HANDOFF.json'),bytes=16711,sha256='05d9cc76d28e67e3d6c58b5775427e6d0bcd9bcb49195fd75164478a63186a9a');check(hand);h=m.load(hand['path']);assert sorted(x.name for x in Q.iterdir())==sorted(h['namespace'])
for r in h['files']:check(r)
s=m.load(Q/'SOURCE_REFERENCES.json');assert len(s['direct_sources'])==102 and sum(r['identity']['bytes'] for r in s['direct_sources'])==2139499
for r in s['direct_sources']:check(r['identity'])
assert len(seen)==108
prior=m.load(s['predecessor_references']['path']);assert s['preserved_boundary_keys']==prior['preserved_boundary_keys'] and len(s['preserved_boundary_keys'])==15
for key in s['preserved_boundary_keys']:assert s['preserved_boundaries'][key]==prior['preserved_boundaries'][key]
for row in prior['direct_sources']:assert any(row['identity']==x['identity'] for x in s['direct_sources'])
assert len(prior['direct_sources'])==91 and s['closed_RI246_literal_exception_by_reference']['closed'] is True
author=m.load(Q/'AUTHOR_VERIFICATION.json');assert h['diagnostics']==s['diagnostics']==author['diagnostics'] and h['canonical_Cb_resolved'] is False and h['actual_kappa_gap_resolved'] is False
for r in list(seen.values()):assert m.identity(r['path'])==r
checkref=m.save('RI248_ROOT_METADATA_CHECK.json',dict(status='PASS_BOUNDED_ADMINISTRATIVE_COMPARISON',identities=list(seen.values()),direct_sources=102,direct_bytes=2139499,predecessor_sources=91,preserved_boundaries=15,whole_identities=108,original_scientific_body_read=False,proof_arithmetic=False,scientific_execution=False,full_manual_proof_reads=['0cfbff','d5b22d','d6775c','4f2a34'],genuine_final=m.ref(R/'RI248_GENUINE_FINAL.json')))
review=Path('/private/tmp/ri248-independent-review-0838c4.txt');m.verify(review,dict(bytes=14436,sha256='045ad7fecc017e591feb1748f1d860d1ef78e6abb80b01df1eb69187b6d180ec'))
with (R/'RI248_INDEPENDENT_REVIEW.txt').open('xb') as f:f.write(review.read_bytes())
decision=m.save('RI248_ROOT_ADJUDICATION.json',dict(status='ACCEPT_COMPLETE_COMPANION_WEIGHTED_EXCHANGE_DUAL_NECESSITY_AND_STRUCTURAL_KEYS_ONLY',handoff=hand,root_check=checkref,independent_review=m.ref(R/'RI248_INDEPENDENT_REVIEW.txt'),root_complete_review_read='e48501',accepted=['Complete nine-proper-ideal companion row with all four component families and32whole records','Actual5/9/7history multiplicities imply L_i=0<T_i','Positive kappa implies complete tight companion capacity and positive primary dual mass','Structural roots kappa=(8590,17,i),tau=(8604,17,i); original ranks still unknown'],premises=['fixed prescribed finite law','accepted positive lower probabilities','complete original primary and sequential lexicographic optimizer','all13equations10coordinates and complete recovery','all15inherited boundaries and423manifest by reference'],unresolved=['actual kappa gap','actual canonical C_b','original798rank binding','sparse-value schema'],actual_normalized_witness=False,actual_signed_inconsistency=False,scientific_execution=False,RET_paused=True))
N=Path(tempfile.mkdtemp(prefix='ri250-native-canonical-literals-',dir=B))
target=m.REPO/'docs/track_b/native_growth_expected_defect_completion_v1/CERTIFICATE.json';expected=dict(path=str(target),bytes=19805,sha256='f55625a686b4c859a8b3e720c80fbabbe9cfa0972cb7a9e78a50d1705833c28b')
cur=Path('/')
for part in target.parts[1:]:cur=cur/part;assert not cur.is_symlink()
z=target.lstat();assert stat.S_ISREG(z.st_mode) and z.st_size==19805 and target.resolve()==target
ad=m.save('RI250_TWO_ROLE_LITERAL_ADMISSION.json',dict(schema='ri250-bounded-original-canonical-literal-admission-v1',status='AUTHORIZE_BOUNDED_MANUAL_LITERAL_BINDING_ONLY',predecessor=decision,expected_original=expected,expected_identity_origin='RI63 admitted COMPLETION.md hash plus metadata-only stable19805-byte lstat; fresh authentication is a condition of this new admission',pre_admission_lstat=[z.st_dev,z.st_ino,z.st_mode,z.st_nlink,z.st_size,z.st_mtime_ns,z.st_ctime_ns],readers=['Quantum Relativity chat01a074c4-4b09-76a3-8cb2-0caf116f6b9c','root coordinator01a09c7a-ebce-7213-b06a-43315ae68fd5','root nonauthor subagent qr_opportunities'],permitted='One complete bounded literal display per reader, repeated only to recover a truncated display under same whole pin; opaque whole-file nofollow custody hash before/after. Manual structural/index/schema binding and transcription of only two canonical role strings after binding succeeds.',roles=[dict(name='kappa0',root=[8590,17,0]),dict(name='kappa1',root=[8590,17,1])],selector='original canonical alpha^min certified by complete primary and sequential lexicographic selector; never alternative primary optimum or strict mixture',conditions=['normalized no-symlink regular path O_NOFOLLOW stable descriptor/path seven-field states and exact whole length/hash','untruncated genuine literal receipt','original root-to-rank binding among798 before any role-value use','original sparse absence-zero convention explicitly authenticated before absent entries count as zero','manual exact rational comparison only after both bindings'],stop_conditions=['custody or pin mismatch','GAP-INDEX if literal root-to-rank binding absent; no guessedindex109 or reconstruction','GAP-SCHEMA if original sparse convention absent','gap>1/70 leaves C_b unresolved'],prohibited=['scientific JSON decoding/filtering','vector instantiation or extra coefficient extraction','scientific arithmetic/graph/LP/AST/import/compile/execution','regeneration or alternate source','other original bodies or descendant expansion','measurement or RET','Git/index/repository changes'],complete_system_and_recovery_retained=True,other_literal_exceptions_closed=True,scientific_execution=False,ret_paused=True))
text=f'''RI250: two-role canonical literal binding after RI248 adjudication.\nReservation: {N}\nRead and authenticate {R/'RI248_ROOT_ADJUDICATION.json'} and {R/'RI250_TWO_ROLE_LITERAL_ADMISSION.json'}. The companion proof is accepted; actual C_b remains unresolved. Use only the new precisely scoped authority for the single named RI63 original body. Bind roots(8590,17,0/1) to original798component ranks and canonical alpha^min, preserving primary and sequential selection. If original binding or sparse schema is absent, report GAP-INDEX/GAP-SCHEMA before using numerical entries. Do not guess ranks, use coordinate109 as a proxy, or run a reconstruction. With valid binding transcribe only the two role strings and manually test kappa0-kappa1<=1/70; that sufficient comparison implies C_b<0 under the accepted theorem, while its failure does not prove C_b=0.\nRetain complete source custody and genuine literal/check receipts; no body copy or scientific JSON decoding, no mathematical engine or extra values. Other original exceptions stay closed. All13equations10coordinates, complete recovery, records/ideals/newborns, strict endpoints,15boundaries and423manifest remain. No normalized witness or signed inconsistency without the necessary exact comparison and independent acceptance. No measurement/RET/repo/Git. Seal bounded source references, binding witness or precise gap, manual consequence and diagnostics for independent root review. Root retains next assignment and publication.\n'''
with (R/'RI250_ASSIGNMENT.md').open('x') as f:f.write(text)
assignment=m.save('RI250_ASSIGNMENT.json',dict(schema='ri250-canonical-two-role-assignment-v1',status='ASSIGNED_AFTER_PREDECESSOR_ADJUDICATION',predecessor=decision,admission=ad,assignment=m.ref(R/'RI250_ASSIGNMENT.md'),reservation=str(N),thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',scientific_execution=False))
print(decision);print(ad);print(assignment);print(N)
