"""Seal this independent source/admin review only; never invokes any subject."""
from pathlib import Path
import hashlib, importlib.util, json, os
D=Path(__file__).resolve().parent;B=D.parent
S=B/'ri162-inert-qualification-preflight-wb69vu5s'
H=B/'ri122-root-execution-review-6whn_vky'/'metadata.py'
raw=H.read_bytes()
if len(raw)!=3144 or hashlib.sha256(raw).hexdigest()!='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7':raise ValueError('administrative helper pin')
spec=importlib.util.spec_from_file_location('ri162_seal_admin_only',H);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);m.D=D
A=B/'ri161-root-qualification-review-0dyyjyuy'/'MEASUREMENT_REVIEW_ASSIGNMENT.json'
subject=m.load(S/'HANDOFF.json');check=m.load(D/'METADATA_CHECK.json')
if sorted(p.name for p in S.iterdir())!=subject['namespace']:raise ValueError('subject namespace changed')
for row in subject['payloads']:
    if m.ref(row['path'])!=row:raise ValueError('subject changed: '+row['path'])
for old in check['identities']:
    new=m.identity(old['path'])
    if m.pure(new)!=m.pure(old) or new['resolved_path']!=old['resolved_path'] or new['symlink_chain']!=old['symlink_chain']:raise ValueError('reviewed opaque identity changed: '+old['path'])
proposal=m.load(S/'QUALIFICATION_PROPOSAL.json')
if any(os.path.lexists(p) for p in proposal['operation_paths_not_created'].values()):raise ValueError('proposed operation path no longer absent')
status='ACCEPT_EXACT_PREFLIGHT_PROPOSAL_FOR_ROOT_GENUINE_PREFLIGHT_AND_SEPARATE_INERT106_ADMISSION'
next_action='Root freshly checks complete selected vendor/framework/suppliers, host/loader/cache applicability and exact sources; exclusively prepares the stated root/env/monitor paths and request; writes the genuinely rooted preflight and separate12-field admission; then performs one bounded command, preserves actual tool/monitor/adapter/partial evidence and independently reviews all106 results and external postchecks.'
verdict={'schema':'ri162-independent-preflight-verdict-v1','status':status,'blocking_source_findings':[],'source_repair_required':False,'fixed_current_binding_drift':False,'adoptable_concrete_command_proposal':True,'operational_admission':False,'operationally_ready_without_external_preflight':False,'controls':{'defined':106,'executed':0},'reviewer':'/root/archive_repro_review','independence':'Nonauthor of RI162 and RI156/158/160 subjects. Historical WHITE validator/caller/bootstrap including RI141 authored by reviewer; accepted monitor semantics inherited from separate nonauthor/root decisions, not independently self-accepted here.','subject':m.ref(S/'HANDOFF.json'),'assignment':m.ref(A),'narrative':m.ref(D/'INDEPENDENT_SOURCE_REVIEW.md'),'actual_admin_check':m.ref(D/'METADATA_CHECK.json'),'actual_tool':{'chunk_id':'5b8398','exit_code':0},'finite_checks':{'predicates':3224,'source_review_objects':623,'source_dependencies':567,'unique_opaque_observations':642,'source_review_bytes':33796686,'unchanged_literal_monitor_helpers':8,'invocation_lines':17,'current_fixed_files':6,'absent_prospective_paths':8},'remaining_immediate_prerequisites':['Root adoption, fresh complete supplier/framework/host/environment/source/card preflight and explicit stable loader/cache/no-descendants premises','Exclusive actual setup, real current preflight FilePin and separately recorded admission/dispatch','One actual bounded invocation and actual initial/pending/terminal tool records with independently reviewed streams,ps attempts,samples,reap and partials','Independent full106 outcomes and complete source/card/supplier/environment/namespace postchecks, even after failure'],'later_separate':['R01 path applicability','new E unchanged RI141 capture/baseline/profiles','WHITE normal-before-optimized and complete saved arithmetic','RI131 actual-validator mutation campaign','actual15/full32/public-data/physical interpretation'],'next_root_action':next_action,'bounds_unchanged':{'child_wall_seconds':180,'sampled_child_rss_kib':524288,'target_poll_seconds':0.025,'max_initial_interior_final_gap_seconds':0.1,'ps_timeout_seconds':0.05,'file_bytes':67108864,'outer_alarm_seconds':960},'limitations':['Sampled child only, not parent/group or continuous RSS quota.','Outer death/stall does not certify cleanup; no-descendants/stable-supplier and external host/loader/cache premises retained.','Six fixed observations and OS facts are not whole supplier preflight, runtime profile or selected vendor execution.','Inert controls contain explicit observer/authority substitutes and cannot establish authentic scientific/runtime/credential outcomes.'],'subject_import_compile_AST_probe_run':False,'scientific_decode':False,'active_runtime_card_freeze_admission_E_or_fixture_created':False,'repository_or_Git':False,'new_agents':0,'RET':'paused'}
m.save('VERDICT.json',verdict)
tool={'schema':'ri162-independent-genuine-administrative-tool-result-v1','provenance':'Transcribed from actual tool delivery to this reviewer. Does not self-authenticate tool origin or create operational evidence.','command':'python3 -I -B '+str(D/'check_preflight.py'),'chunk_id':'5b8398','exit_code':0,'stdout_object':{'all_paths_absent':True,'controls_executed':0,'current_selected_binding_exact':True,'current_selected_files':6,'eight_unchanged_spans':8,'predicates':3224,'result':m.ref(D/'METADATA_CHECK.json'),'source_dependencies':567,'source_evidence_bytes':33796686,'source_evidence_count':623,'status':'ALL_FINITE_ADMINISTRATIVE_CHECKS_PASSED','unique_observed_identities':642},'stderr':'','preceding_same_cell_edit':'Before the first checker invocation, replaced JSON-incompatible set comparison with sorted lists. This was checker authoring only; no prior failed check existed.','subject_executed':False}
m.save('ADMIN_TOOL_RESULT.json',tool)
reads=[('1b45df','assignment and authenticated subject seal/13 namespace/12payloads'),('1b28e4','complete preflight contract and literal invocation'),('6862aa','complete proposal and fixed current facts'),('ac89bf','complete proposal/facts author scripts, diagnostics and retained exact failed-read stderr'),('c7a734','complete sealing source/final/publication and selecting root assignments/adjudications'),('87c247','monitor imports/constants/helpers and source lines1–360'),('ca4eae','complete monitor327–404 completion path and full adapter1–289; unrelated adjacent source text only'),('ad155b','monitor guarded entry, full contract and proposal writer'),('98e8c4','trusted administrative helper, review assignment and full fixed-fact record'),('d3624a','source ID/runner references, final-fixture consequence text, all17 literal lines and author actual diagnostics'),('513c17','complete combined/integration/inert runner interfaces and full current facts observer script')]
diag={'schema':'ri162-independent-reviewer-diagnostics-v1','actual_read_tools':[{'chunk_id':a,'exit_code':0,'scope':b} for a,b in reads],'administrative_check':m.ref(D/'ADMIN_TOOL_RESULT.json'),'actual_own_failed_commands':[],'own_clipped_displays':[],'author_preserved_failed_commands':[{'chunk_id':'de440f','exit_code':2,'reason':'Incorrect RI139 launch.py filename; correct launch_controls.source-only.py recovered. No subject execution.','stderr':m.ref(S/'READ_DIAGNOSTIC.stderr'),'declared_recoveries':['791097','916f14']}],'author_preserved_clipped_read':{'chunk_id':'163082','exit_code':0,'recovered_relevant_eight_entries':'d2a510'},'author_diagnostics':m.ref(S/'ACTUAL_READ_ONLY_DIAGNOSTICS.json'),'own_write_tools_before_seal':[{'chunk_id':'c0d090','exit_code':0,'scope':'wrote independent admin checker'},{'chunk_id':'a8b890','exit_code':0,'scope':'wrote narrative'}],'authoring_correction_before_first_run':'Sorted-list metadata comparison substituted for Python set before first check execution, in cell5b8398; no discarded failure or target execution.','own_actual_executed_selected_OS_utility':{'command':['/usr/bin/sw_vers'],'returncode':0,'stderr':'','scope':'read-only permitted host OS facts; selected vendor never invoked'},'seal_tool_result':'Delivered separately after seal; not fabricated in this pre-result document.','only_writable_reservation':str(D),'source_only':True,'scientific_decode':False,'RET':'paused'}
m.save('REVIEWER_DIAGNOSTICS.json',diag)
namespace=sorted(['check_preflight.py','METADATA_CHECK.json','INDEPENDENT_SOURCE_REVIEW.md','seal_review.py','VERDICT.json','ADMIN_TOOL_RESULT.json','REVIEWER_DIAGNOSTICS.json','PUBLICATION_SUBSET.json','FINAL_SEAL_CHECK.json','HANDOFF.json'])
m.save('PUBLICATION_SUBSET.json',{'schema':'ri162-independent-publication-subset-v1','include_names':[n for n in namespace if n!='METADATA_CHECK.json'],'external_only':[m.ref(D/'METADATA_CHECK.json')],'reason':'Preserve the complete1,050,142-byte identity/predicate diagnostic immutable externally; publish compact actual tool result, reproducible checker, full narrative/verdict and exact reference.','older_subject_failures':'Remain immutable in subject seal; this review pins their exact declarations and stderr.'})
base=sorted(p.name for p in D.iterdir())
if base!=sorted(set(namespace)-{'FINAL_SEAL_CHECK.json','HANDOFF.json'}):raise ValueError('unexpected review namespace before seal')
m.save('FINAL_SEAL_CHECK.json',{'schema':'ri162-independent-final-seal-check-v1','subject_handoff':m.ref(S/'HANDOFF.json'),'assignment':m.ref(A),'subject_namespace_exact':True,'subject_payloads':12,'rechecked_unique_opaque_identities':len(check['identities']),'all_whole_byte_pins_and_selection_routes_still_exact':True,'all_proposed_paths_still_absent':True,'actual_admin_tool':{'chunk_id':'5b8398','exit_code':0},'checker':m.ref(D/'check_preflight.py'),'administrative_check':m.ref(D/'METADATA_CHECK.json'),'narrative':m.ref(D/'INDEPENDENT_SOURCE_REVIEW.md'),'verdict':m.ref(D/'VERDICT.json'),'actual_tool_result':m.ref(D/'ADMIN_TOOL_RESULT.json'),'diagnostics':m.ref(D/'REVIEWER_DIAGNOSTICS.json'),'publication':m.ref(D/'PUBLICATION_SUBSET.json'),'seal_source':m.ref(D/'seal_review.py'),'controls_executed':0,'operational_admission':False,'RET':'paused'})
files=[m.ref(p) for p in sorted(D.iterdir())]
m.save('HANDOFF.json',{'schema':'ri162-independent-preflight-review-handoff-v1','status':'SEALED_INDEPENDENT_REVIEW_FOR_ROOT_ADJUDICATION','recommendation':status,'reviewer':'/root/archive_repro_review','reservation':str(D),'subject':m.ref(S/'HANDOFF.json'),'assignment':m.ref(A),'review':m.ref(D/'INDEPENDENT_SOURCE_REVIEW.md'),'verdict':m.ref(D/'VERDICT.json'),'administrative_check':m.ref(D/'METADATA_CHECK.json'),'actual_tool_result':m.ref(D/'ADMIN_TOOL_RESULT.json'),'diagnostics':m.ref(D/'REVIEWER_DIAGNOSTICS.json'),'final_check':m.ref(D/'FINAL_SEAL_CHECK.json'),'publication_subset':m.ref(D/'PUBLICATION_SUBSET.json'),'blocking_source_findings':[],'controls_defined':106,'controls_executed':0,'actual_administrative_tool':{'chunk_id':'5b8398','exit_code':0},'actual_admin_counts':verdict['finite_checks'],'no_subject_execution':True,'no_operational_admission':True,'prior_authorship_disclosed':verdict['independence'],'next_root_action':next_action,'namespace':namespace,'files':files,'sealed_immutable':True,'RET':'paused','seal_tool_result':'Actual subsequent tool result is separately delivered to root; this handoff does not invent its identity.'})
if sorted(p.name for p in D.iterdir())!=namespace:raise ValueError('final review namespace')
for row in files:
    if m.ref(row['path'])!=row:raise ValueError('own payload changed')
print(json.dumps({'status':'SEALED','namespace':len(namespace),'payloads':len(files),'handoff':m.ref(D/'HANDOFF.json'),'final_check':m.ref(D/'FINAL_SEAL_CHECK.json'),'verdict':m.ref(D/'VERDICT.json'),'review':m.ref(D/'INDEPENDENT_SOURCE_REVIEW.md'),'controls_executed':0,'blocking_source_findings':[]},sort_keys=True))
