from pathlib import Path
import importlib.util,hashlib,json,tempfile
B=Path('/Volumes/AI_DATA/development/det-review-evidence');old=B/'ri230-root-lower-combinations-review-v9mxbmtc';Q=B/'ri231-native-six-root-witness-qboypkl8';I=B/'ri231-independent-six-root-review-fipt97mw'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7';s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
R=Path(tempfile.mkdtemp(prefix='ri232-root-canonical-review-',dir=B));m.D=R
assert m.git('rev-parse','HEAD').decode().strip()=='5fcbe0ada46c54ccecd14e98ba7ad8c2e29274b7' and m.git('diff','--cached','--name-only')==b''
m.save('REPO_ENTRY.json',m.snapshot());checked={}
def verify(row):checked[row['path']]=m.verify(row['path'],row)
verify(dict(path=str(Q/'HANDOFF.json'),bytes=21131,sha256='baff3300c296e43de7f0253cbafe4c7fbf192a9b05a209d5a33ab9cb52949033'))
verify(dict(path=str(I/'HANDOFF.json'),bytes=6016,sha256='bc4cdd39e00c17360b38f5eda3176d98dc7574cd587c215fea9cf5903c1f4db4'))
qh=m.load(Q/'HANDOFF.json');ih=m.load(I/'HANDOFF.json')
for base,handoff,key in [(Q,qh,'payloads'),(I,ih,'files')]:
 rows=handoff[key];assert sorted(p.name for p in base.iterdir())==sorted(['HANDOFF.json']+[Path(r['path']).name for r in rows])
 for row in rows:verify(row)
refs=m.load(Q/'SOURCE_REFERENCES.json');assert len(refs['direct_sources'])==32
for row in refs['direct_sources']:verify(row['identity'])
verdict=m.load(I/'VERDICT.json');assert verdict['blocking_findings']==[] and verdict['recommendation']=='ACCEPT_CONDITIONAL_SIX_ROOT_SUBSTITUTION_AND_COMPLETE_CANONICAL_CAPACITY'
for key in ['literal_admission','literal_check','independent_metadata','reviewed_author_replay']:verify(verdict[key])
before=m.load(old/'RI231_REVIEWER_SIX_ROOT_LITERAL_ADMISSION.json')['identity'];assert m.identity(before['path'])==before
check=m.save('RI231_ROOT_METADATA.json',dict(schema='ri231-root-administrative-custody-v1',status='PASS_SOURCE_REVIEW_SEALS_AND_DIRECT_IDENTITIES',whole_identities=len(checked),subject_files=6,review_files=10,direct_sources=32,direct_bytes=sum(r['identity']['bytes'] for r in refs['direct_sources']),identities=list(checked.values()),scientific_body_decoded=False,mathematical_arithmetic=False,inherited_423_manifest_replayed=False,subject_execution=False))
with (R/'RI231_ROOT_REVIEW.md').open('xb') as out:out.write(Path('/private/tmp/ri232_root_review.md').read_bytes())
decision=m.save('RI231_ROOT_ADJUDICATION.json',dict(schema='ri231-root-native-adjudication-v1',status=verdict['recommendation'],packet=m.ref(Q/'HANDOFF.json'),independent_review=m.ref(I/'HANDOFF.json'),root_manual_review=m.ref(R/'RI231_ROOT_REVIEW.md'),root_metadata=check,complete_proof_reads=['3de623 exit0','572cdc exit0'],accepted=['Six prescribed lambda values and complete alpha/gamma/T substitutions','Complete ten-proper-ideal P row and four neutral component families with all companion capacities','Canonical-only forced tight P row per root sector and exact competing-capacity identity','kappa<=352/41,zeta<=385/2952,F_Y>421/492 for unchanged strict law'],unresolved=['Actual kappa allocations','Full normalized u2=-1 witness or signed inconsistency identity','Improvement,optimality,maximal amplitude'],qualification_credit=0,scientific_execution=False,RET_paused=True))
N=Path(tempfile.mkdtemp(prefix='ri233-native-same-root-contrast-',dir=B))
assignment=m.save('RI233_NATIVE_ASSIGNMENT.json',dict(schema='ri233-native-same-root-contrast-assignment-v1',status='ASSIGNED_AFTER_RI231_ADJUDICATION',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(N),predecessor=decision,predecessor_packet=m.ref(Q/'HANDOFF.json'),source_references=m.ref(Q/'SOURCE_REFERENCES.json'),inherited_assignment=m.ref(old/'RI231_NATIVE_ASSIGNMENT.json'),independent_review=m.ref(I/'HANDOFF.json'),question='Can exact same-root relative-row elimination resolve the full normalized witness obligation without determining the two canonical allocations?',requirements=['Prove for all five actual W5 profiles that explicit kappa terms are record-constant offsets at fixed root bit, preserving all held rows and every labelled occurrence.','Derive division-free pairwise contrast-minor necessary equations from W6. Retain zero-contrast branches and actual reference positivity; do not treat minors as sufficient without proof.','Derive at least one substantive actual held-row contrast consequence using the admitted analytical sources; a generic rewritten determinant alone is not the intended result.','Seek a complete normalized u2=-1 witness or finite signed inconsistency identity. Restore all connected,within-sector,reference and cross-sector rows,all ten unknowns and exact full-slot recovery. If not resolved, prove the strongest justified elimination/compatibility lemma and name the smallest remaining exact premise.','Distinguish a result for the actual fixed canonical law from a relaxation over the allowed kappa range. A relaxed-range counterexample or bounds alone do not decide the actual law or rank.','Keep original rejection,positive family,strict endpoints,rho/s/theta,all canonical corrections,history multiplicities and every protected/executable obligation unchanged.'],source_authority='Inherit only exact previously admitted analytic sources and accepted finite premises named by predecessor SOURCE_REFERENCES; add the accepted RI231 proofs and separate review texts. Use the six accepted values as inherited facts without reopening the scientific body. No new coordinate/body or executable authority.',prohibitions=['No automatic scientific parsing,arithmetic,Fraction/calculator,graph/LP/numerical engine,H/z reconstruction,full coefficient vector or numerical amplitude.','No subject import,compile,AST,probe,run,fixtures,runtime,freeze,mode,protected-file mutation,measurement,RET,repository/Git/index operations.','No successor self-assignment or scope expansion. Return a sealed bounded packet for root adjudication; root immediately chooses the next justified question after review.'],qualification_credit=0,RET_paused=True))
with (R/'adjudicate.py').open('xb') as out:out.write(Path(__file__).read_bytes())
Path('/private/tmp/ri232_root_path.txt').write_text(str(R));print(json.dumps(dict(root=str(R),metadata=check,adjudication=decision,assignment=assignment,next_reservation=str(N))))
