"""Root actual-evidence adjudication and current-E baseline card; no target run."""
from pathlib import Path
import hashlib,importlib.util
D=Path(__file__).parent
hp=D/'publication_helpers.py';assert hashlib.sha256(hp.read_bytes()).hexdigest()=='8b04758d4e19988f67d0d96e86c93a8eb5405704f5b2a3e3d0b401f33afa4277'
s=importlib.util.spec_from_file_location('p',hp);p=importlib.util.module_from_spec(s);s.loader.exec_module(p);m=p.m
R=m.B/'ri186-current-e-capture-independent-68ebm0tu'
m.verify(R/'HANDOFF.json',dict(bytes=4900,sha256='7dd04adab9201a230baba1cff3dbd3a040dd6e92b441e7354d80e734c10c2c83'))
h=m.load(R/'HANDOFF.json');assert sorted(x.name for x in R.iterdir())==h['exclusive_namespace']
for row in h['files']:m.verify(row['path'],row)
v=m.load(R/'VERDICT.json');a=m.load(R/'ADMIN_CHECK.json')
assert v['status']=='ACCEPT_CURRENT_E_METADATA_BASELINE_EVIDENCE' and not v['blocking_findings']
assert a['predicates']==487888 and a['opaque_unique_identities']==12429
rows=m.load(R/'IDENTITIES.json')['identities'];assert len(rows)==12429
for row in rows:assert m.identity(row['path'])==row
print(m.save('RI186_ROOT_FRESH_CHECK.json',dict(schema='ri186-root-fresh-capture-review-check-v1',status='PASS',review=m.ref(R/'HANDOFF.json'),identities=m.ref(R/'IDENTITIES.json'),whole_identities_rehashed=12429,complete_seven_field_state_and_links_equal=True,source_and_namespace_review='Complete reviewer checker and prose read; reconciled with prior independent root monitor/custody replay.',subject_execution=False)))
decision=dict(schema='ri186-root-current-e-baseline-adjudication-v1',status='ACCEPT_EXACT_CURRENT_E_METADATA_BASELINE',review=m.ref(R/'INDEPENDENT_REVIEW.md'),verdict=m.ref(R/'VERDICT.json'),fresh_root_check=m.ref(D/'RI186_ROOT_FRESH_CHECK.json'),prior_root_check=m.ref(D/'ROOT_CAPTURE_CHECK.json'),actual_terminal='5c0651 exit0',review_actual_check='7c9995 exit0; final01925d and seal0891fd exit0',scope='Actual metadata capture only; genuine root tool origin and independent saved observations. Accepted source semantics inherited; reviewer prior bootstrap authorship disclosed.',guard_sequence_clarification='The sealed reviewer closing prose mentions a later 65-guard stage. It does not authorize or require a blanket new65 rerun. The accepted RI170 R01 path-applicability contract governs: nonauthor path-sensitive review decides whether a smallest genuinely required extra control exists. Preserve the sealed review unchanged.',premises=['Stable host/tool/vendor and Apple kernel/loader/shared-cache suppliers.','Saved pid_owner is parent PID, not authenticated child identity; sampled child RSS and accepted no-descendants premise, not hard group quota.','Finite read-window stability is not continuous freeze; source/pyc equivalence and complete dynamic imports are not established.'],scientific_credit=False,profile_or_guard_executed=False,ret_paused=True,next='Separately admitted genuine current-E normal profile, independent review, then separately admitted optimized profile; R01/WHITE/GWOSC/native-forward-map gates remain separate.')
print(m.save('RI186_ROOT_ADJUDICATION.json',decision))
RR=m.B/'ri170-current-e-root-records-proposed-gikj2giy';ad=m.load(RR/'ADMIT_CAPTURE.json');O=Path(ad['output']);c=m.load(O/'COMPLETE.json');outer=m.load(D/'GENUINE_OUTER.json')
assert c['sources']==ad['sources'] and c['first_error'] is None and not c['independent_tail_errors']
assert outer['completion']==m.ref(O/'COMPLETE.json') and outer['command']==c['command'] and outer['environment']==c['environment'] and outer['exit_code']==0
card=dict(schema='ri133-root-preparation-stage-review-v1',status='ACCEPT_NONSCIENTIFIC_PREPARATION_EVIDENCE',stage='baseline',sources=ad['sources'],packet=ad['packet'],environment_root=ad['environment_root'],completions=dict(capture=m.ref(O/'COMPLETE.json')),genuine_outer=dict(capture=m.ref(D/'GENUINE_OUTER.json')),independent_review=m.ref(R/'INDEPENDENT_REVIEW.md'),scientific_execution=False)
assert len(card)==10 and list(card['completions'])==list(card['genuine_outer'])==['capture']
print(m.save(str(RR/'BASELINE_ACCEPTANCE.json'),card))
print(m.save('BASELINE_CARD_CHECK.json',dict(status='PASS_CLOSED_TEN_FIELD_BASELINE_CARD',card=m.ref(RR/'BASELINE_ACCEPTANCE.json'),decision=m.ref(D/'RI186_ROOT_ADJUDICATION.json'),current_e=ad['environment_root'],next_profile_admitted=False,subject_execution=False)))
print(m.save('CAPTURE_PUBLICATION_DISPOSITION.json',dict(baseline_accepted=True,review_reservation=str(R),review_payload_key='files',extra_root_files=['RI186_ROOT_FRESH_CHECK.json','BASELINE_CARD_CHECK.json','accept_capture.py'],table_status='Actual current-E capture independently accepted; root issued exact baseline card after fresh 12429-identity replay.',next='Fresh preflight and separately admitted normal profile, then independent review before optimized; R01 path applicability separate.',readme_decision='RI186 independently accepts current-E metadata baseline evidence after 487,888 administrative predicates and all 12,429 opaque identities. Root reviewed its complete checker and interpretation, rehashed every identity and issued the closed ten-field baseline card. Earlier bootstrap authorship is disclosed; source acceptance is inherited and actual outcomes independently reviewed. Initial reviewer-code failure and successful corrected replay remain. The closing reference to 65 guards does not mandate a blanket rerun: the accepted R01 path-applicability review controls genuinely needed extra tests.\n')))
