import hashlib,importlib.util,tempfile
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri207-root-four-maxima-review-rrel_hre';Q=B/'ri208-native-five-maxima-po8tjwlh'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
H=m.load(Q/'HANDOFF.json');m.verify(Q/'HANDOFF.json',dict(bytes=7875,sha256='f912de523795987606968934907e264d238bd5e074af410a3b3e68034162804f'))
for r in H['payloads']:m.verify(r['path'],r)
meta=m.load(D/'RI208_ROOT_METADATA_CHECK.json');assert meta['status']=='PASS_METADATA_NOT_MATHEMATICAL_EXECUTION' and meta['direct_sources']==14 and meta['selected_references']==28
review=m.load('/private/tmp/ri208_independent_review.json');assert review['status']=='ACCEPT_COMPLETE_FIVE_MAXIMA_CLASS_CONDITIONAL_THEOREM' and review['handoff']==m.ref(Q/'HANDOFF.json')
r=m.save('RI208_NONAUTHOR_REVIEW.json',review)
for src,name in [('/private/tmp/ri208_root_review.md','RI208_ROOT_PROOF_REVIEW.md'),('/private/tmp/ri207_review_ri208.py','review_ri208.py'),(__file__,'adjudicate_ri208.py')]:
 with (D/name).open('xb') as f:f.write(Path(src).read_bytes())
a=m.save('RI208_ROOT_ADJUDICATION.json',dict(schema='ri207-root-ri208-adjudication-v1',status='ACCEPT_COMPLETE_FIVE_MAXIMA_CLASS_CONDITIONAL_THEOREM',handoff=m.ref(Q/'HANDOFF.json'),proof=m.ref(Q/'FIVE_MAXIMA.md'),lemma=m.ref(Q/'HIGH_OMISSION_LEMMA.md'),metadata=m.ref(D/'RI208_ROOT_METADATA_CHECK.json'),root_review=m.ref(D/'RI208_ROOT_PROOF_REVIEW.md'),independent_review=r,theorem=H['theorem'],premises=H['inherited_premises_not_fresh_verification'],whole_class_not_selected_records=True,scientific_execution=False,qualification_credit=False,global_M6_bound_proved=False,actual_W_decided=False,both_margins_or_H30_decided=False,ret_paused=True))
reservation=Path(tempfile.mkdtemp(prefix='ri210-native-six-maxima-',dir=B))
repo=m.REPO
references=[B/'ri185-six-antichain-bound-dd0wfjn0/ANTICHAIN_CLASSIFICATION.md',B/'ri185-six-antichain-bound-dd0wfjn0/SIX_ANTICHAIN_BOUND.md',repo/'docs/track_b/native_six_antichain_bound_v1/root/RI185_ROOT_ADJUDICATION.json',B/'ri199-native-maximum-bound-buxv337k/MAXIMUM_BOUND.md',repo/'docs/track_b/native_maximal_deletion_reduction_v1/root_review/RI199_ROOT_ADJUDICATION.json']
assignment=m.save('RI210_NATIVE_ASSIGNMENT.json',dict(schema='ri210-native-assignment-v1',status='ASSIGNED_AFTER_RI208_INDEPENDENT_ADJUDICATION',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(reservation),predecessor=a,question='Prove or refute the remaining complete six-maxima class U6<=T. Reuse the already accepted RI185 all-mark antichain classification and restoration-only proper A5 law. If that bound closes, explicitly combine the accepted one-through-five classes to justify the global M6<=T comparison and exactly the RI199 weighted-W consequence, keeping stronger conclusions open.',accepted_analytic_references=[m.ref(p) for p in references],justified_starting_points=['Six maxima forces A6; RI185 already supplies all63slots/64records and the exact reduced six-row table. Do not redo its completed classification. Full A5 complements keep record dependence and have no extra theta.','The literal seed has antichain q3(empty)=1/44. A uniform1/110 floor for every factor is unnecessarily weak in the k=0 row. Reconcile the precise seed before using this value, and retain empty-parent1.','Candidate manual estimate from theta<2^-38: in k=0, use p3(empty)>1/64 and p1(empty)>1/2 with numerator probabilities<=1, to obtain u6(empty)<2^36. Check all five other rows and all actual marks/multiplicities independently. This is a suggested route, not preaccepted proof.','One through five maxima now have separate accepted uniform bounds. Only after six-maxima closure prove that finite exhaustive class partition implies the actual global same-law M6 target; then independently check exact strict RI199 implication including equality.'],requirements=['No scientific body/vector/certificate read or automatic proof arithmetic; manual accepted analytic text only. These newly named accepted RI185/RI199 manuscript reads do not expand their opaque historical or runtime dependencies.','Preserve all original marks, full slots, positive theta restoration, fixed canonical corrections and every labeled multiplicity.','No numerical maximizing-parent/actual-scale computation, no claim that W>0 gives both margins or H30. Reconcile remaining obligations and next concrete mathematical dependency.','No new graph/LP/subject/runtime/fixture/card/source execution, Git, repository edits or RET work. Exclusive source-only sealed packet with actual administrative checks and all diagnostics.','Root retains independent adjudication, publication and any successor; stop at the sealed handoff.'],global_bound_or_W_preaccepted=False,ret_paused=True))
print(a);print(assignment);print(reservation)
