from pathlib import Path
import hashlib,importlib.util,json,tempfile
B=Path('/Volumes/AI_DATA/development/det-review-evidence');R=B/'ri234-root-reconciliation-tzop5ais';Q=B/'ri233-native-same-root-contrast-sa2lhrgp';N=B/'ri233-independent-root-transport-review-1d_n8ih1';I=B/'ri234-independent-reconciliation-review-1t1b_0pb';D=B/'ri226-directory-custody-recovery-yvfg_p1b';O=B/'ri226-freeze-reconciliation-operation-yvfg_p1b'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7';s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=R
expected=m.load('/private/tmp/ri234_sealed_measurement_review.json')
for row in expected['handoffs']:m.verify(row['path'],row)
seals=[]
for base in [I]:
 handoff=m.load(base/'HANDOFF.json');rows=handoff['files'];assert sorted(x.name for x in base.iterdir())==sorted(['HANDOFF.json']+[Path(r['path']).name for r in rows])
 observed=[m.identity(base/'HANDOFF.json')]+[m.verify(r['path'],r) for r in rows];seals.append(dict(handoff=m.ref(base/'HANDOFF.json'),identities=observed))
seal=m.save('ROOT_MEASUREMENT_REVIEW_SEAL.json',dict(schema='ri234-final-nonauthor-seals-v1',reviews=seals,root_complete_reads=expected['root_complete_reads']))
v=m.load(I/'VERDICT.json');assert v['blocking_findings']==[] and v['status']=='ACCEPT_ACTUAL_READ_ONLY_RECONCILIATION_CUSTODY_FOR_ROOT_ADJUDICATION' and v['checks']==11709
post=m.load(B/'ri224-root-cwd-review-nyvru347/POST_FAILURE_CUSTODY.json');assert m.identity(post['installed_partial']['path'])==post['installed_partial']
accept=m.save('FROZEN_CUSTODY_ACCEPTANCE.json',dict(schema='ri234-root-current-frozen-custody-acceptance-v1',status='ACCEPT_CURRENT_FROZEN_CUSTODY_BY_READ_ONLY_RECONCILIATION',root=str(B/'ri154-white-execution-proposed-42_uvw15'),operation=m.ref(O/'COMPLETE.json'),frozen_observation=m.ref(O/'FROZEN.json'),genuine_outer=m.ref(R/'GENUINE_OUTER.json'),source_review=m.ref(D/'ROOT_SOURCE_REVIEW.json'),operational_decision=m.ref(R/'ROOT_ONE_RECONCILIATION_DECISION.json'),sameauthor_postcheck=m.ref(D/'RECONCILIATION_POSTCHECK.json'),independent_review=m.ref(I/'HANDOFF.json'),root_actual_check=m.ref(R/'ROOT_ACTUAL_RECONCILIATION_CHECK.json'),root_manual_review=m.ref(R/'ACTUAL_RECONCILIATION_ROOT_REVIEW.md'),final_review_seals=seal,original_complete=m.ref(B/'ri222-freeze-install-operation-ypiy2jqw/COMPLETE.json'),original_status='REFUSED_RETAIN_ALL_PARTIALS',E_written=False,operation_retried=False,all_eight_tails_passed=True,files=49,directories=9,original_limits_unchanged=True,original_installation_retroactively_accepted=False,atomicity_or_power_loss_durability_claim=False,scientific_execution=False,normal_or_optimized_accepted=False,mode_admission_issued=False,RET_paused=True,premises=['Original accepted source/guard/path/runtime applicability and genuine tool origin','Apple supplier/loader/cache/kernel trust and observed read-window stability','No descendants and sampled sole-child RSS scope,not continuous group accounting']))
nextm=Path(tempfile.mkdtemp(prefix='ri236-current-e-normal-preparation-',dir=B))
measurement=m.save('RI236_MEASUREMENT_NEXT_STEP.json',dict(schema='ri236-root-current-e-normal-preparation-v1',status='SELECTED_AFTER_CURRENT_FROZEN_CUSTODY_ACCEPTANCE_NOT_OPERATIONAL_ADMISSION',owner='root coordinator',reservation=str(nextm),predecessor=accept,design_trace=m.ref(R/'NORMAL_MODE_DESIGN_TRACE.json'),next_action='Fresh RI141 capture phase at E/tmp followed by whole accepted-normal-PRE comparison and separate complete frozen E custody; then separately reviewed unchanged RI160 pre_mode and normal-card candidates.',unchanged_sources=True,no_new_wrapper_or_qualification_campaign_indicated=True,baseline=dict(path=str(B/'ri170-current-e-profile-normal-proposed-gikj2giy/PRE.stdout'),bytes=7142026,sha256='ee672c5014d38656e19230bdd10c9831fabf71387e30248e600a8b6d2d8f378e'),requirements=['Fresh full vendor/host/source preflight and exact ten-field E environment','Separate genuine capture authorization and original bounds; new external output only','Both entire current runtime snapshots equal accepted normal PRE, plus full E49/9 and48/124/30 role custody','13-field actual runtime,5-field pre_mode request,9-field pre_mode result and10-field candidate card in acyclic order','Only later separately authorized sole-card insertion may change root directory metadata; retain exact full before/after states,stable device/inode/mode,and every prior file/nonroot directory; no arbitrary extra changes or predicted nlink increment','No scientific normal dispatch before full accepted pre-mode/card/current custody; accepted normal precedes optimized'],capture_not_started=True,mode_card_not_issued=True,scientific_execution=False,RET_paused=True))
print(json.dumps(dict(frozen_acceptance=accept,measurement_next=measurement,measurement_reservation=str(nextm))))
