import hashlib,importlib.util,tempfile
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri206-root-freeze-5e_n5lj_';R=B/'ri207-root-four-maxima-review-rrel_hre';O=B/'ri156-operation-ri206-freeze-5e_n5lj_'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
result=dict(path=str(O/'RESULT.json'),bytes=26214,sha256='9e0c0e4953c7213a76fea291d5f799984422de8628f039eac4e0d7b3c5758b14');complete=dict(path=str(O/'COMPLETE.json'),bytes=176891,sha256='cbc97f695b822fd7ff12ab643d892968a951d7481c297d6fc175612d2f2c6823')
for r in (result,complete):m.verify(r['path'],r)
post=m.load(D/'ACTUAL_FREEZE_POSTCHECK.json');assert post['result']==result and post['complete']==complete and post['all_complete_candidate_fields_matched'] is True and post['all_seven_independent_tails_passed'] is True and post['candidate_acceptances_issued'] is False
review_value=m.load('/private/tmp/ri206_independent_actual_review.json');assert review_value['status']=='PASS_COMPLETE_SAVED_CANDIDATE_AND_CUSTODY' and review_value['result']==result and review_value['complete']==complete
review=m.save('INDEPENDENT_ACTUAL_FREEZE_REVIEW.json',review_value)
with (D/'ROOT_ACTUAL_FREEZE_REVIEW.md').open('xb') as f:f.write(Path('/private/tmp/ri206_actual_review.md').read_bytes())
receipts=m.save('MEASUREMENT_ACTUAL_RECEIPTS.json',dict(schema='ri206-actual-operation-receipts-v1',preparation=m.ref(D/'PREPARATION_ACTUAL_RECEIPTS.json'),source_decision=dict(chunk='de2899',exit_code=0),concrete_review_save=dict(chunk='f6d835',exit_code=0),predispatch=dict(chunk='a65228',exit_code=0),actual=dict(chunk='0c8349',exit_code=0,output='',session_returned=False),genuine=m.ref(D/'GENUINE_TOOL.json'),postcheck=dict(chunk='d2da10',exit_code=0),whole_monitor_read=dict(chunk='f32c4a',exit_code=0),no_retry=True,scientific_execution=False))
accepted=m.save('FREEZE_CANDIDATE_ACCEPTANCE.json',dict(schema='ri206-root-actual-freeze-candidate-adjudication-v1',status='ACCEPT_COMPLETE_ADMINISTRATIVE_FREEZE_CANDIDATE',root_review=m.ref(D/'ROOT_ACTUAL_FREEZE_REVIEW.md'),independent_review=review,source_review=m.ref(D/'ROOT_PREPARATION_DECISION.json'),preflight_review=m.ref(D/'INDEPENDENT_CONCRETE_PREFLIGHT_REVIEW.json'),genuine_outer=m.ref(D/'GENUINE_TOOL.json'),actual_receipts=receipts,postcheck=m.ref(D/'ACTUAL_FREEZE_POSTCHECK.json'),post_custody=m.ref(D/'POST_CUSTODY.json'),result=result,complete=complete,candidate_is_complete_canonical_result=True,candidate_fields=17,run_fields=dict(normal=9,optimized=9),acceptance_scope='Administrative freeze construction over separately accepted source, original guard applicability and complete current profiles. Exact candidate may next be installed only by a separately reviewed exclusive root write and immediate whole E custody.',environment_unchanged=True,scientific_execution=False,freeze_installed=False,mode_admission_issued=False,ret_paused=True))
next_action=m.save('MEASUREMENT_NEXT_ACTION.json',dict(schema='ri206-next-measurement-action-v1',status='ROOT_OWNED_NEXT_BOUNDED_ACTION',candidate_acceptance=accepted,action='exclusive_freeze_installation_and_complete_frozen_observation',requirements=['exact accepted RESULT bytes to literal E/AUTHORIZED_FREEZE.json by bounded exclusive creation; retain partials, fsync and independently reread','all48 original E files retain full identities; exactly49files/nine dirs afterward with only expected E-root directory change, empty tmp/runs and no mode cards','independent tail checks and full ri156-complete-copy-card-observation-v1 frozen object, original48 pairs/124history/30targets; every receipt outside E','root independent review and acceptance of actual installation before fresh normal-mode runtime custody','new-E normal PRE baseline, genuine RI141 collector under exact E environment, full non-null dyld/supplier brackets,13-field actual runtime record, existing pre_mode contract','actual normal execution and acceptance before optimized'],later_obligations=['WHITE15/W09','both179controls','27/13/30records','57artifacts','74postchecks','three trees','RI131/full32','selected public GWOSC conventional reproduction'],no_missing_user_decision=True,scientific_execution_authorized=False,calibration_or_native_forward_map_claimed=False,ret_paused=True))
reservation=Path(tempfile.mkdtemp(prefix='ri209-freeze-installation-',dir=B));(reservation/'worker_proposal').mkdir()
m.D=R
assignment=m.save('RI209_MEASUREMENT_ASSIGNMENT.json',dict(schema='ri209-measurement-assignment-v1',status='ASSIGNED_AFTER_RI206_INDEPENDENT_ADJUDICATION',owner='/root/ri116_complete_caller_review',reservation=str(reservation/'worker_proposal'),predecessor=accepted,next_action=next_action,scope='Source-only proposal for exact exclusive installation and complete frozen observation/postcheck. No execution, admission, candidate rewrite, E mutation or Git by worker.',requirements=['Use actual accepted26214-byte RESULT with exact9e0c0e4953c7213a76fea291d5f799984422de8628f039eac4e0d7b3c5758b14 pin','Read literal RI160 observe/custody contract; all9 frozen-observation fields,48copy/124history/30original roles and whole sorted E tree retained','Independent tails preserve first and later failures; candidate/source/acceptance dependencies and before/after source identities stay exact; single exclusive no-retry write','Root owns admission/execution/independent review, custody acceptance, later per-mode observations and Git','Prior authorship disclosed; sealed exact source packet and full source deltas/metadata evidence; no new scientific launcher or restart of completedqualification'],ret_paused=True))
m.D=D
with (D/'ri206_adjudicate_freeze.py').open('xb') as f:f.write(Path(__file__).read_bytes())
print(accepted);print(assignment);print(reservation)
