import hashlib, importlib.util
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence'); D=B/'ri206-root-freeze-5e_n5lj_';W=D/'worker_proposal'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';b=h.read_bytes();assert len(b)==3144 and hashlib.sha256(b).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
hr=m.verify(W/'HANDOFF.json',dict(bytes=5204,sha256='c79768e5bf074c1df6e6c4161db1382635ec4c852c78426ad24d7b567ae0e51d'));v=m.load(W/'HANDOFF.json')
assert sorted(p.name for p in W.iterdir())==v['namespace'] and len(v['payloads'])==11
for r in v['payloads']:m.verify(r['path'],r)
assert sorted(p.name for p in D.iterdir())==['worker_proposal']
review=m.save('INDEPENDENT_PREPARATION_REVIEW.json',dict(schema='ri206-independent-source-review-transcript-v1',status='NO_BLOCKING_DEFECT_IN_SEALED_OPERATION_PROPOSAL',reviewer='/root/archive_repro_review',handoff=m.ref(W/'HANDOFF.json'),payloads=v['payloads'],scope='Complete three operational scripts, notes, full source diff, source references and retained consumer. All17 candidate fields, four evidence references, nine fields per mode, complete canonical RESULT and all7 tails reviewed. No proposal or subject execution.',independent_checks=[dict(chunk='4b5bba',exit_code=0,exact_seal=True),dict(chunk='6c3294',exit_code=0,predicates=4008,distinct_pins=771,required_consumer_references=153,prior_source_rows=722,historical_role_rows=810,dependencies=567,complete_diff_equal=True)],prospective_bootstrap=dict(bytes=2401,sha256='ddc3b0f906130d036777250055bf1cc088c194dd888c76a4f9a20d9add54e319'),source_reads=['969fce','2dde4c','f5a5f5','413152','97f117','e400dd','f4fa43'],diagnostics=['Combined source display clipped; missing text recovered by f4fa43 exit0. No failed administrative checks.'],checker_provenance='Inline administrative tool command; no saved checker path. Actual source and output in6c3294.',prior_authorship='RI130/RI141 and prior review involvement, not RI206 author. Earlier accepted semantics inherited, not newly self-approved.',candidate_acceptance=False,ret_paused=True,premises=['genuine external tool origin','fresh operational custody','stable supplier/host/cache and read-window','no descendants','sampled child RSS, not continuous/group quota']))
print(m.save('ROOT_PREPARATION_DECISION.json',dict(schema='ri206-root-preparation-decision-v1',status='ACCEPT_SEALED_SOURCE_FOR_ONE_FRESH_PREPARATION',handoff=m.ref(W/'HANDOFF.json'),payloads=v['payloads'],independent_review=review,root_source_reads=['5fbb2c','343c5d','250495','32493a'],manual_review='Root read complete prepare/predispatch/postcheck operational sources and notes; reconciled full retained static/source-admission contract, both exact9-field run maps and bindings.freeze_record. All17 fields, original65 guards, accepted profiles, runtime sidecars, all30 sources/11helpers, full custody/tails and exact dispatch boundaries retained. No blocker.',author_check=v['actual_author_check'],author_prior_RI160_authorship_disclosed=True,operation='One prospective administrative freeze-candidate construction; root separately reviews concrete prepared dispatch before launch.',execute_only_at_original_worker_path=True,candidate_acceptance=False,freeze_installed=False,mode_admission=False,scientific_execution=False,ret_paused=True)))
