"""Record independent source refusal, a narrow repair assignment, and literal analytic access."""
from pathlib import Path
import hashlib,importlib.util,tempfile
B=Path('/Volumes/AI_DATA/development/det-review-evidence')
hp=B/'ri122-root-execution-review-6whn_vky/metadata.py';b=hp.read_bytes()
assert len(b)==3144 and hashlib.sha256(b).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',hp);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
D=Path(tempfile.mkdtemp(prefix='ri214-root-installation-review-',dir=B));m.D=D
entry=m.snapshot();assert entry['head']=='c1cb37d0c70c899a3d9648cbb91a8620ead60757' and entry['branch']=='ret' and entry['upstream']=='origin/ret' and entry['index']==''
print(m.save('REPO_ENTRY.json',entry))
W=B/'ri209-freeze-installation-b3bokxbe/worker_proposal';h=m.load(W/'HANDOFF.json')
assert m.pure(m.ref(W/'HANDOFF.json'))==dict(bytes=6621,sha256='b507c85ff8d4fbe37093854376c71de5de293dfeea3308c6236a1de48e2260df')
assert sorted(p.name for p in W.iterdir())==sorted(h['namespace'])
for r in h['files']:m.verify(r['path'],r)
E=B/'ri154-white-execution-proposed-42_uvw15'
assert not (E/'AUTHORIZED_FREEZE.json').exists() and not (B/'ri209-freeze-install-operation-b3bokxbe').exists()
ef=[m.identity(p) for p in sorted(E.rglob('*')) if p.is_file()]
ed=[str(p) for p in sorted(E.rglob('*')) if p.is_dir()]
assert len(ef)==48 and len(ed)==9
m.save('MEASUREMENT_BOUNDARY.json',dict(E=str(E),files=ef,subdirectories=ed,freeze_absent=True,RI209_operation_absent=True,mode_cards_issued=False))
review=dict(schema='ri214-ri209-nonauthor-source-review-v1',status='REPAIR_REQUIRED_NO_OPERATIONAL_ADMISSION',reviewer='/root/archive_repro_review',prior_authorship='Reviewer authored earlier RI130/RI141 material, not RI209; accepted inherited semantics are not claimed newly independent.',record_kind='Root-preserved complete substantive findings from independent collaboration report; original report remains in transcript',handoff=m.ref(W/'HANDOFF.json'),installer=m.ref(W/'install_freeze.py'),postchecker=m.ref(W/'check_installation.py'),
 findings=[dict(lines=[146,157],issue='Successful OUT.mkdir owns attempt; initial time.monotonic and safe-state initialization occur before protected try. A clock exception bypasses all eight tails and completion.',repair='Initialize safe state before ownership and protect the first fallible step after successful mkdir.'),dict(lines=[205,210],issue='Final elapsed-time call is unprotected. Its exception skips COMPLETE and can obscure earlier first/tail errors retained only in memory.',repair='Preserve first error, record timing failure separately, and attempt refused COMPLETE without inventing valid elapsed time.')],
 remainder='No additional blocker found in exclusive directory-relative destination creation, descriptor cleanup, fsync/reread, partial preservation, complete frozen observation, unchanged 48-file custody, eight independent tails or same-author postchecker complete reconstruction. Success path keeps original monitor/bounds and external genuine-evidence prerequisites. These paths were not executed.',
 administrative_replay=dict(chunk_id='66c76b',exit_code=0,predicates=4339,distinct_opaque_identities=821,input_pins=806,historical_rows=810,predecessor_sources=764,named_roles=20,namespace_files=15,payloads=14,installer_lines=212,postchecker_lines=135,copy_pairs=48,history_pairs=124,originals=30),
 reviewer_diagnostics=[dict(chunk_id='75d26d',exit_code=1,cause='Reviewer checker omitted legitimate import re addition in retained author matcher repair; corrected checker passed.'),dict(chunk_id='17d221',exit_code=1,cause='Expected diff status: exact import re addition and matcher replacement confirmed.')],
 other_reads=[dict(chunk_id=x,exit_code=0) for x in ['502124','25f4a8','1df688','7f7099','0fba6a','06b6e6']],
 author_diagnostic_preserved='5325f0 author matcher failure and corrected4df72a admin check remain; neither is qualification.',proposal_execution=False,proposal_import_compile_AST=False,scientific_execution=False,E_write=False,admission_issued=False,git_operations=False)
m.save('RI209_NONAUTHOR_REVIEW.json',review)
m.save('RI209_ROOT_SOURCE_DECISION.json',dict(schema='ri214-ri209-root-source-decision-v1',status='REVISE_SOURCE_ONLY_WITHOUT_EXECUTION',handoff=m.ref(W/'HANDOFF.json'),source_manifest=m.ref(W/'SOURCE_PINS.json'),independent_review=m.ref(D/'RI209_NONAUTHOR_REVIEW.json'),boundary=m.ref(D/'MEASUREMENT_BOUNDARY.json'),root_complete_reads=[dict(chunk_id=x,exit_code=0) for x in ['535105','3612fe','df350b','ccddd5']],display_recovery='Tiny postchecker header clipping in3612fe recovereddf350b; full protocol/installer/postchecker read.',accepted_findings=review['findings'],source_namespace_verified=15,payloads_verified=14,admission_issued=False,operation_attempted=False,RI206_candidate_acceptance_unchanged=True,original_RI209_sealed=True,required_next='Fresh source-only repair, then fresh independent/root source review; actual admission/execution remain separate.',qualification_credit=False,RET_paused=True))
R=Path(tempfile.mkdtemp(prefix='ri213-freeze-clock-repair-',dir=B));(R/'worker_proposal').mkdir()
m.save('RI213_REPAIR_ASSIGNMENT.json',dict(schema='ri213-freeze-installation-clock-repair-v1',status='ASSIGNED_AFTER_INDEPENDENT_RI209_SOURCE_REFUSAL',owner='/root/ri116_complete_caller_review',reservation=str(R/'worker_proposal'),predecessor=m.ref(D/'RI209_ROOT_SOURCE_DECISION.json'),source_handoff=m.ref(W/'HANDOFF.json'),question='Repair both admitted clock-failure gaps while preserving complete first/later error evidence and all independent tail attempts. Keep the original successful installation semantics and whole postchecker reconstruction.',requirements=['Use fresh reservation only; sealed RI209 and all prior diagnostics remain immutable. Root owns Git/index, admission, runtime execution and acceptance.', 'Move safe initialization before attempt ownership and put the initial clock inside protected handling. Any clock failure after successful mkdir must reach the eight independent tail attempts and refused completion attempt.', 'Catch final clock/elapsed acquisition failure; retain earlier first error and separately represent missing/invalid elapsed rather than fabricate a successful duration. Preserve terminal write failure as genuine outer/partial evidence.', 'Reconcile postchecker and protocol with explicit timing failure records, keeping successful elapsed validation and unchanged 180s/524288KiB monitor bounds, sampling limits and no-descendants premise.', 'Do not redesign the monitor/launcher, change candidate bytes, widen source/runtime scope, touch E, create admissions/cards, or execute/import/compile/AST/probe the proposal/monitor/vendor. No scientific bodies or computation; no new qualification campaign.', 'Preserve all48copy/124history/30original mappings,810roles,764sources,806pins, exact exclusive directory-relative write, fsync/reread and partial retention. Refresh only dependencies changed by this source repair with explicit path provenance.', 'Supply exact predecessor-to-repair diff, full source/protocol/postchecker, administrative checks with actual diagnostics and receipts, namespace and source pins for fresh independent review. Source-only branch reasoning is not executable qualification.'],proposed_operation_must_remain_absent=True,qualification_credit=False,RET_paused=True))
old=B/'ri211-root-global-W-review-xh6eetn1'
source=m.REPO/'docs/track_b/native_endpoint_certificate_v1/source/ENDPOINT_CERTIFICATE.md'
original=B/'ri187-same-law-endpoint-certificate-fh41wfew/ENDPOINT_CERTIFICATE.md'
assert source.read_bytes()==original.read_bytes()
inv=m.load(B/'ri197-manual-original-pair-proof-dh668vz_/SOURCE_DEPENDENCIES.json')
ref=m.ref(source);matches=[r for r in inv['protected_files'] if m.pure(r['identity'])==m.pure(ref)]
assert matches and all(r['classification']=='analytic-source-text-or-review' for r in matches)
m.save('RI212_LITERAL_COMPLEMENT_ADMISSION.json',dict(schema='ri212-literal-complement-admission-v1',status='ADMIT_ONE_EXISTING_ANALYTIC_TEXT_FOR_SAME_LAW_SEED_SIGN',assignment=m.ref(old/'RI212_NATIVE_ASSIGNMENT.json'),previous_admission=m.ref(old/'RI212_LITERAL_SEED_RELATION_ADMISSION.json'),reference=ref,original=m.ref(original),inherited_matches=matches,request='Worker seeks complete H5 complement and c_i/j_i contrast identities to analyze original seed determinant K*h=A, preserving zero determinant branch.',scope='Read the entire named RI187 ENDPOINT_CERTIFICATE.md literally. Equation3 retains complete C4/C3 rows and both H5 one-cap occurrences: j_i=1-theta*K_i. Combine original same-law identities manually with admitted seed equations. No automatic typed-reference expansion or descendant read authority.',root_reads=[dict(chunk_id='650c12',exit_code=0,scope='Complete RI120 F3_ANALYTIC_CHECK, insufficient alone for requested full complement'),dict(chunk_id='f44744',exit_code=0,scope='Complete RI187 ENDPOINT_CERTIFICATE')],not_preaccepted='Worker B3 slack, determinant and local interval claims await complete sealed proof and independent review. RI187 historical unresolved endpoint claims remain historical; RI210 actual positive weighted result is current.',new_execution_authority=False,scientific_body_read=False,H_or_z_numerical_reconstruction=False,automatic_proof_arithmetic=False,typed_reference_expansion=False,RET_paused=True))
with (D/'record_followthrough.py').open('xb') as f:f.write(Path(__file__).read_bytes())
print(dict(root=str(D),repair=str(R/'worker_proposal'),decision=m.ref(D/'RI209_ROOT_SOURCE_DECISION.json'),assignment=m.ref(D/'RI213_REPAIR_ASSIGNMENT.json'),admission=m.ref(D/'RI212_LITERAL_COMPLEMENT_ADMISSION.json')))
