"""Root decisions for independently reviewed bounded proof and inert outcomes."""
from pathlib import Path
import hashlib,importlib.util,tempfile
D=Path(__file__).resolve().parent;H=D.parent/'ri122-root-execution-review-6whn_vky/metadata.py';b=H.read_bytes();assert len(b)==3144 and hashlib.sha256(b).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',H);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
S=m.B/'ri166-native-contrast-gap-2j9ykuoq';R=m.B/'ri162-independent-outcome-review-s6xrt59o';Q=m.B/'ri162-inert106-root-records-proposed-wb69vu5s';replay=D/'measurement_replay'
rv=m.load(R/'INDEPENDENT_OUTCOME_REVIEW.json');old=m.load(R/'CHECK_RESULT.json');new=m.load(replay/'CHECK_RESULT.json')
for key in old:
 if key not in ('finite_checker','completed_at_unix_ns'):assert old[key]==new[key],key
assert new['controls']==106 and new['checks']==232815 and m.load(replay/'SUPPLEMENT_RESULT.json')['checks']==89
n=m.save('RI166_ROOT_ADJUDICATION.json',dict(schema='ri166-independent-root-proof-adjudication-v1',status='ACCEPT_EXACT_REDUCTIONS_COMPONENT_SEPARATION_AND_ENUMERATED_RELAXATION_COUNTEREXAMPLE',subject=m.ref(S/'HANDOFF.json'),manual_review=m.ref(D/'ROOT_PROOF_REVIEW.md'),metadata=m.ref(D/'ROOT_METADATA_RECHECK.json'),root_check=dict(chunk='5830bf',exit_code=0,historical_paths=252,current_paths=8,inherited_rows=223),full_native_bound='UNRESOLVED',full_native_counterexample=False,actual_vector_read=False,scientific_execution=False,qualification_admission=False,physical_claim=False,ret_paused=True))
q=m.save('RI162_OUTCOME_ROOT_ADJUDICATION.json',dict(schema='ri162-root-inert106-outcome-adjudication-v1',status='ACCEPT_ONE_GENUINE_INERT_METADATA_QUALIFICATION',independent_review=m.ref(R/'INDEPENDENT_OUTCOME_REVIEW.json'),actual_summary=m.ref(Q/'ACTUAL_RUN_SUMMARY.json'),genuine_initial=m.ref(Q/'GENUINE_INITIAL_TOOL.json'),genuine_terminal=m.ref(Q/'GENUINE_TERMINAL_TOOL.json'),original_source_acceptance=rv['subject']['source_adjudication'],source_manifest=rv['subject']['source_manifest'],accepted_action='controls',accepted_controls=106,new_target_runs_this_review=0,root_replay=dict(source_exact_copies=True,full_result_equal_except_checker_location_and_timestamp=True,main=m.ref(replay/'CHECK_RESULT.json'),main_tool=dict(chunk='4bf10c',exit_code=0,saved_result_predicates=232815,terminal_predicates_after_evidence_and_checker_hashes=232833),supplement=m.ref(replay/'SUPPLEMENT_RESULT.json'),supplement_tool=dict(chunk='423834',exit_code=0,predicates=89)),source_count='582 observations, 581 distinct paths; SOURCE_SET separately pinned and freshly checked through both preflight and actual source tail',all_nine_tails_error_null=True,complete_external_custody=True,actual_occurrence=rv['actual_occurrence'],inherited_premises=rv['inherited_premises'],limits=rv['limits_of_acceptance'],review_diagnostics=rv['preserved_review_diagnostics'],next_action='Bind current-E capture, baseline and profile applicability under a fresh scoped root preflight; then preserve separate actual R01, genuine normal-before-optimized WHITE15 and independent arithmetic acceptance. This outcome decision alone authorizes no additional dispatch.',scientific_qualification_accepted=False,actual_data_admitted=False,ret_paused=True))
W=Path(tempfile.mkdtemp(prefix='ri168-terminal-row-coupling-',dir=m.B))
a=m.save('RI168_NATIVE_ASSIGNMENT.json',dict(schema='ri168-root-terminal-component-row-coupling-assignment-v1',owner_thread='01a074c4-4b09-76a3-8cb2-0caf116f6b9c',reservation=str(W),predecessor=n,question='Determine the complete native marked-row incidence and resulting coupling inequalities for the six C4 components distinguished by RI166, using their terminal orders and every possible maximal-deletion presentation. Can those additional row constraints prove the three reverse-bound halfspaces, or which exact residual cross-row constraint remains?',deliverables=['Explicit finite terminal/deletion-role table for all six selected components, preserving every retained mark, forgotten mark, raw diamond identification and labeled ideal multiplicity; establish completeness or precisely delimit any unresolved incidence.','Derive the complete corresponding row terms from the fixed RI36 prefix and RI41 potential rule; include the alternative parents for masks 1 and 3, not only the two C4 rows. Treat every other component as the same global variable wherever it reappears.','Use those coupled constraints to prove a nontrivial bound on the marked contrasts relative to d7, or identify an exact obstruction with all assumptions stated. A reduced model cannot become a full-law counterexample by relabeling. Do not merely repeat RI166 normalization or introduce an unsupported mark-flip symmetry.','Concise proof and immutable administrative source/provenance/check handoff for independent root review.'],allowed='Source-only literal reading and manual mathematics; administrative identities using Homebrew Python or Node. No selected vendor, target import/compile/AST, scientific JSON decoding, numerical/symbolic engine, graph execution, fixtures or new agents.',preserve=['Actual fixed109-vector remains unread pending qualification/QP04; no replacement witness or grid premise.','RI167 supervisor repair remains separate, completed author source awaiting root review; do not duplicate it.','Full-law coefficient ordering, same-law M5/canonical construction, global M6/rho, actual capacity, joint q/v, W/C2/C3/shared H30 and physical claims remain distinct.','P2/P3, Y=1/4, 31/139/20/42 obligations, shared T1, other eight parents, all five Di, strict endpoints and all labeled ideal multiplicities.','RET paused; measurement separate; root owns all Git/index, repository docs and execution admissions.'],stop='Seal bounded result and hand back for review; root selects next justified task.'))
print(n);print(q);print(a)
