"""Independent actual preparation metadata/custody only. Never runs subjects.
Only authenticated root metadata.identity/canonical primitives are imported.
Candidate and all scientific files are opaque hash/byte reads, never JSON loads.
"""
from pathlib import Path
import hashlib,json,os,stat,shlex,importlib.util
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri226-directory-custody-recovery-yvfg_p1b';W=D/'worker_proposal';PW=B/'ri229-reconciliation-preparation-t93t1607/worker_proposal';T=B/'ri230-root-lower-combinations-review-v9mxbmtc';R=B/'ri230-independent-concrete-preparation-yehbzc6e';E=B/'ri154-white-execution-proposed-42_uvw15';O=B/'ri226-freeze-reconciliation-operation-yvfg_p1b'
H=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=H.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('ri230_review_metadata',H);m=importlib.util.module_from_spec(s);s.loader.exec_module(m)
labels=[];seen={}
def ck(ok,label):
 labels.append(label)
 if not ok:raise ValueError(label)
def eq(a,b,label):ck(m.canonical(a)==m.canonical(b),label)
def identity(path):
 p=str(path)
 if p not in seen:seen[p]=m.identity(p)
 return seen[p]
def pin(path):return {k:identity(path)[k] for k in ('path','bytes','sha256')}
def verify(ref):eq(pin(ref['path']),{k:ref[k] for k in ('path','bytes','sha256')},'opaque pin '+ref['path'])
def load(path):
 p=Path(path);before=identity(p);data=p.read_bytes();eq(m.pin(data),m.pure(before),'whole administrative bytes '+str(p))
 def pairs(rows):
  out={}
  for key,value in rows:
   if key in out:raise ValueError('duplicate metadata key')
   out[key]=value
  return out
 return json.loads(data,object_pairs_hook=pairs,parse_constant=lambda x:(_ for _ in ()).throw(ValueError(x)))
def state(p):
 a=Path(p).lstat();return [a.st_dev,a.st_ino,a.st_mode,a.st_nlink,a.st_size,a.st_mtime_ns,a.st_ctime_ns]
def observed_rows(rows,label):
 for row in rows:eq(identity(row['path']),row,'entire actual '+label+' '+row['path'])
outputs=['HOST_GENUINE_TOOL.json','HOST_BEFORE.json','RECONCILE_BOOTSTRAP.py','SOURCES_BEFORE.json','SUPPLIER_BEFORE.json','E_BEFORE.json','RECONCILE_PREFLIGHT.json','RECONCILIATION_PROPOSAL.json','PREPARATION_CUSTODY.json']
for name in outputs:
 a=identity(D/name);ck(a['resolved_path']==str(D/name) and a['symlink_chain']==[] and a['state'][3]==1 and a['bytes']<=67108864,'regular literal single-link output '+name)
 if name!='RECONCILE_BOOTSTRAP.py':ck((D/name).read_bytes()==m.canonical(load(D/name)),'entire canonical output '+name)
for n,size,sha in [('GENUINE_PREPARATION_TOOL.json',3113,'afe45fc3982de98e7bde448fe9be75974d273da2f91eee3e6bbb1b64e27a97d1'),('RI229_PREPARATION_SOURCE_ACCEPTANCE.json',2356,'149af89b6d5a7a09c7efb56f2910d272c7f48f6df049da6c40d57268cf697646'),('ROOT_ONE_PREPARATION_DECISION.json',4234,'25fdd96a229961cfd6ed32d232687b5ad5449f25c1dfa9eb584d5aba6a5a0514')]:verify(dict(path=str(T/n),bytes=size,sha256=sha))
c=load(D/'PREPARATION_CUSTODY.json');pre=load(D/'RECONCILE_PREFLIGHT.json');proposal=load(D/'RECONCILIATION_PROPOSAL.json');sources=load(D/'SOURCES_BEFORE.json');supplier=load(D/'SUPPLIER_BEFORE.json');etree=load(D/'E_BEFORE.json');host=load(D/'HOST_BEFORE.json');copyhost=load(D/'HOST_GENUINE_TOOL.json');originalhost=load(T/'GENUINE_PREPARATION_HOST_TOOL.json');root=load(T/'ROOT_ONE_PREPARATION_DECISION.json');decision=load(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json');genuine=load(T/'GENUINE_PREPARATION_TOOL.json')
manifest=load(W/'SOURCE_PINS.json');prepmanifest=load(PW/'SOURCE_PINS.json');rh=load(W/'HANDOFF.json');ph=load(PW/'HANDOFF.json');review=load(D/'ROOT_SOURCE_REVIEW.json');deps=load(PW/'DEPENDENCIES.json');base=load(W/'INPUT_PINS.json');repair=load(W/'REPAIR_PROVENANCE.json');build=load(PW/'BUILD_METADATA.json');g=load(base['roles']['graph']['path']);history=load(base['roles']['historical_supplier']['path']);oldbefore=load(repair['roles']['original_before']['path']);oldobs=load(repair['roles']['original_observations']['path']);oldcomplete=load(repair['roles']['original_complete']['path']);oldpost=load(repair['roles']['postflight']['path']);oldsources=load(repair['roles']['original_sources']['path'])
for directory,handoff in [(W,rh),(PW,ph)]:
 eq(sorted(p.name for p in directory.iterdir()),sorted(handoff['namespace']),'complete unchanged source namespace '+str(directory))
 for row in handoff['files']:verify(row)
for row in manifest['files']+prepmanifest['files']+deps['files']:verify(row)
eq(decision['status'],'ACCEPT_RI229_PREPARATION_SOURCE_ONLY','source-only acceptance');eq(decision['source_manifest'],pin(PW/'SOURCE_PINS.json'),'accepted preparation manifest');eq(decision['recovery_source_review'],pin(D/'ROOT_SOURCE_REVIEW.json'),'accepted recovery decision');eq(decision['packet'],pin(PW/'HANDOFF.json'),'accepted complete preparation packet')
for key in ('independent_review','root_manual_review','root_metadata'):verify(decision[key])
eq(root['status'],'AUTHORIZE_ONE_ADMINISTRATIVE_PREPARATION_ONLY','actual preparation authority only');eq(root['source_review'],pin(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),'one-operation source acceptance');eq(root['source_manifest'],pin(PW/'SOURCE_PINS.json'),'one-operation manifest');eq(root['host'],pin(T/'GENUINE_PREPARATION_HOST_TOOL.json'),'genuine host pin');observed_rows([root['administrative_interpreter'],root['writer']],'root administrative startup binding');eq(root['observed_flags'],dict(isolated=1,dont_write_bytecode=1,optimize=0),'administrative flags');eq([root[k] for k in ['one_attempt','E_write','reconciliation_admitted','reconciliation_dispatched','mode_authority','scientific_execution','qualification_credit','RET_paused']],[True,False,False,False,False,False,0,True],'complete authority scope')
command=['/opt/homebrew/bin/python3','-I','-B',str(PW/'prepare_reconciliation.py'),'--preparation-manifest-bytes',str(pin(PW/'SOURCE_PINS.json')['bytes']),'--preparation-manifest-sha256',pin(PW/'SOURCE_PINS.json')['sha256'],'--preparation-review',str(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),'--preparation-review-bytes',str(root['source_review']['bytes']),'--preparation-review-sha256',root['source_review']['sha256'],'--host-transcript',str(T/'GENUINE_PREPARATION_HOST_TOOL.json'),'--host-transcript-bytes',str(root['host']['bytes']),'--host-transcript-sha256',root['host']['sha256']]
eq(root['command'],command,'entire independently reconstructed preparation argv');args=genuine['initial']['arguments'];eq({k:args[k] for k in ['cmd','workdir','login','yield_time_ms','max_output_tokens']},dict(cmd=shlex.join(command),workdir=str(D),login=False,yield_time_ms=1000,max_output_tokens=4000),'actual preparation command/cwd/flags/transport');ck(set(args)=={'cmd','workdir','login','sandbox_permissions','justification','yield_time_ms','max_output_tokens'},'complete preserved transport argument schema');eq(genuine['initial']['result']['chunk_id'],'0f12a4','actual initial receipt');eq(genuine['initial']['result']['session_id'],16198,'actual initial session');eq(genuine['initial']['result']['output'],'','initial empty output');ck(genuine['initial']['result'].get('exit_code') is None,'initial pending');eq([genuine['terminal']['chunk_id'],genuine['terminal']['exit_code']],['1db8d4',0],'actual final result');ck('session_id' not in genuine['terminal'],'genuine terminal no pending session')
eq(copyhost,originalhost,'entire host canonical copy preserves original value');ck(set(copyhost)=={'schema','arguments','result','observation'},'host record fields')
eq(copyhost['schema'],'ri229-root-genuine-host-tool-transcript-v1','genuine host schema');eq([copyhost['result']['chunk_id'],copyhost['result']['exit_code']],['ff059f',0],'actual host receipt');eq(json.loads(copyhost['result']['output']),copyhost['observation'],'whole real host stdout');obs=copyhost['observation'];eq(obs,dict(command=history['host']['argv'],environment={'PATH':'/usr/bin:/bin','LC_ALL':'C'},returncode=0,stdout=history['host']['stdout'],stderr='',uname=history['host']['uname']),'complete host observation');eq(host,dict(schema='ri209-root-host-command-record-v1',**obs,genuine_tool=pin(D/'HOST_GENUINE_TOOL.json')),'all eight host fields')
VENDOR='/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/bin/python3.9';ENV=dict(LC_ALL='C',MKL_NUM_THREADS='1',NUMEXPR_NUM_THREADS='1',OMP_NUM_THREADS='1',OPENBLAS_NUM_THREADS='1',PATH='/usr/bin:/bin',TMPDIR=str(D/'tmp'),TZ='UTC',VECLIB_MAXIMUM_THREADS='1',__CF_USER_TEXT_ENCODING='0x1F5:0x0:0x0');LIMITS=dict(wall_seconds=180,rss_kib=524288,target_poll_seconds=.025,maximum_sample_gap_seconds=.1,ps_timeout_seconds=.05,file_bytes=67108864)
expected_refs={}
for row in base['files']+repair['files']+manifest['files']+[pin(W/'SOURCE_PINS.json'),pin(D/'ROOT_SOURCE_REVIEW.json'),pin(D/'RECONCILE_BOOTSTRAP.py')]:
 ck(row['path'] not in expected_refs or expected_refs[row['path']]==row,'unambiguous source ref');expected_refs[row['path']]=row
eq(len(expected_refs),971,'entire971 source domain');eq([v['path'] for v in sources],sorted(expected_refs),'whole sorted source domain');observed_rows(sources,'current source')
for row in sources:eq({k:row[k] for k in ('path','bytes','sha256')},expected_refs[row['path']],'entire source FilePin')
eq(len(oldsources),904,'original904 count');observed_rows(oldsources,'old source');observed_rows(list(oldbefore['bindings'].values()),'old control binding');eq(oldsources,oldbefore['source_observations'],'whole old source baseline');eq(oldobs['sources_actual'],oldsources,'whole old source tail');eq(oldobs['binding_actual'],oldbefore['bindings'],'whole old binding tail');eq(oldcomplete['status'],'REFUSED_RETAIN_ALL_PARTIALS','old refusal immutable');eq(oldcomplete['first_error'],dict(type='ValueError',message='RI209: root device inode mode links',secondary=[]),'old first error immutable');eq(sorted(p.name for p in Path(repair['roles']['original_complete']['path']).parent.iterdir()),['ATTEMPT.json','BEFORE.json','COMPLETE.json','OBSERVATIONS.json'],'whole old failed operation namespace')
for row in oldpost['operation_files']:verify(row)
eq({k:v for k,v in supplier.items() if k not in ('environment','observed_at_unix_ns')},{k:v for k,v in history.items() if k not in ('environment','observed_at_unix_ns')},'entire inherited supplier shape');eq(supplier['environment'],ENV,'whole supplier environment');ck(type(supplier['observed_at_unix_ns']) is int and supplier['observed_at_unix_ns']>2**53,'integer current recorded observation time');eq([len(supplier['vendor']),sum(v['bytes'] for v in supplier['vendor']),len(supplier['tools']),len(supplier['namespace']),len(supplier['absent'])],[1810,48024515,4,195,2],'complete supplier counts');observed_rows(supplier['vendor']+supplier['tools'],'supplier file')
for row in supplier['namespace']:
 p=Path(row['path']);v=dict(path=str(p),kind=row['kind'],state=state(p))
 if row['kind']=='directory':v['entries']=sorted(x.name for x in p.iterdir())
 else:v['target']=os.readlink(p)
 eq(v,row,'entire fresh supplier namespace '+str(p));eq(state(p),v['state'],'supplier namespace stable')
for p in supplier['absent']:ck(not os.path.lexists(p),'required supplier absence '+p)
eq(list(os.uname()),obs['uname'],'current uname matches genuine host')
# Full read-only E tree without scientific decode.
live=[];stack=[(E,0)];total=0
while stack:
 p,depth=stack.pop();a=state(p);ck(depth<=16 and len(live)<25000 and not p.is_symlink(),'bounded ordinary E entry');row=dict(relative=str(p.relative_to(E)),state=a)
 if stat.S_ISDIR(a[2]):row.update(kind='directory',entries=sorted(x.name for x in p.iterdir()));stack.extend((p/n,depth+1) for n in reversed(row['entries']))
 else:
  ck(stat.S_ISREG(a[2]) and a[4]<=67108864,'bounded E file');ident=identity(p);ck(ident['resolved_path']==str(p) and not ident['symlink_chain'] and ident['state'][3]==1,'literal single-link E file');total+=ident['bytes'];ck(total<=536870912,'aggregate E cap');row.update(kind='file',identity=ident)
 eq(state(p),a,'E entry stable');live.append(row)
for row in live:
 p=E/row['relative'];eq(state(p),row['state'],'E final whole state')
 if row['kind']=='directory':eq(sorted(x.name for x in p.iterdir()),row['entries'],'E final membership')
live.sort(key=lambda x:x['relative']);eq(live,etree,'entire fresh E equals actual prepared E');eq(etree,oldobs['E_after'],'entire prepared E equals retained postwrite baseline');eq([len(live),sum(v['kind']=='file' for v in live),sum(v['kind']=='directory' for v in live)],[58,49,9],'whole E counts');eq(identity(E/'AUTHORIZED_FREEZE.json'),oldpost['installed_partial'],'whole exact retained partial selection');candidate=base['roles']['result'];verify(candidate);ck((E/'AUTHORIZED_FREEZE.json').read_bytes()==Path(candidate['path']).read_bytes(),'whole candidate bytes opaque equality')
for name in ['tmp','runs/normal','runs/optimized']:eq(list((E/name).iterdir()),[],'empty unadmitted E path '+name)
def slim(path):return {k:identity(path)[k] for k in ('path','bytes','sha256','state')}
roles=dict(copies=[dict(relative=x['relative'],original=slim(x['source']['path']),copy=slim(x['destination'])) for x in g['copied_files']],history=[slim(x['path']) for x in g['history_originals']],target_originals=[slim(x['original']) for x in g['sources']]);eq(roles,oldbefore['source_states'],'whole48/124/30 live retained selections')
eq([len(roles[k]) for k in ['copies','history','target_originals']],[48,124,30],'complete roles')
boot=(D/'RECONCILE_BOOTSTRAP.py').read_bytes();ck(boot==(PW/'RECONCILE_BOOTSTRAP.source-only.py').read_bytes(),'whole concrete bootstrap equals accepted source');template=Path(deps['roles']['bootstrap_template']['path']).read_text();changed=template
for old,new in build['bootstrap_replacements']:eq(changed.count(old),1,'single bootstrap adaptation');changed=changed.replace(old,new)
ck(boot==changed.encode(),'entire seven-replacement bootstrap correspondence');MONITOR=deps['roles']['monitor'];verify(MONITOR)
child=[VENDOR,'-I','-B',str(W/'reconcile_freeze.py'),'--admission',str(D/'ADMIT_RECONCILE.json')];call='module.child_run('+repr(child)+', Path('+repr(str(D/'monitor'))+"), 'RECONCILE', 180, expected_environment)";eq([l for l in boot.decode().splitlines() if l.startswith('module.child_run(')],[call],'one whole child call');popen="child = subprocess.Popen(command, stdin=subprocess.DEVNULL, stdout=output, stderr=errors,\n                                     cwd=out, env=env, start_new_session=True)";ck(popen in Path(MONITOR['path']).read_text(),'actual monitor cwd');guard="need(Path.cwd()==literal(D/'monitor') and literal(OUT)==OUT and literal(W)==W,'fixed operation paths')";ck(guard in (W/'reconcile_freeze.py').read_text(),'exact recovery cwd guard');cwd=dict(outer_cwd=str(D),child_cwd=str(D/'monitor'),monitor=MONITOR,exact_popen=popen,generated_child_call=call,reconciler=manifest['files'][4],reconciler_guard=guard,source_text_only=True,subject_execution=False)
expected_pre=dict(schema='ri226-root-reconciliation-preflight-v1',status='FRESH_EXACT_READ_ONLY_RECONCILIATION_PREFLIGHT',sources=pin(D/'SOURCES_BEFORE.json'),supplier=pin(D/'SUPPLIER_BEFORE.json'),E_before=pin(D/'E_BEFORE.json'),host_tool_receipts=pin(D/'HOST_BEFORE.json'),monitor_bootstrap=pin(D/'RECONCILE_BOOTSTRAP.py'),source_manifest=pin(W/'SOURCE_PINS.json'),environment=ENV,scientific_execution=False);eq(pre,expected_pre,'all ten preflight fields')
card=dict(schema='ri226-root-read-only-reconciliation-admission-v1',status='AUTHORIZE_ONE_READ_ONLY_RECONCILIATION',source_manifest=pin(W/'SOURCE_PINS.json'),source_review=pin(D/'ROOT_SOURCE_REVIEW.json'),preflight=pin(D/'RECONCILE_PREFLIGHT.json'),output=str(O),environment=ENV,limits=LIMITS,genuine_outer_required=True)
outer=['/usr/bin/env','-i',*[k+'='+v for k,v in ENV.items()],'/usr/bin/perl','-e','$SIG{ALRM}="DEFAULT"; alarm 960; exec @ARGV; die $!;',VENDOR,'-I','-B',str(D/'RECONCILE_BOOTSTRAP.py')];dispatch=dict(outer_argv=outer,shell_command=shlex.join(outer),cwd=str(D),login=False,bootstrap=pin(D/'RECONCILE_BOOTSTRAP.py'),monitor_source=MONITOR,external_timeout_seconds=960,single_attempt=True,actual_execution_not_yet_started=True)
eq(proposal,dict(schema='ri229-unissued-reconciliation-proposal-v1',status='UNISSUED_REQUIRES_ROOT_PREFLIGHT_REVIEW',proposed_admission_fields=card,future_admission_path=str(D/'ADMIT_RECONCILE.json'),dispatch_fields_without_admission=dispatch,active_card_created=False,dispatch_created=False),'entire seven-field proposal with all9+9 nested fields')
packet=[identity(x['path']) for x in rh['files']]+[identity(W/'HANDOFF.json')];review_support=[identity(review[k]['path']) for k in ('independent_review','root_metadata_check','root_manual_review')];prep_support=[identity(PW/'SOURCE_PINS.json'),identity(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json')]+[identity(x['path']) for x in prepmanifest['files']];depstates=[identity(x['path']) for x in deps['files']]
expected_c=dict(schema='ri229-root-preparation-custody-v1',status='PREPARED_NOT_ADMITTED_OR_DISPATCHED',sealed_source_packet=packet,root_review_support=review_support,preparation_source_manifest=pin(PW/'SOURCE_PINS.json'),preparation_source_review=pin(T/'RI229_PREPARATION_SOURCE_ACCEPTANCE.json'),preparation_support=prep_support,preparation_dependency_states=depstates,retained_failure=repair['roles']['original_complete'],retained_postflight=repair['roles']['postflight'],original_genuine_host=pin(T/'GENUINE_PREPARATION_HOST_TOOL.json'),canonical_genuine_host=pin(D/'HOST_GENUINE_TOOL.json'),monitor_template=deps['roles']['bootstrap_template'],bootstrap_replacements=build['bootstrap_replacements'],cwd_contract=cwd,source_domain=971,original_source_observation=repair['roles']['original_sources'],original_bindings=oldbefore['bindings'],root_namespace_before=['ROOT_SOURCE_REVIEW.json','worker_proposal'],root_namespace_expected_after=sorted(['ROOT_SOURCE_REVIEW.json','worker_proposal']+outputs+['tmp','monitor']),produced_before_custody={n:pin(D/n) for n in outputs[:-1]},prior_roles=810,copy_history_targets=[48,124,30],source_observations=pin(D/'SOURCES_BEFORE.json'),supplier_observation=pin(D/'SUPPLIER_BEFORE.json'),E_observation=pin(D/'E_BEFORE.json'),preflight=pin(D/'RECONCILE_PREFLIGHT.json'),unissued_proposal=pin(D/'RECONCILIATION_PROPOSAL.json'),preparation_source=pin(PW/'prepare_reconciliation.py'),tool_origin_and_startup_are_root_premises=True,scientific_execution=False,reconciliation_admitted=False,reconciliation_dispatched=False,E_read_only=True,ret_paused=True);eq(c,expected_c,'entire35-field custody including all nested fields')
summary=json.loads(genuine['terminal']['output']);eq(summary,dict(status='PREPARED_FOR_ROOT_PREFLIGHT_REVIEW_NO_ADMISSION',proposal=pin(D/'RECONCILIATION_PROPOSAL.json'),custody=pin(D/'PREPARATION_CUSTODY.json'),exact_tool_arguments=dict(cmd=dispatch['shell_command'],workdir=str(D),login=False,yield_time_ms=1000,max_output_tokens=4000)),'whole genuine terminal stdout binding')
eq(sorted(p.name for p in D.iterdir()),expected_c['root_namespace_expected_after'],'exact final13 root namespace')
for n in ['tmp','monitor']:ck((D/n).is_dir() and not (D/n).is_symlink(),'ordinary control directory');eq(list((D/n).iterdir()),[],'empty control directory')
for p in [O,D/'ADMIT_RECONCILE.json',D/'DISPATCH.json',E/'ADMIT_NORMAL.json',E/'ADMIT_OPTIMIZED.json']:ck(not os.path.lexists(p),'operational absence '+str(p))
# The primary genuine record lacks terminal call arguments; root supplies a separate
# authenticated additive receipt for complete session linkage, reviewed separately.
result=dict(schema='ri230-independent-concrete-preparation-check-v1',status='PASS_COMPLETE_PREPARED_METADATA_AND_CURRENT_CUSTODY_PENDING_GENUINE_TERMINAL_ARGUMENTS',checks=len(labels),labels=labels,whole_file_identities=[seen[k] for k in sorted(seen)],counts=dict(whole_files=len(seen),sources=971,original_sources=904,preparation_dependencies=992,vendor=1810,vendor_bytes=48024515,tools=4,supplier_namespace=195,supplier_absences=2,E_files=49,E_directories=9,outputs=9,root_members=13),outputs=[pin(D/n) for n in outputs],actual_preparation_tool=pin(T/'GENUINE_PREPARATION_TOOL.json'),actual_host=pin(T/'GENUINE_PREPARATION_HOST_TOOL.json'),whole_E=live,source_execution=False,reconciliation_admitted=False,frozen_custody_accepted=False,scientific_decode=False,qualification_credit=0,RET_paused=True)
raw=m.canonical(result)
with (R/'CHECK_RESULT.json').open('xb') as f:f.write(raw);f.flush();os.fsync(f.fileno())
print(json.dumps(dict(report=dict(path=str(R/'CHECK_RESULT.json'),bytes=len(raw),sha256=hashlib.sha256(raw).hexdigest()),checks=len(labels),whole_files=len(seen),status=result['status'])))
