import hashlib,importlib.util,json
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri204-root-adapters-f04k2tg9';W=D/'worker_proposal'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
hr=dict(path=str(W/'HANDOFF.json'),bytes=4966,sha256='fa6f25e0d79eaca70050c622e189f16b9fac897446a8d25b66089ab931ebef98');m.verify(hr['path'],hr);v=m.load(hr['path'])
assert sorted(p.name for p in W.iterdir())==sorted(v['namespace']) and len(v['namespace'])==13 and len(v['payloads'])==12
for r in v['payloads']:m.verify(r['path'],r)
review=m.save('INDEPENDENT_PREPARATION_REVIEW.json',dict(schema='ri204-independent-source-review-transcript-v1',reviewer='/root/archive_repro_review',status='NO_BLOCKING_DEFECT_IN_SEALED_OPERATION_PROPOSAL',handoff=hr,payloads=v['payloads'],scope='Complete three scripts, notes, complete delta, authoring/check sources and records, pertinent unchanged RI160 consumers/custody. Every caller/guard/runtime candidate field reconstructed; whole canonical output comparison. No proposal or subject execution.',independent_checks=[dict(chunk='ad0e4c',exit_code=0,predicates=4394,reference_occurrences=2188,distinct_opaque_pins=719,required_consumer_references=42,complete_source_diff_equal=True),dict(chunk='08505d',exit_code=0,exact_seal=True,complete_literal_bootstrap_correspondence=True)],source_reads=['03d16a','76a08d','0705e4','fa3648','59103d','42a113','4d176e'],diagnostics=[dict(chunk='25e1ff',exit_code=1,reason='Requested nonexistent ACTUAL_AUTHOR_TOOLS.json; recovered using actual AUTHORING_RECORD.json'),dict(chunk='4de2ca',reason='Display clipping recovered by targeted read and exact diff comparison')],prior_authorship='RI130/RI141 and RI154 review, not this proposal; earlier independently accepted semantics are inherited, not newly self-approved.',premises=['genuine external tool origin','fresh operational custody','stable supplier/host/cache and read-window','no descendants','sampled child RSS, not continuous/group quota'],candidate_acceptance=False,ret_paused=True))
print(m.save('ROOT_PREPARATION_DECISION.json',dict(schema='ri204-root-preparation-decision-v1',status='ACCEPT_SEALED_SOURCE_FOR_ONE_FRESH_PREPARATION',handoff=hr,independent_review=review,payloads=v['payloads'],manual_review='Root reviewed full draft and complete final prepare/predispatch/postcheck sources and notes, accepted RI200 source framing, literal monitor bootstrap, actual adapter/bindings/retained-contract branches. Final reread1c9fbe recovered clipped notes in48bf37. No blocker.',root_source_reads=['457b71','ca3101','c31668','812fd7','ddcf9f','6bfd78','1319b5','1c9fbe'],author_check=dict(chunk='59d5a6',exit_code=0,predicates=4915,pinned_inputs=715,required_consumer_references=42),author_prior_RI160_authorship_disclosed=True,execute_only_at_original_worker_path=True,operation='one prospective adapters administrative action; root separately reviews prepared dispatch before launch',scientific_execution=False,candidate_acceptance=False,freeze=False,ret_paused=True)))
