import hashlib,importlib.util
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri204-root-adapters-f04k2tg9'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
dispatch=m.load(D/'DISPATCH.json');post=m.load(D/'ACTUAL_ADAPTERS_POSTCHECK.json')
m.save('INDEPENDENT_CONCRETE_PREFLIGHT_REVIEW.json',dict(schema='ri204-independent-concrete-preflight-review-v1',status='PASS_BEFORE_ROOT_FRESH_PREDISPATCH',reviewer='/root/archive_repro_review',dispatch=m.ref(D/'DISPATCH.json'),admission=dispatch['admission'],preflight=dispatch['preflight'],bootstrap=dispatch['bootstrap'],tool=dict(chunk='c692a2',exit_code=0,predicates=5767,fresh_source_identities=722),reads=['79fedd exit0','83ce8c exit0'],scope='Closed12 admission, exact accepted request, literal dispatch/direct vendor/ten-field environment/unchanged limits, whole bootstrap derivation, four observation pins, all810 historical roles,659 prior sources and9 supplements; full saved1810vendor/195namespace/48Efile/nine-directory records. Absent output, empty monitor/tmp.',fresh_vendor_execution=False,failed_commands=[],prior_authorship='RI130/RI141, not current proposal; original independently accepted semantics remain inherited.',scientific_execution=False,ret_paused=True))
m.save('MEASUREMENT_ACTUAL_RECEIPTS.json',dict(schema='ri204-measurement-actual-receipts-v1',source_review=m.ref(D/'ROOT_PREPARATION_DECISION.json'),proposal_source_reads=['48bf37 exit0 (clipped notes recovered)','1c9fbe exit0 full final sources and notes','3f2fac exit0 full concrete card/dispatch/bootstrap/preflight','e6b5fb exit0 sealed payload/dispatch authentication'],preparation=dict(initial='6a7852',session_id=90595,terminal='d92429',exit_code=0),fresh_predispatch=dict(chunk='b52aeb',exit_code=0),actual_outer=m.ref(D/'GENUINE_TOOL.json'),actual_terminal=m.ref(D/'GENUINE_TERMINAL_ARGUMENTS.json'),postcheck=dict(chunk='206324',exit_code=0,record=m.ref(D/'ACTUAL_ADAPTERS_POSTCHECK.json')),root_actual_read='aea28d exit0',failed_subject_commands=[],subject_retries=0,scientific_execution=False,ret_paused=True))
review='''# Root review of the actual RI204 administrative adapters operation

The single admitted operation completed. This review records the root checks before separate independent actual review and issuance of candidate acceptance records. The operation itself did not grant acceptance.

The sealed source was reviewed in full, including the concrete RI160 adapters branch, acceptance_adapters and literal HISTORY/TARGET constants, inherited source/guard/profile premises and the complete unchanged whole-source RI141 monitor. The final postchecker independently reconstructs complete canonical RESULT bytes from authenticated administrative operands; it does not call the subject bindings. Thus the comparison checks every field and JSON type, including nested helpers, sources, profiles and interpreter records, rather than merely accepted-looking status strings.

Actual exec7f6855/session57986 and terminal942d82 exited0 with empty output. Exact initial/final tool objects and the terminal empty-write arguments are retained. Fresh predispatch b52aeb exit0 preceded the launch; postcheck206324 exit0 rechecked722 current source identities,1810vendor files/48024515bytes,195namespace rows,two absences,four primitives,host and full E. All810 historical role rows remain bound without treating old states as fresh observations. E still has48files/nine directories. The administrative output has exactly ATTEMPT,RESULT,COMPLETE; monitor has its four expected files and empty streams; tmp is empty. Complete is included in external post-custody. All7 independent adapter tails pass, including567dependency pins and all13 authenticated source records.

The monitor records2.414953375seconds,73valid RSS samples,peak211872KiB,maximum observed gap0.047343917seconds and final gap0.029915083seconds. The unchanged180second/524288KiB/25ms-target/100ms-gap/50ms-ps/64MiB-file and960second-outer bounds remain. These are sampled child observations, not continuous/group quotas; stable host/supplier/cache/read-window and no-descendants assumptions remain explicit. COMPLETE write and bootstrap return are covered by genuine outer exit, not the adapter pre-complete elapsed field.

Caller has11fields: all11helpers/30source pairs, retained HISTORY/TARGET pins, unchanged limits, original RI130 handoff, RI154 independent source review and explicit source-only/RET flags. Guards have8fields and preserve the entire original genuine65 acceptance, changing only helpers according to the separately accepted path-applicability decision. No guard is newly claimed to have run at E. Runtime has23fields: the full actual accepted profile, interpreter and inventory mapping, both profile references and review, complete five sidecars, and all8 explicit accepted applicability premises. The observed_dyld_routes field means the preobserved domain; full original attempts/errors remain bound through complete profiles. No new runtime capture or source/cache equivalence is claimed.

The candidate fields agree exactly with the reviewed inputs. Original author and reviewer prior RI130/141/160 roles are disclosed; independent earlier source and actual106 qualification remain inherited, not rerun or newly self-approved. No scientific body was decoded or scientific helper invoked. Actual WHITE15/W09, both179-control inventories,27/13/30 records,57artifacts,74postchecks,three science trees,RI131/full32 and selected public GWOSC reproduction remain later obligations. Normal actual acceptance must precede optimized. Calibration, protected validation, a native forward map and physical claims remain separate; RET alone remains paused.
'''
with (D/'ROOT_ACTUAL_ADAPTERS_REVIEW.md').open('x') as f:f.write(review)
for name in ('ri204_accept_preparation.py','ri204_save_genuine.py','ri204_record_actual.py'):
 with (D/name).open('xb') as f:f.write((Path('/private/tmp')/name).read_bytes())
print(m.ref(D/'ROOT_ACTUAL_ADAPTERS_REVIEW.md'))
