import hashlib,importlib.util
from pathlib import Path
B=Path('/Volumes/AI_DATA/development/det-review-evidence');D=B/'ri204-root-adapters-f04k2tg9';O=B/'ri156-operation-ri204-adapters-f04k2tg9'
h=B/'ri122-root-execution-review-6whn_vky/metadata.py';raw=h.read_bytes();assert len(raw)==3144 and hashlib.sha256(raw).hexdigest()=='d2825bb1ea78306388a410d9b5aa9b931f72cb6a78334bc69151560f6b2584a7'
s=importlib.util.spec_from_file_location('m',h);m=importlib.util.module_from_spec(s);s.loader.exec_module(m);m.D=D
result=dict(path=str(O/'RESULT.json'),bytes=46546,sha256='804196b08bbe96758279b66b1deac3da80d3cea67b7c1eb5169895c028997d62');complete=dict(path=str(O/'COMPLETE.json'),bytes=176901,sha256='7323135a4bd6b489f74eac74968c5618f164d51ef1f9143225abc509b7a3e470')
for r in (result,complete):m.verify(r['path'],r)
post=m.load(D/'ACTUAL_ADAPTERS_POSTCHECK.json');assert post['result']==result and post['complete']==complete and post['all_complete_candidate_fields_matched'] is True and post['all_seven_independent_tails_passed'] is True and post['candidate_acceptances_issued'] is False
review=m.save('INDEPENDENT_ACTUAL_ADAPTERS_REVIEW.json',dict(schema='ri204-independent-actual-adapters-review-v1',status='PASS_COMPLETE_SAVED_CANDIDATES_AND_CUSTODY',reviewer='/root/archive_repro_review',result=result,complete=complete,checker=dict(chunk='b37b35',exit_code=0,predicates=3829,distinct_fresh_whole_file_identities=2555),reads=['c17cf6 exit0','f780e2 exit0'],candidate_field_counts=dict(caller=11,guards=8,runtime=23),scope=['Every field of three candidates reconstructed independently with typed canonical RESULT equality','All COMPLETE fields, seven independent tails, captured sources/dependencies/output pins and final namespace','All73 monitor attempts/samples, complete empty streams, exact command/environment and genuine session/terminal relationships','Fresh722source/1810vendor/195namespace/fourprimitive/completeE custody; three operation files and empty temporary directory'],genuine_outer=m.ref(D/'GENUINE_TOOL.json'),terminal=m.ref(D/'GENUINE_TERMINAL_ARGUMENTS.json'),postcheck=m.ref(D/'ACTUAL_ADAPTERS_POSTCHECK.json'),failed_commands=[],subject_rerun=False,prior_authorship='RI130/RI141, not this proposal; actual result reviewed using previously accepted source semantics.',limitations=['genuine external tool origin supported by root receipts','sampled child RSS, not continuous/group quota','saved parent PID is not authenticated child identity','stable supplier/host/cache/read-window and no descendants remain premises','administrative result creates no freeze or WHITE/scientific credit'],ret_paused=True))
values=m.load(result['path']);assert {k:len(v) for k,v in values.items()}==dict(caller=11,guards=8,runtime=23)
(D/'accepted_adapters').mkdir()
cards={name:m.save('accepted_adapters/'+name.upper()+'_ACCEPTANCE.json',value) for name,value in values.items()}
for name,r in cards.items():assert Path(r['path']).read_bytes()==m.canonical(values[name])
accepted=m.save('ADAPTERS_ACCEPTANCE.json',dict(schema='ri204-root-actual-adapters-adjudication-v1',status='ACCEPT_COMPLETE_ADMINISTRATIVE_ADAPTERS',root_review=m.ref(D/'ROOT_ACTUAL_ADAPTERS_REVIEW.md'),independent_review=review,source_review=m.ref(D/'ROOT_PREPARATION_DECISION.json'),preflight_review=m.ref(D/'INDEPENDENT_CONCRETE_PREFLIGHT_REVIEW.json'),genuine_outer=m.ref(D/'GENUINE_TOOL.json'),terminal=m.ref(D/'GENUINE_TERMINAL_ARGUMENTS.json'),postcheck=m.ref(D/'ACTUAL_ADAPTERS_POSTCHECK.json'),post_custody=m.ref(D/'POST_CUSTODY.json'),result=result,complete=complete,accepted_adapters=cards,cards_are_complete_canonical_result_values=True,acceptance_scope='Administrative construction over separately accepted source, original guard applicability and complete current profiles. No guards newly ran at E; no runtime capture or source/cache equivalence claim.',frozen_environment_unchanged=True,scientific_execution=False,freeze_issued=False,mode_admission_issued=False,ret_paused=True))
request=m.save('FREEZE_REQUEST.json',dict(accepted_adapters=cards))
m.save('MEASUREMENT_NEXT_ACTION.json',dict(schema='ri204-next-measurement-action-v1',status='ROOT_OWNED_NEXT_BOUNDED_ACTION',action='freeze',request=request,adapters_acceptance=accepted,requirements=['fresh source/vendor/host/E custody and exact twelve-field admission for one bounded unchanged RI160 freeze action outside E','genuine monitor/terminal receipts and full candidate freeze reconstruction','independent review before issuing the accepted freeze at E','fresh per-mode custody and genuine normal WHITE execution/acceptance before optimized'],unchanged_limits=dict(wall_seconds=180,rss_kib=524288,target_poll_seconds=0.025,maximum_sample_gap_seconds=0.1,ps_timeout_seconds=0.05,file_bytes=67108864,outer_alarm_seconds=960),later_obligations=['WHITE15/W09','both179controls','27/13/30records','57artifacts','74postchecks','three science trees','RI131/full32','selected public GWOSC conventional reproduction'],no_missing_user_decision=True,scientific_execution_authorized=False,freeze_issued=False,calibration_or_native_forward_map_claimed=False,ret_paused=True))
with (D/'ri204_adjudicate_adapters.py').open('xb') as f:f.write(Path(__file__).read_bytes())
print(accepted);print(request);print(cards)
